/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BankTransferBalanceGetRequest,
  bankTransferBalanceGetRequestSchema,
} from '../models/bankTransferBalanceGetRequest.js';
import {
  BankTransferBalanceGetResponse,
  bankTransferBalanceGetResponseSchema,
} from '../models/bankTransferBalanceGetResponse.js';
import {
  BankTransferCancelRequest,
  bankTransferCancelRequestSchema,
} from '../models/bankTransferCancelRequest.js';
import {
  BankTransferCancelResponse,
  bankTransferCancelResponseSchema,
} from '../models/bankTransferCancelResponse.js';
import {
  BankTransferCreateRequest,
  bankTransferCreateRequestSchema,
} from '../models/bankTransferCreateRequest.js';
import {
  BankTransferCreateResponse,
  bankTransferCreateResponseSchema,
} from '../models/bankTransferCreateResponse.js';
import {
  BankTransferEventListRequest,
  bankTransferEventListRequestSchema,
} from '../models/bankTransferEventListRequest.js';
import {
  BankTransferEventListResponse,
  bankTransferEventListResponseSchema,
} from '../models/bankTransferEventListResponse.js';
import {
  BankTransferEventSyncRequest,
  bankTransferEventSyncRequestSchema,
} from '../models/bankTransferEventSyncRequest.js';
import {
  BankTransferEventSyncResponse,
  bankTransferEventSyncResponseSchema,
} from '../models/bankTransferEventSyncResponse.js';
import {
  BankTransferGetRequest,
  bankTransferGetRequestSchema,
} from '../models/bankTransferGetRequest.js';
import {
  BankTransferGetResponse,
  bankTransferGetResponseSchema,
} from '../models/bankTransferGetResponse.js';
import {
  BankTransferListRequest,
  bankTransferListRequestSchema,
} from '../models/bankTransferListRequest.js';
import {
  BankTransferListResponse,
  bankTransferListResponseSchema,
} from '../models/bankTransferListResponse.js';
import {
  BankTransferMigrateAccountRequest,
  bankTransferMigrateAccountRequestSchema,
} from '../models/bankTransferMigrateAccountRequest.js';
import {
  BankTransferMigrateAccountResponse,
  bankTransferMigrateAccountResponseSchema,
} from '../models/bankTransferMigrateAccountResponse.js';
import {
  BankTransferSweepGetRequest,
  bankTransferSweepGetRequestSchema,
} from '../models/bankTransferSweepGetRequest.js';
import {
  BankTransferSweepGetResponse,
  bankTransferSweepGetResponseSchema,
} from '../models/bankTransferSweepGetResponse.js';
import {
  BankTransferSweepListRequest,
  bankTransferSweepListRequestSchema,
} from '../models/bankTransferSweepListRequest.js';
import {
  BankTransferSweepListResponse,
  bankTransferSweepListResponseSchema,
} from '../models/bankTransferSweepListResponse.js';
import { BaseApi } from './baseApi.js';
import { ErrorError } from '../errors/errorError.js';

export class BankTransferApi extends BaseApi {
  /**
   * Use the `/bank_transfer/cancel` endpoint to cancel a bank transfer.  A transfer is eligible for
   * cancelation if the `cancellable` property returned by `/bank_transfer/get` is `true`.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferCancel(
    body: BankTransferCancelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferCancelResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/cancel');
    const mapped = req.prepareArgs({
      body: [body, bankTransferCancelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferCancelResponseSchema, requestOptions);
  }

  /**
   * The `/bank_transfer/sweep/get` endpoint fetches information about the sweep corresponding to the
   * given `sweep_id`.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferSweepGet(
    body: BankTransferSweepGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferSweepGetResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/sweep/get');
    const mapped = req.prepareArgs({
      body: [body, bankTransferSweepGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferSweepGetResponseSchema, requestOptions);
  }

  /**
   * Use the `/bank_transfer/list` endpoint to see a list of all your bank transfers and their statuses.
   * Results are paginated; use the `count` and `offset` query parameters to retrieve the desired bank
   * transfers.
   *
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferList(
    body: BankTransferListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferListResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/list');
    const mapped = req.prepareArgs({
      body: [body, bankTransferListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferListResponseSchema, requestOptions);
  }

  /**
   * `/bank_transfer/event/sync` allows you to request up to the next 25 bank transfer events that
   * happened after a specific `event_id`. Use the `/bank_transfer/event/sync` endpoint to guarantee you
   * have seen all bank transfer events.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferEventSync(
    body: BankTransferEventSyncRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferEventSyncResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/event/sync');
    const mapped = req.prepareArgs({
      body: [body, bankTransferEventSyncRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferEventSyncResponseSchema, requestOptions);
  }

  /**
   * As an alternative to adding Items via Link, you can also use the `/bank_transfer/migrate_account`
   * endpoint to migrate known account and routing numbers to Plaid Items.  Note that Items created in
   * this way are not compatible with endpoints for other products, such as `/accounts/balance/get`, and
   * can only be used with Bank Transfer endpoints.  If you require access to other endpoints, create the
   * Item through Link instead.  Access to `/bank_transfer/migrate_account` is not enabled by default; to
   * obtain access, contact your Plaid Account Manager.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferMigrateAccount(
    body: BankTransferMigrateAccountRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferMigrateAccountResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/migrate_account');
    const mapped = req.prepareArgs({
      body: [body, bankTransferMigrateAccountRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      bankTransferMigrateAccountResponseSchema,
      requestOptions
    );
  }

  /**
   * Use the `/bank_transfer/create` endpoint to initiate a new bank transfer.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferCreate(
    body: BankTransferCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferCreateResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/create');
    const mapped = req.prepareArgs({
      body: [body, bankTransferCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferCreateResponseSchema, requestOptions);
  }

  /**
   * The `/bank_transfer/sweep/list` endpoint fetches information about the sweeps matching the given
   * filters.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferSweepList(
    body: BankTransferSweepListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferSweepListResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/sweep/list');
    const mapped = req.prepareArgs({
      body: [body, bankTransferSweepListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferSweepListResponseSchema, requestOptions);
  }

  /**
   * Use the `/bank_transfer/event/list` endpoint to get a list of bank transfer events based on
   * specified filter criteria.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferEventList(
    body: BankTransferEventListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferEventListResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/event/list');
    const mapped = req.prepareArgs({
      body: [body, bankTransferEventListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferEventListResponseSchema, requestOptions);
  }

  /**
   * The `/bank_transfer/get` fetches information about the bank transfer corresponding to the given
   * `bank_transfer_id`.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferGet(
    body: BankTransferGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferGetResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/get');
    const mapped = req.prepareArgs({
      body: [body, bankTransferGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferGetResponseSchema, requestOptions);
  }

  /**
   * Use the `/bank_transfer/balance/get` endpoint to see the available balance in your bank transfer
   * account. Debit transfers increase this balance once their status is posted. Credit transfers
   * decrease this balance when they are created.
   *
   * The transactable balance shows the amount in your account that you are able to use for transfers,
   * and is essentially your available balance minus your minimum balance.
   *
   * Note that this endpoint can only be used with FBO accounts, when using Bank Transfers in the Full
   * Service configuration. It cannot be used on your own account when using Bank Transfers in the BTS
   * Platform configuration.
   *
   * @param body
   * @return Response from the API call
   */
  async bankTransferBalanceGet(
    body: BankTransferBalanceGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BankTransferBalanceGetResponse>> {
    const req = this.createRequest('POST', '/bank_transfer/balance/get');
    const mapped = req.prepareArgs({
      body: [body, bankTransferBalanceGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(bankTransferBalanceGetResponseSchema, requestOptions);
  }
}
