/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CategoriesGetResponse,
  categoriesGetResponseSchema,
} from '../models/categoriesGetResponse.js';
import { optional, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorError } from '../errors/errorError.js';

export class CategoriesApi extends BaseApi {
  /**
   * Send a request to the `/categories/get`  endpoint to get detailed information on categories returned
   * by Plaid. This endpoint does not require authentication.
   *
   * @param body
   * @return Response from the API call
   */
  async categoriesGet(
    body: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CategoriesGetResponse>> {
    const req = this.createRequest('POST', '/categories/get');
    const mapped = req.prepareArgs({ body: [body, optional(unknown())] });
    req.header('Content-Type', 'text/plain');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate(false);
    return req.callAsJson(categoriesGetResponseSchema, requestOptions);
  }
}
