/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  EmployersSearchRequest,
  employersSearchRequestSchema,
} from '../models/employersSearchRequest.js';
import {
  EmployersSearchResponse,
  employersSearchResponseSchema,
} from '../models/employersSearchResponse.js';
import { BaseApi } from './baseApi.js';

export class EmployersApi extends BaseApi {
  /**
   * `/employers/search` allows you the ability to search Plaid’s database of known employers, for use
   * with Deposit Switch. You can use this endpoint to look up a user's employer in order to confirm that
   * they are supported. Users with non-supported employers can then be routed out of the Deposit Switch
   * flow.
   *
   * The data in the employer database is currently limited. As the Deposit Switch and Income products
   * progress through their respective beta periods, more employers are being regularly added. Because
   * the employer database is frequently updated, we recommend that you do not cache or store data from
   * this endpoint for more than a day.
   *
   * @param body
   * @return Response from the API call
   */
  async employersSearch(
    body: EmployersSearchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EmployersSearchResponse>> {
    const req = this.createRequest('POST', '/employers/search');
    const mapped = req.prepareArgs({
      body: [body, employersSearchRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(employersSearchResponseSchema, requestOptions);
  }
}
