/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  InvestmentsHoldingsGetRequest,
  investmentsHoldingsGetRequestSchema,
} from '../models/investmentsHoldingsGetRequest.js';
import {
  InvestmentsHoldingsGetResponse,
  investmentsHoldingsGetResponseSchema,
} from '../models/investmentsHoldingsGetResponse.js';
import {
  InvestmentsTransactionsGetRequest,
  investmentsTransactionsGetRequestSchema,
} from '../models/investmentsTransactionsGetRequest.js';
import {
  InvestmentsTransactionsGetResponse,
  investmentsTransactionsGetResponseSchema,
} from '../models/investmentsTransactionsGetResponse.js';
import { BaseController } from './baseController.js';

export class InvestmentsController extends BaseController {
  /**
   * The `/investments/transactions/get` endpoint allows developers to retrieve user-authorized
   * transaction data for investment accounts.
   *
   * Transactions are returned in reverse-chronological order, and the sequence of transaction ordering
   * is stable and will not shift.
   *
   * Due to the potentially large number of investment transactions associated with an Item, results are
   * paginated. Manipulate the count and offset parameters in conjunction with the
   * `total_investment_transactions` response body field to fetch all available investment transactions.
   *
   * @param body
   * @return Response from the API call
   */
  async investmentsTransactionsGet(
    body: InvestmentsTransactionsGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvestmentsTransactionsGetResponse>> {
    const req = this.createRequest('POST', '/investments/transactions/get');
    const mapped = req.prepareArgs({
      body: [body, investmentsTransactionsGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      investmentsTransactionsGetResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/investments/holdings/get` endpoint allows developers to receive user-authorized stock position
   * data for `investment`-type accounts.
   *
   * @param body
   * @return Response from the API call
   */
  async investmentsHoldingsGet(
    body: InvestmentsHoldingsGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvestmentsHoldingsGetResponse>> {
    const req = this.createRequest('POST', '/investments/holdings/get');
    const mapped = req.prepareArgs({
      body: [body, investmentsHoldingsGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(investmentsHoldingsGetResponseSchema, requestOptions);
  }
}
