/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ItemAccessTokenInvalidateRequest,
  itemAccessTokenInvalidateRequestSchema,
} from '../models/itemAccessTokenInvalidateRequest.js';
import {
  ItemAccessTokenInvalidateResponse,
  itemAccessTokenInvalidateResponseSchema,
} from '../models/itemAccessTokenInvalidateResponse.js';
import {
  ItemApplicationListRequest,
  itemApplicationListRequestSchema,
} from '../models/itemApplicationListRequest.js';
import {
  ItemApplicationListResponse,
  itemApplicationListResponseSchema,
} from '../models/itemApplicationListResponse.js';
import {
  ItemApplicationScopesUpdateRequest,
  itemApplicationScopesUpdateRequestSchema,
} from '../models/itemApplicationScopesUpdateRequest.js';
import {
  ItemApplicationScopesUpdateResponse,
  itemApplicationScopesUpdateResponseSchema,
} from '../models/itemApplicationScopesUpdateResponse.js';
import {
  ItemGetRequest,
  itemGetRequestSchema,
} from '../models/itemGetRequest.js';
import {
  ItemGetResponse,
  itemGetResponseSchema,
} from '../models/itemGetResponse.js';
import {
  ItemImportRequest,
  itemImportRequestSchema,
} from '../models/itemImportRequest.js';
import {
  ItemImportResponse,
  itemImportResponseSchema,
} from '../models/itemImportResponse.js';
import {
  ItemPublicTokenCreateRequest,
  itemPublicTokenCreateRequestSchema,
} from '../models/itemPublicTokenCreateRequest.js';
import {
  ItemPublicTokenCreateResponse,
  itemPublicTokenCreateResponseSchema,
} from '../models/itemPublicTokenCreateResponse.js';
import {
  ItemPublicTokenExchangeRequest,
  itemPublicTokenExchangeRequestSchema,
} from '../models/itemPublicTokenExchangeRequest.js';
import {
  ItemPublicTokenExchangeResponse,
  itemPublicTokenExchangeResponseSchema,
} from '../models/itemPublicTokenExchangeResponse.js';
import {
  ItemRemoveRequest,
  itemRemoveRequestSchema,
} from '../models/itemRemoveRequest.js';
import {
  ItemRemoveResponse,
  itemRemoveResponseSchema,
} from '../models/itemRemoveResponse.js';
import {
  ItemWebhookUpdateRequest,
  itemWebhookUpdateRequestSchema,
} from '../models/itemWebhookUpdateRequest.js';
import {
  ItemWebhookUpdateResponse,
  itemWebhookUpdateResponseSchema,
} from '../models/itemWebhookUpdateResponse.js';
import { BaseController } from './baseController.js';
import { ErrorError } from '../errors/errorError.js';

export class ItemController extends BaseController {
  /**
   * By default, the `access_token` associated with an Item does not expire and should be stored in a
   * persistent, secure manner.
   *
   * You can use the `/item/access_token/invalidate` endpoint to rotate the `access_token` associated
   * with an Item. The endpoint returns a new `access_token` and immediately invalidates the previous
   * `access_token`.
   *
   *
   * @param body
   * @return Response from the API call
   */
  async itemAccessTokenInvalidate(
    body: ItemAccessTokenInvalidateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemAccessTokenInvalidateResponse>> {
    const req = this.createRequest('POST', '/item/access_token/invalidate');
    const mapped = req.prepareArgs({
      body: [body, itemAccessTokenInvalidateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      itemAccessTokenInvalidateResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/item/remove`  endpoint allows you to remove an Item. Once removed, the `access_token`
   * associated with the Item is no longer valid and cannot be used to access any data that was
   * associated with the Item.
   *
   * Note that in the Development environment, issuing an `/item/remove`  request will not decrement your
   * live credential count. To increase your credential account in Development, contact Support.
   *
   * Also note that for certain OAuth-based institutions, an Item removed via `/item/remove` may still
   * show as an active connection in the institution's OAuth permission manager.
   *
   * @param body
   * @return Response from the API call
   */
  async itemRemove(
    body: ItemRemoveRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemRemoveResponse>> {
    const req = this.createRequest('POST', '/item/remove');
    const mapped = req.prepareArgs({ body: [body, itemRemoveRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemRemoveResponseSchema, requestOptions);
  }

  /**
   * List a user’s connected applications
   *
   * @param body
   * @return Response from the API call
   */
  async itemApplicationList(
    body: ItemApplicationListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemApplicationListResponse>> {
    const req = this.createRequest('POST', '/item/application/list');
    const mapped = req.prepareArgs({
      body: [body, itemApplicationListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemApplicationListResponseSchema, requestOptions);
  }

  /**
   * Exchange a Link `public_token` for an API `access_token`. Link hands off the `public_token` client-
   * side via the `onSuccess` callback once a user has successfully created an Item. The `public_token`
   * is ephemeral and expires after 30 minutes.
   *
   * The response also includes an `item_id` that should be stored with the `access_token`. The `item_id`
   * is used to identify an Item in a webhook. The `item_id` can also be retrieved by making an
   * `/item/get` request.
   *
   * @param body
   * @return Response from the API call
   */
  async itemPublicTokenExchange(
    body: ItemPublicTokenExchangeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemPublicTokenExchangeResponse>> {
    const req = this.createRequest('POST', '/item/public_token/exchange');
    const mapped = req.prepareArgs({
      body: [body, itemPublicTokenExchangeRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      itemPublicTokenExchangeResponseSchema,
      requestOptions
    );
  }

  /**
   * Returns information about the status of an Item.
   *
   * @param body
   * @return Response from the API call
   */
  async itemGet(
    body: ItemGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemGetResponse>> {
    const req = this.createRequest('POST', '/item/get');
    const mapped = req.prepareArgs({ body: [body, itemGetRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemGetResponseSchema, requestOptions);
  }

  /**
   * Note: As of July 2020, the `/item/public_token/create` endpoint is deprecated. Instead, use
   * `/link/token/create` with an `access_token` to create a Link token for use with [update mode](https:
   * //plaid.com/docs/link/update-mode).
   *
   * If you need your user to take action to restore or resolve an error associated with an Item,
   * generate a public token with the `/item/public_token/create` endpoint and then initialize Link with
   * that `public_token`.
   *
   * A `public_token` is one-time use and expires after 30 minutes. You use a `public_token` to
   * initialize Link in [update mode](https://plaid.com/docs/link/update-mode) for a particular Item. You
   * can generate a `public_token` for an Item even if you did not use Link to create the Item originally.
   *
   * The `/item/public_token/create` endpoint is **not** used to create your initial `public_token`. If
   * you have not already received an `access_token` for a specific Item, use Link to obtain your
   * `public_token` instead. See the [Quickstart](https://plaid.com/docs/quickstart) for more information.
   *
   * @param body
   * @return Response from the API call
   */
  async itemCreatePublicToken(
    body: ItemPublicTokenCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemPublicTokenCreateResponse>> {
    const req = this.createRequest('POST', '/item/public_token/create');
    const mapped = req.prepareArgs({
      body: [body, itemPublicTokenCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemPublicTokenCreateResponseSchema, requestOptions);
  }

  /**
   * Enable consumers to update product access on selected accounts for an application.
   *
   * @param body
   * @return Response from the API call
   */
  async itemApplicationScopesUpdate(
    body: ItemApplicationScopesUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemApplicationScopesUpdateResponse>> {
    const req = this.createRequest('POST', '/item/application/scopes/update');
    const mapped = req.prepareArgs({
      body: [body, itemApplicationScopesUpdateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      itemApplicationScopesUpdateResponseSchema,
      requestOptions
    );
  }

  /**
   * The POST `/item/webhook/update` allows you to update the webhook URL associated with an Item. This
   * request triggers a [`WEBHOOK_UPDATE_ACKNOWLEDGED`](https://plaid.com/docs/api/webhooks/#item-webhook-
   * url-updated) webhook to the newly specified webhook URL.
   *
   * @param body
   * @return Response from the API call
   */
  async itemWebhookUpdate(
    body: ItemWebhookUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemWebhookUpdateResponse>> {
    const req = this.createRequest('POST', '/item/webhook/update');
    const mapped = req.prepareArgs({
      body: [body, itemWebhookUpdateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemWebhookUpdateResponseSchema, requestOptions);
  }

  /**
   * `/item/import` creates an Item via your Plaid Exchange Integration and returns an `access_token`. As
   * part of an `/item/import` request, you will include a User ID (`user_auth.user_id`) and
   * Authentication Token (`user_auth.auth_token`) that enable data aggregation through your Plaid
   * Exchange API endpoints. These authentication principals are to be chosen by you.
   *
   * Upon creating an Item via `/item/import`, Plaid will automatically begin an extraction of that Item
   * through the Plaid Exchange infrastructure you have already integrated. This will automatically
   * generate the Plaid native account ID for the account the user will switch their direct deposit to
   * (`target_account_id`).
   *
   * @param body
   * @return Response from the API call
   */
  async itemImport(
    body: ItemImportRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemImportResponse>> {
    const req = this.createRequest('POST', '/item/import');
    const mapped = req.prepareArgs({ body: [body, itemImportRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(itemImportResponseSchema, requestOptions);
  }
}
