/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  PaymentInitiationPaymentCreateRequest,
  paymentInitiationPaymentCreateRequestSchema,
} from '../models/paymentInitiationPaymentCreateRequest.js';
import {
  PaymentInitiationPaymentCreateResponse,
  paymentInitiationPaymentCreateResponseSchema,
} from '../models/paymentInitiationPaymentCreateResponse.js';
import {
  PaymentInitiationPaymentGetRequest,
  paymentInitiationPaymentGetRequestSchema,
} from '../models/paymentInitiationPaymentGetRequest.js';
import {
  PaymentInitiationPaymentGetResponse,
  paymentInitiationPaymentGetResponseSchema,
} from '../models/paymentInitiationPaymentGetResponse.js';
import {
  PaymentInitiationPaymentListRequest,
  paymentInitiationPaymentListRequestSchema,
} from '../models/paymentInitiationPaymentListRequest.js';
import {
  PaymentInitiationPaymentListResponse,
  paymentInitiationPaymentListResponseSchema,
} from '../models/paymentInitiationPaymentListResponse.js';
import {
  PaymentInitiationPaymentReverseRequest,
  paymentInitiationPaymentReverseRequestSchema,
} from '../models/paymentInitiationPaymentReverseRequest.js';
import {
  PaymentInitiationPaymentReverseResponse,
  paymentInitiationPaymentReverseResponseSchema,
} from '../models/paymentInitiationPaymentReverseResponse.js';
import {
  PaymentInitiationPaymentTokenCreateRequest,
  paymentInitiationPaymentTokenCreateRequestSchema,
} from '../models/paymentInitiationPaymentTokenCreateRequest.js';
import {
  PaymentInitiationPaymentTokenCreateResponse,
  paymentInitiationPaymentTokenCreateResponseSchema,
} from '../models/paymentInitiationPaymentTokenCreateResponse.js';
import {
  PaymentInitiationRecipientCreateRequest,
  paymentInitiationRecipientCreateRequestSchema,
} from '../models/paymentInitiationRecipientCreateRequest.js';
import {
  PaymentInitiationRecipientCreateResponse,
  paymentInitiationRecipientCreateResponseSchema,
} from '../models/paymentInitiationRecipientCreateResponse.js';
import {
  PaymentInitiationRecipientGetRequest,
  paymentInitiationRecipientGetRequestSchema,
} from '../models/paymentInitiationRecipientGetRequest.js';
import {
  PaymentInitiationRecipientGetResponse,
  paymentInitiationRecipientGetResponseSchema,
} from '../models/paymentInitiationRecipientGetResponse.js';
import {
  PaymentInitiationRecipientListRequest,
  paymentInitiationRecipientListRequestSchema,
} from '../models/paymentInitiationRecipientListRequest.js';
import {
  PaymentInitiationRecipientListResponse,
  paymentInitiationRecipientListResponseSchema,
} from '../models/paymentInitiationRecipientListResponse.js';
import { BaseApi } from './baseApi.js';

export class PaymentInitiationApi extends BaseApi {
  /**
   * Reverse a previously initiated payment.
   *
   * A payment can only be reversed once and will be refunded to the original sender's account.
   *
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationPaymentReverse(
    body: PaymentInitiationPaymentReverseRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationPaymentReverseResponse>> {
    const req = this.createRequest(
      'POST',
      '/payment_initiation/payment/reverse'
    );
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationPaymentReverseRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationPaymentReverseResponseSchema,
      requestOptions
    );
  }

  /**
   * Create a payment recipient for payment initiation.  The recipient must be in Europe, within a
   * country that is a member of the Single Euro Payment Area (SEPA).  For a standing order (recurring)
   * payment, the recipient must be in the UK.
   *
   * The endpoint is idempotent: if a developer has already made a request with the same payment details,
   * Plaid will return the same `recipient_id`.
   *
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationRecipientCreate(
    body: PaymentInitiationRecipientCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationRecipientCreateResponse>> {
    const req = this.createRequest(
      'POST',
      '/payment_initiation/recipient/create'
    );
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationRecipientCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationRecipientCreateResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/payment_initiation/recipient/list` endpoint list the payment recipients that you have
   * previously created.
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationRecipientList(
    body: PaymentInitiationRecipientListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationRecipientListResponse>> {
    const req = this.createRequest(
      'POST',
      '/payment_initiation/recipient/list'
    );
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationRecipientListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationRecipientListResponseSchema,
      requestOptions
    );
  }

  /**
   * Get details about a payment recipient you have previously created.
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationRecipientGet(
    body: PaymentInitiationRecipientGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationRecipientGetResponse>> {
    const req = this.createRequest('POST', '/payment_initiation/recipient/get');
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationRecipientGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationRecipientGetResponseSchema,
      requestOptions
    );
  }

  /**
   * After creating a payment recipient, you can use the `/payment_initiation/payment/create` endpoint to
   * create a payment to that recipient.  Payments can be one-time or standing order (recurring) and can
   * be denominated in either EUR or GBP.  If making domestic GBP-denominated payments, your recipient
   * must have been created with BACS numbers. In general, EUR-denominated payments will be sent via SEPA
   * Credit Transfer and GBP-denominated payments will be sent via the Faster Payments network, but the
   * payment network used will be determined by the institution. Payments sent via Faster Payments will
   * typically arrive immediately, while payments sent via SEPA Credit Transfer will typically arrive in
   * one business day.
   *
   * Standing orders (recurring payments) must be denominated in GBP and can only be sent to recipients
   * in the UK. Once created, standing order payments cannot be modified or canceled via the API. An end
   * user can cancel or modify a standing order directly on their banking application or website, or by
   * contacting the bank. Standing orders will follow the payment rules of the underlying rails (Faster
   * Payments in UK). Payments can be sent Monday to Friday, excluding bank holidays. If the pre-arranged
   * date falls on a weekend or bank holiday, the payment is made on the next working day. It is not
   * possible to guarantee the exact time the payment will reach the recipient’s account, although at
   * least 90% of standing order payments are sent by 6am.
   *
   * In the Development environment, payments must be below 5 GBP / EUR. For details on any payment
   * limits in Production, contact your Plaid Account Manager.
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationPaymentCreate(
    body: PaymentInitiationPaymentCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationPaymentCreateResponse>> {
    const req = this.createRequest(
      'POST',
      '/payment_initiation/payment/create'
    );
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationPaymentCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationPaymentCreateResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/payment_initiation/payment/get` endpoint can be used to check the status of a payment, as well
   * as to receive basic information such as recipient and payment amount. In the case of standing orders,
   * the `/payment_initiation/payment/get` endpoint will provide information about the status of the
   * overall standing order itself; the API cannot be used to retrieve payment status for individual
   * payments within a standing order.
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationPaymentGet(
    body: PaymentInitiationPaymentGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationPaymentGetResponse>> {
    const req = this.createRequest('POST', '/payment_initiation/payment/get');
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationPaymentGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationPaymentGetResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/payment_initiation/payment/token/create` endpoint has been deprecated. New Plaid customers
   * will be unable to use this endpoint, and existing customers are encouraged to migrate to the newer,
   * `link_token`-based flow. The recommended flow is to provide the `payment_id` to `/link/token/create`,
   * which returns a `link_token` used to initialize Link.
   *
   * The `/payment_initiation/payment/token/create` is used to create a `payment_token`, which can then
   * be used in Link initialization to enter a payment initiation flow. You can only use a
   * `payment_token` once. If this attempt fails, the end user aborts the flow, or the token expires, you
   * will need to create a new payment token. Creating a new payment token does not require end user
   * input.
   *
   * @param body
   * @return Response from the API call
   */
  async createPaymentToken(
    body: PaymentInitiationPaymentTokenCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationPaymentTokenCreateResponse>> {
    const req = this.createRequest(
      'POST',
      '/payment_initiation/payment/token/create'
    );
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationPaymentTokenCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationPaymentTokenCreateResponseSchema,
      requestOptions
    );
  }

  /**
   * The `/payment_initiation/payment/list` endpoint can be used to retrieve all created payments. By
   * default, the 10 most recent payments are returned. You can request more payments and paginate
   * through the results using the optional `count` and `cursor` parameters.
   *
   * @param body
   * @return Response from the API call
   */
  async paymentInitiationPaymentList(
    body: PaymentInitiationPaymentListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentInitiationPaymentListResponse>> {
    const req = this.createRequest('POST', '/payment_initiation/payment/list');
    const mapped = req.prepareArgs({
      body: [body, paymentInitiationPaymentListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      paymentInitiationPaymentListResponseSchema,
      requestOptions
    );
  }
}
