/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SignalDecisionReportRequest,
  signalDecisionReportRequestSchema,
} from '../models/signalDecisionReportRequest.js';
import {
  SignalDecisionReportResponse,
  signalDecisionReportResponseSchema,
} from '../models/signalDecisionReportResponse.js';
import {
  SignalEvaluateRequest,
  signalEvaluateRequestSchema,
} from '../models/signalEvaluateRequest.js';
import {
  SignalEvaluateResponse,
  signalEvaluateResponseSchema,
} from '../models/signalEvaluateResponse.js';
import {
  SignalReturnReportRequest,
  signalReturnReportRequestSchema,
} from '../models/signalReturnReportRequest.js';
import {
  SignalReturnReportResponse,
  signalReturnReportResponseSchema,
} from '../models/signalReturnReportResponse.js';
import { BaseController } from './baseController.js';
import { ErrorError } from '../errors/errorError.js';

export class SignalController extends BaseController {
  /**
   * Use `/signal/evaluate` to evaluate a planned ACH transaction to get a return risk assessment (such
   * as a risk score and risk tier) and additional risk signals.
   *
   * In order to obtain a valid score for an ACH transaction, Plaid must have an access token for the
   * account, and the Item must be healthy (receiving product updates) or have recently been in a healthy
   * state. If the transaction does not meet eligibility requirements, an error will be returned
   * corresponding to the underlying cause.
   *
   * @param body
   * @return Response from the API call
   */
  async signalEvaluate(
    body: SignalEvaluateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SignalEvaluateResponse>> {
    const req = this.createRequest('POST', '/signal/evaluate');
    const mapped = req.prepareArgs({
      body: [body, signalEvaluateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(signalEvaluateResponseSchema, requestOptions);
  }

  /**
   * After calling `/signal/evaluate`, call `/signal/decision/report` to report whether the transaction
   * was initiated. This endpoint will return an `INVALID_REQUEST` error if called a second time with a
   * different value for `initiated`.
   *
   * @param body
   * @return Response from the API call
   */
  async signalDecisionReport(
    body: SignalDecisionReportRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SignalDecisionReportResponse>> {
    const req = this.createRequest('POST', '/signal/decision/report');
    const mapped = req.prepareArgs({
      body: [body, signalDecisionReportRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(signalDecisionReportResponseSchema, requestOptions);
  }

  /**
   * Call the `/signal/return/report` endpoint to report a returned transaction that was previously sent
   * to the `/signal/evaluate` endpoint. Your feedback will be used by the model to incorporate the
   * latest risk trend in your portfolio.
   *
   * @param body
   * @return Response from the API call
   */
  async signalReturnReport(
    body: SignalReturnReportRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SignalReturnReportResponse>> {
    const req = this.createRequest('POST', '/signal/return/report');
    const mapped = req.prepareArgs({
      body: [body, signalReturnReportRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response.');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(signalReturnReportResponseSchema, requestOptions);
  }
}
