/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TransferAuthorizationCreateRequest,
  transferAuthorizationCreateRequestSchema,
} from '../models/transferAuthorizationCreateRequest.js';
import {
  TransferAuthorizationCreateResponse,
  transferAuthorizationCreateResponseSchema,
} from '../models/transferAuthorizationCreateResponse.js';
import {
  TransferCancelRequest,
  transferCancelRequestSchema,
} from '../models/transferCancelRequest.js';
import {
  TransferCancelResponse,
  transferCancelResponseSchema,
} from '../models/transferCancelResponse.js';
import {
  TransferCreateRequest,
  transferCreateRequestSchema,
} from '../models/transferCreateRequest.js';
import {
  TransferCreateResponse,
  transferCreateResponseSchema,
} from '../models/transferCreateResponse.js';
import {
  TransferEventListRequest,
  transferEventListRequestSchema,
} from '../models/transferEventListRequest.js';
import {
  TransferEventListResponse,
  transferEventListResponseSchema,
} from '../models/transferEventListResponse.js';
import {
  TransferEventSyncRequest,
  transferEventSyncRequestSchema,
} from '../models/transferEventSyncRequest.js';
import {
  TransferEventSyncResponse,
  transferEventSyncResponseSchema,
} from '../models/transferEventSyncResponse.js';
import {
  TransferGetRequest,
  transferGetRequestSchema,
} from '../models/transferGetRequest.js';
import {
  TransferGetResponse,
  transferGetResponseSchema,
} from '../models/transferGetResponse.js';
import {
  TransferListRequest,
  transferListRequestSchema,
} from '../models/transferListRequest.js';
import {
  TransferListResponse,
  transferListResponseSchema,
} from '../models/transferListResponse.js';
import { BaseController } from './baseController.js';
import { ErrorError } from '../errors/errorError.js';

export class TransferController extends BaseController {
  /**
   * `/transfer/event/sync` allows you to request up to the next 25 transfer events that happened after a
   * specific `event_id`. Use the `/transfer/event/sync` endpoint to guarantee you have seen all transfer
   * events.
   *
   * @param body
   * @return Response from the API call
   */
  async transferEventSync(
    body: TransferEventSyncRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferEventSyncResponse>> {
    const req = this.createRequest('POST', '/transfer/event/sync');
    const mapped = req.prepareArgs({
      body: [body, transferEventSyncRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferEventSyncResponseSchema, requestOptions);
  }

  /**
   * Use the `/transfer/list` endpoint to see a list of all your transfers and their statuses. Results
   * are paginated; use the `count` and `offset` query parameters to retrieve the desired transfers.
   *
   *
   * @param body
   * @return Response from the API call
   */
  async transferList(
    body: TransferListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferListResponse>> {
    const req = this.createRequest('POST', '/transfer/list');
    const mapped = req.prepareArgs({ body: [body, transferListRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferListResponseSchema, requestOptions);
  }

  /**
   * The `/transfer/get` fetches information about the transfer corresponding to the given `transfer_id`.
   *
   * @param body
   * @return Response from the API call
   */
  async transferGet(
    body: TransferGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferGetResponse>> {
    const req = this.createRequest('POST', '/transfer/get');
    const mapped = req.prepareArgs({ body: [body, transferGetRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferGetResponseSchema, requestOptions);
  }

  /**
   * Use the `/transfer/cancel` endpoint to cancel a transfer.  A transfer is eligible for cancelation if
   * the `cancellable` property returned by `/transfer/get` is `true`.
   *
   * @param body
   * @return Response from the API call
   */
  async transferCancel(
    body: TransferCancelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferCancelResponse>> {
    const req = this.createRequest('POST', '/transfer/cancel');
    const mapped = req.prepareArgs({
      body: [body, transferCancelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferCancelResponseSchema, requestOptions);
  }

  /**
   * Use the `/transfer/create` endpoint to initiate a new transfer.
   *
   * @param body
   * @return Response from the API call
   */
  async transferCreate(
    body: TransferCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferCreateResponse>> {
    const req = this.createRequest('POST', '/transfer/create');
    const mapped = req.prepareArgs({
      body: [body, transferCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferCreateResponseSchema, requestOptions);
  }

  /**
   * Use the `/transfer/authorization/create` endpoint to determine transfer failure risk.
   *
   * In Plaid's sandbox environment the decisions will be returned as follows:
   *
   * - To approve a transfer, make an authorization request with an `amount` less than the available
   * balance in the account.
   *
   * - To decline a transfer with the rationale code `NSF`, the available balance on the account must
   * be less than the authorization `amount`. See [Create Sandbox test data](https://plaid.
   * com/docs/sandbox/user-custom/) for details on how to customize data in Sandbox.
   *
   * - To decline a transfer with the rationale code `RISK`, the available balance on the account must
   * be exactly $0. See [Create Sandbox test data](https://plaid.com/docs/sandbox/user-custom/) for
   * details on how to customize data in Sandbox.
   *
   * - To permit a transfer with the rationale code `MANUALLY_VERIFIED_ITEM`, create an Item in Link
   * through the [Same Day Micro-deposits flow](https://plaid.com/docs/auth/coverage/testing/#testing-
   * same-day-micro-deposits).
   *
   * - To permit a transfer with the rationale code `LOGIN_REQUIRED`, [reset the login for an
   * Item](https://plaid.com/docs/sandbox/#item_login_required).
   *
   * All username/password combinations other than the ones listed above will result in a decision of
   * permitted and rationale code `ERROR`.
   *
   * @param body
   * @return Response from the API call
   */
  async transferAuthorizationCreate(
    body: TransferAuthorizationCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferAuthorizationCreateResponse>> {
    const req = this.createRequest('POST', '/transfer/authorization/create');
    const mapped = req.prepareArgs({
      body: [body, transferAuthorizationCreateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      transferAuthorizationCreateResponseSchema,
      requestOptions
    );
  }

  /**
   * Use the `/transfer/event/list` endpoint to get a list of transfer events based on specified filter
   * criteria.
   *
   * @param body
   * @return Response from the API call
   */
  async transferEventList(
    body: TransferEventListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransferEventListResponse>> {
    const req = this.createRequest('POST', '/transfer/event/list');
    const mapped = req.prepareArgs({
      body: [body, transferEventListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(ErrorError, 'Error response');
    req.authenticate([
      { pLAIDCLIENTID: true, pLAIDSECRET: true, plaidVersion: true },
    ]);
    return req.callAsJson(transferEventListResponseSchema, requestOptions);
  }
}
