/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  WebhookVerificationKeyGetRequest,
  webhookVerificationKeyGetRequestSchema,
} from '../models/webhookVerificationKeyGetRequest.js';
import {
  WebhookVerificationKeyGetResponse,
  webhookVerificationKeyGetResponseSchema,
} from '../models/webhookVerificationKeyGetResponse.js';
import { BaseApi } from './baseApi.js';

export class WebhookVerificationKeyApi extends BaseApi {
  /**
   * Plaid signs all outgoing webhooks and provides JSON Web Tokens (JWTs) so that you can verify the
   * authenticity of any incoming webhooks to your application. A message signature is included in the
   * `Plaid-Verification` header.
   *
   * The `/webhook_verification_key/get` endpoint provides a JSON Web Key (JWK) that can be used to
   * verify a JWT.
   *
   * @param body
   * @return Response from the API call
   */
  async webhookVerificationKeyGet(
    body: WebhookVerificationKeyGetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WebhookVerificationKeyGetResponse>> {
    const req = this.createRequest('POST', '/webhook_verification_key/get');
    const mapped = req.prepareArgs({
      body: [body, webhookVerificationKeyGetRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([
      { plaidClientId: true, plaidSecret: true, plaidVersion: true },
    ]);
    return req.callAsJson(
      webhookVerificationKeyGetResponseSchema,
      requestOptions
    );
  }
}
