/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountSubtypeEnum
 */
export enum AccountSubtypeEnum {
  Enum401a = '401a',
  Enum401k = '401k',
  Enum403B = '403B',
  Enum457b = '457b',
  Enum529 = '529',
  Brokerage = 'brokerage',
  EnumCashIsa = 'cash isa',
  EnumEducationSavingsAccount = 'education savings account',
  Ebt = 'ebt',
  EnumFixedAnnuity = 'fixed annuity',
  Gic = 'gic',
  EnumHealthReimbursementArrangement = 'health reimbursement arrangement',
  Hsa = 'hsa',
  Isa = 'isa',
  Ira = 'ira',
  Lif = 'lif',
  EnumLifeInsurance = 'life insurance',
  Lira = 'lira',
  Lrif = 'lrif',
  Lrsp = 'lrsp',
  EnumNontaxableBrokerageAccount = 'non-taxable brokerage account',
  Other = 'other',
  EnumOtherInsurance = 'other insurance',
  EnumOtherAnnuity = 'other annuity',
  Prif = 'prif',
  Rdsp = 'rdsp',
  Resp = 'resp',
  Rlif = 'rlif',
  Rrif = 'rrif',
  Pension = 'pension',
  EnumProfitSharingPlan = 'profit sharing plan',
  Retirement = 'retirement',
  Roth = 'roth',
  EnumRoth401k = 'roth 401k',
  Rrsp = 'rrsp',
  EnumSepIra = 'sep ira',
  EnumSimpleIra = 'simple ira',
  Sipp = 'sipp',
  EnumStockPlan = 'stock plan',
  EnumThriftSavingsPlan = 'thrift savings plan',
  Tfsa = 'tfsa',
  Trust = 'trust',
  Ugma = 'ugma',
  Utma = 'utma',
  EnumVariableAnnuity = 'variable annuity',
  EnumCreditCard = 'credit card',
  Paypal = 'paypal',
  Cd = 'cd',
  Checking = 'checking',
  Savings = 'savings',
  EnumMoneyMarket = 'money market',
  Prepaid = 'prepaid',
  Auto = 'auto',
  Business = 'business',
  Commercial = 'commercial',
  Construction = 'construction',
  Consumer = 'consumer',
  Home = 'home',
  EnumHomeEquity = 'home equity',
  Loan = 'loan',
  Mortgage = 'mortgage',
  Overdraft = 'overdraft',
  EnumLineOfCredit = 'line of credit',
  Student = 'student',
  EnumCashManagement = 'cash management',
  Keogh = 'keogh',
  EnumMutualFund = 'mutual fund',
  Recurring = 'recurring',
  Rewards = 'rewards',
  EnumSafeDeposit = 'safe deposit',
  Sarsep = 'sarsep',
  Payroll = 'payroll',
}

/**
 * Schema for AccountSubtypeEnum
 */
export const accountSubtypeEnumSchema: Schema<AccountSubtypeEnum> = stringEnum(
  AccountSubtypeEnum
);
