/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountsBalanceGetRequestOptions,
  accountsBalanceGetRequestOptionsSchema,
} from './accountsBalanceGetRequestOptions.js';

/** AccountsBalanceGetRequest defines the request schema for `/accounts/balance/get` */
export interface AccountsBalanceGetRequest {
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** An optional object to filter `/accounts/balance/get` results. */
  options?: AccountsBalanceGetRequestOptions;
}

export const accountsBalanceGetRequestSchema: Schema<AccountsBalanceGetRequest> = lazy(
  () =>
    object({
      accessToken: ['access_token', string()],
      secret: ['secret', optional(string())],
      clientId: ['client_id', optional(string())],
      options: ['options', optional(accountsBalanceGetRequestOptionsSchema)],
    })
);
