/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Allow or disallow product access by account. Unlisted (e.g. missing) accounts will be considered `new_accounts`. */
export interface AccountAccess {
  /** The unique account identifier for this account. This value must match that returned by the data access API for this account. */
  uniqueId: string;
  /** Allow the application to see this account (and associated details, including balance) in the list of accounts. If unset, defaults to `true`. */
  authorized?: boolean | null;
  additionalProperties?: Record<string, unknown>;
}

export const accountAccessSchema: Schema<AccountAccess> = typedExpandoObject(
  {
    uniqueId: ['unique_id', string()],
    authorized: ['authorized', optional(nullable(boolean()))],
  },
  'additionalProperties',
  optional(unknown())
);
