/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An optional object to filter `/accounts/get` results. */
export interface AccountsGetRequestOptions {
  /** An array of `account_ids` to retrieve for the Account. */
  accountIds?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const accountsGetRequestOptionsSchema: Schema<AccountsGetRequestOptions> = typedExpandoObject(
  { accountIds: ['account_ids', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
