/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountsGetRequestOptions,
  accountsGetRequestOptionsSchema,
} from './accountsGetRequestOptions.js';

/** AccountsGetRequest defines the request schema for `/accounts/get` */
export interface AccountsGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** An optional object to filter `/accounts/get` results. */
  options?: AccountsGetRequestOptions;
  additionalProperties?: Record<string, unknown>;
}

export const accountsGetRequestSchema: Schema<AccountsGetRequest> = lazy(() =>
  typedExpandoObject(
    {
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      accessToken: ['access_token', string()],
      options: ['options', optional(accountsGetRequestOptionsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
