/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountSubtype1
 */
export enum AccountSubtype1 {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for AccountSubtype1
 */
export const accountSubtype1Schema: Schema<AccountSubtype1> = stringEnum(
  AccountSubtype1,
  true
);
