/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccountBalance, accountBalanceSchema } from './accountBalance.js';
import {
  AccountSubtypeEnum,
  accountSubtypeEnumSchema,
} from './accountSubtypeEnum.js';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum.js';
import {
  AssetReportTransaction,
  assetReportTransactionSchema,
} from './assetReportTransaction.js';
import {
  HistoricalBalance,
  historicalBalanceSchema,
} from './historicalBalance.js';
import { Owner, ownerSchema } from './owner.js';
import {
  VerificationStatus4Enum,
  verificationStatus4EnumSchema,
} from './verificationStatus4Enum.js';

export interface AccountAssets {
  /**
   * Plaid’s unique identifier for the account. This value will not change unless Plaid can't reconcile the account with the data returned by the financial institution. This may occur, for example, when the name of the account changes. If this happens a new `account_id` will be assigned to the account.
   * The `account_id` can also change if the `access_token` is deleted and the same credentials that were used to generate that `access_token` are used to generate a new `access_token` on a later date. In that case, the new `account_id` will be different from the old `account_id`.
   * If an account with a specific `account_id` disappears instead of changing, the account is likely closed. Closed accounts are not returned by the Plaid API.
   * Like all Plaid identifiers, the `account_id` is case sensitive.
   */
  accountId: string;
  /** A set of fields describing the balance for an account. Balance information may be cached unless the balance object was returned by `/accounts/balance/get`. */
  balances: AccountBalance;
  /** The last 2-4 alphanumeric characters of an account's official account number. Note that the mask may be non-unique between an Item's accounts, and it may also not match the mask that the bank displays to the user. */
  mask: string | null;
  /** The name of the account, either assigned by the user or by the financial institution itself */
  name: string;
  /** The official name of the account as given by the financial institution */
  officialName: string | null;
  /**
   * `investment:` Investment account
   * `credit:` Credit card
   * `depository:` Depository account
   * `loan:` Loan account
   * `brokerage`: An investment account. Used for `/assets/` endpoints only; other endpoints use `investment`.
   * `other:` Non-specified account type
   * See the [Account type schema](https://plaid.com/docs/api/accounts#account-type-schema) for a full listing of account types and corresponding subtypes.
   */
  type: AccountTypeEnum;
  /** See the [Account type schema](https://plaid.com/docs/api/accounts/#account-type-schema) for a full listing of account types and corresponding subtypes. */
  subtype: AccountSubtypeEnum;
  /**
   * The current verification status of an Auth Item initiated through Automated or Manual micro-deposits.  Returned for Auth Items only.
   * `pending_automatic_verification`: The Item is pending automatic verification
   * `pending_manual_verification`: The Item is pending manual micro-deposit verification. Items remain in this state until the user successfully verifies the two amounts.
   * `automatically_verified`: The Item has successfully been automatically verified
   * `manually_verified`: The Item has successfully been manually verified
   * `verification_expired`: Plaid was unable to automatically verify the deposit within 7 calendar days and will no longer attempt to validate the Item. Users may retry by submitting their information again through Link.
   * `verification_failed`: The Item failed manual micro-deposit verification because the user exhausted all 3 verification attempts. Users may retry by submitting their information again through Link.
   */
  verificationStatus?: VerificationStatus4Enum;
  /** The duration of transaction history available for this Item, typically defined as the time since the date of the earliest transaction in that account. Only returned by Assets endpoints. */
  daysAvailable: number;
  /** Transaction history associated with the account. Only returned by Assets endpoints. Transaction history returned by endpoints such as `/transactions/get` or `/investments/transactions/get` will be returned in the top-level `transactions` field instead. */
  transactions: AssetReportTransaction[];
  /** Data returned by the financial institution about the account owner or owners. Only returned by Identity or Assets endpoints. Multiple owners on a single account will be represented in the same `owner` object, not in multiple owner objects within the array. */
  owners: Owner[];
  /** Calculated data about the historical balances on the account. Only returned by Assets endpoints. */
  historicalBalances: HistoricalBalance[];
}

export const accountAssetsSchema: Schema<AccountAssets> = lazy(() =>
  object({
    accountId: ['account_id', string()],
    balances: ['balances', accountBalanceSchema],
    mask: ['mask', nullable(string())],
    name: ['name', string()],
    officialName: ['official_name', nullable(string())],
    type: ['type', accountTypeEnumSchema],
    subtype: ['subtype', accountSubtypeEnumSchema],
    verificationStatus: [
      'verification_status',
      optional(verificationStatus4EnumSchema),
    ],
    daysAvailable: ['days_available', number()],
    transactions: ['transactions', array(assetReportTransactionSchema)],
    owners: ['owners', array(ownerSchema)],
    historicalBalances: ['historical_balances', array(historicalBalanceSchema)],
  })
);
