/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { Item, itemSchema } from './item.js';

/** AccountsGetResponse defines the response schema for `/accounts/get` and `/accounts/balance/get`. */
export interface AccountsGetResponse {
  /**
   * An array of financial institution accounts associated with the Item.
   * If `/accounts/balance/get` was called, each account will include real-time balance information.
   */
  accounts: Account[];
  /** Metadata about the Item. */
  item: Item;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const accountsGetResponseSchema: Schema<AccountsGetResponse> = lazy(() =>
  typedExpandoObject(
    {
      accounts: ['accounts', array(accountSchema)],
      item: ['item', itemSchema],
      requestId: ['request_id', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
