/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Enumerates the account subtypes that the application wishes for the user to be able to select from. For more details refer to Plaid documentation on account filters. */
export interface AccountFilter {
  /** A list of account subtypes to be filtered. */
  depository?: string[];
  /** A list of account subtypes to be filtered. */
  credit?: string[];
  /** A list of account subtypes to be filtered. */
  loan?: string[];
  /** A list of account subtypes to be filtered. */
  investment?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const accountFilterSchema: Schema<AccountFilter> = typedExpandoObject(
  {
    depository: ['depository', optional(array(string()))],
    credit: ['credit', optional(array(string()))],
    loan: ['loan', optional(array(string()))],
    investment: ['investment', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
