/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AchClass
 */
export enum AchClass {
  Arc = 'arc',
  Cbr = 'cbr',
  Ccd = 'ccd',
  Cie = 'cie',
  Cor = 'cor',
  Ctx = 'ctx',
  Iat = 'iat',
  Mte = 'mte',
  Pbr = 'pbr',
  Pop = 'pop',
  Pos = 'pos',
  Ppd = 'ppd',
  Rck = 'rck',
  Tel = 'tel',
  Web = 'web',
}

/**
 * Schema for AchClass
 */
export const achClassSchema: Schema<AchClass> = stringEnum(AchClass, true);
