/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AddressData, addressDataSchema } from './addressData.js';

export interface AddressNullable {
  /** Data about the components comprising an address. */
  data: AddressData;
  /** When `true`, identifies the address as the primary address on an account. */
  primary?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const addressNullableSchema: Schema<AddressNullable> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', addressDataSchema],
      primary: ['primary', optional(boolean())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
