/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Data about the components comprising an address. */
export interface AddressData1 {
  /** The full city name */
  city?: string;
  /**
   * The region or state
   * Example: `"NC"`
   */
  region?: string | null;
  /**
   * The full street address
   * Example: `"564 Main Street, APT 15"`
   */
  street?: string;
  /** The postal code */
  postalCode?: string | null;
  /** The ISO 3166-1 alpha-2 country code */
  country?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const addressData1Schema: Schema<AddressData1> = typedExpandoObject(
  {
    city: ['city', optional(string())],
    region: ['region', optional(nullable(string()))],
    street: ['street', optional(string())],
    postalCode: ['postal_code', optional(nullable(string()))],
    country: ['country', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
