/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The address of the employee. */
export interface Address1 {
  /** The full city name. */
  city?: string;
  /**
   * The region or state
   * Example: `"NC"`
   */
  region?: string;
  /**
   * The full street address
   * Example: `"564 Main Street, APT 15"`
   */
  street?: string;
  /** 5 digit postal code. */
  postalCode?: string;
  /** The country of the address. */
  country?: string;
}

export const address1Schema: Schema<Address1> = object({
  city: ['city', optional(string())],
  region: ['region', optional(string())],
  street: ['street', optional(string())],
  postalCode: ['postal_code', optional(string())],
  country: ['country', optional(string())],
});
