/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import { AddressData, addressDataSchema } from './addressData.js';

/** A physical mailing address. */
export interface Address {
  /** Data about the components comprising an address. */
  data: AddressData;
  /** When `true`, identifies the address as the primary address on an account. */
  primary?: boolean;
}

export const addressSchema: Schema<Address> = lazy(() =>
  object({
    data: ['data', addressDataSchema],
    primary: ['primary', optional(boolean())],
  })
);
