/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Application, applicationSchema } from './application.js';

/** The request ID associated with this call. */
export interface ApplicationGetResponse {
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  /** Metadata about the application */
  application: Application;
  additionalProperties?: Record<string, unknown>;
}

export const applicationGetResponseSchema: Schema<ApplicationGetResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        requestId: ['request_id', string()],
        application: ['application', applicationSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
