/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AprType
 */
export enum AprType {
  BalanceTransferApr = 'balance_transfer_apr',
  CashApr = 'cash_apr',
  PurchaseApr = 'purchase_apr',
  Special = 'special',
}

/**
 * Schema for AprType
 */
export const aprTypeSchema: Schema<AprType> = stringEnum(AprType, true);
