/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AprTypeEnum
 */
export enum AprTypeEnum {
  BalanceTransferApr = 'balance_transfer_apr',
  CashApr = 'cash_apr',
  PurchaseApr = 'purchase_apr',
  Special = 'special',
}

/**
 * Schema for AprTypeEnum
 */
export const aprTypeEnumSchema: Schema<AprTypeEnum> = stringEnum(AprTypeEnum);
