/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** AssetReportFilterResponse defines the response schema for `/asset_report/filter` */
export interface AssetReportFilterResponse {
  /** A token that can be provided to endpoints such as `/asset_report/get` or `/asset_report/pdf/get` to fetch or update an Asset Report. */
  assetReportToken: string;
  /** A unique ID identifying an Asset Report. Like all Plaid identifiers, this ID is case sensitive. */
  assetReportId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const assetReportFilterResponseSchema: Schema<AssetReportFilterResponse> = object(
  {
    assetReportToken: ['asset_report_token', string()],
    assetReportId: ['asset_report_id', string()],
    requestId: ['request_id', string()],
  }
);
