/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentMeta, paymentMetaSchema } from './paymentMeta.js';
import {
  TransactionLocation,
  transactionLocationSchema,
} from './transactionLocation.js';
import { TransactionType, transactionTypeSchema } from './transactionType.js';

export interface AssetReportTransaction {
  /**
   * Please use the `payment_channel` field, `transaction_type` will be deprecated in the future.
   * `digital:` transactions that took place online.
   * `place:` transactions that were made at a physical location.
   * `special:` transactions that relate to banks, e.g. fees or deposits.
   * `unresolved:` transactions that do not fit into the other three types.
   */
  transactionType?: TransactionType;
  /** The ID of a posted transaction's associated pending transaction, where applicable. */
  pendingTransactionId?: string | null;
  /**
   * The ID of the category to which this transaction belongs. See [Categories](https://plaid.com/docs/#category-overview).
   * If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
   */
  categoryId?: string | null;
  /**
   * A hierarchical array of the categories to which this transaction belongs. See [Categories](https://plaid.com/docs/#category-overview).
   * If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
   */
  category?: string[] | null;
  /** A representation of where a transaction took place */
  location?: TransactionLocation;
  /**
   * Transaction information specific to inter-bank transfers. If the transaction was not an inter-bank transfer, all fields will be `null`.
   * If the `transactions` object was returned by a Transactions endpoint such as `/transactions/get`, the `payment_meta` key will always appear, but no data elements are guaranteed. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
   */
  paymentMeta?: PaymentMeta;
  /** The name of the account owner. This field is not typically populated and only relevant when dealing with sub-accounts. */
  accountOwner?: string | null;
  /**
   * The merchant name or transaction description.
   * If the `transactions` object was returned by a Transactions endpoint such as `/transactions/get`, this field will always appear. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
   */
  name?: string;
  /** The string returned by the financial institution to describe the transaction. For transactions returned by `/transactions/get`, this field is in beta and will be omitted unless the client is both enrolled in the closed beta program and has set `options.include_original_description` to `true`. */
  originalDescription: string | null;
  /** The ID of the account in which this transaction occurred. */
  accountId: string;
  /** The settled value of the transaction, denominated in the account's currency, as stated in `iso_currency_code` or `unofficial_currency_code`. Positive values when money moves out of the account; negative values when money moves in. For example, debit card purchases are positive; credit card payments, direct deposits, and refunds are negative. */
  amount: number;
  /** The ISO-4217 currency code of the transaction. Always `null` if `unofficial_currency_code` is non-null. */
  isoCurrencyCode: string | null;
  /**
   * The unofficial currency code associated with the transaction. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
   * See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
   */
  unofficialCurrencyCode: string | null;
  /** For pending transactions, the date that the transaction occurred; for posted transactions, the date that the transaction posted. Both dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ( `YYYY-MM-DD` ). */
  date: string;
  /** When `true`, identifies the transaction as pending or unsettled. Pending transaction details (name, type, amount, category ID) may change before they are settled. */
  pending: boolean;
  /** The unique ID of the transaction. Like all Plaid identifiers, the `transaction_id` is case sensitive. */
  transactionId: string;
  /** The date on which the transaction took place, in IS0 8601 format. */
  dateTransacted?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const assetReportTransactionSchema: Schema<AssetReportTransaction> = lazy(
  () =>
    typedExpandoObject(
      {
        transactionType: ['transaction_type', optional(transactionTypeSchema)],
        pendingTransactionId: [
          'pending_transaction_id',
          optional(nullable(string())),
        ],
        categoryId: ['category_id', optional(nullable(string()))],
        category: ['category', optional(nullable(array(string())))],
        location: ['location', optional(transactionLocationSchema)],
        paymentMeta: ['payment_meta', optional(paymentMetaSchema)],
        accountOwner: ['account_owner', optional(nullable(string()))],
        name: ['name', optional(string())],
        originalDescription: ['original_description', nullable(string())],
        accountId: ['account_id', string()],
        amount: ['amount', number()],
        isoCurrencyCode: ['iso_currency_code', nullable(string())],
        unofficialCurrencyCode: [
          'unofficial_currency_code',
          nullable(string()),
        ],
        date: ['date', string()],
        pending: ['pending', boolean()],
        transactionId: ['transaction_id', string()],
        dateTransacted: ['date_transacted', optional(nullable(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
