/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { AssetReport, assetReportSchema } from './assetReport.js';
import { Warning, warningSchema } from './warning.js';

/** AssetReportGetResponse defines the response schema for `/asset_report/get` */
export interface AssetReportGetResponse {
  /** An object representing an Asset Report */
  report: AssetReport;
  /** If the Asset Report generation was successful but identity information cannot be returned, this array will contain information about the errors causing identity information to be missing */
  warnings: Warning[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const assetReportGetResponseSchema: Schema<AssetReportGetResponse> = lazy(
  () =>
    object({
      report: ['report', assetReportSchema],
      warnings: ['warnings', array(warningSchema)],
      requestId: ['request_id', string()],
    })
);
