/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Fired when the Asset Report has been generated and `/asset_report/get` is ready to be called.  If you attempt to retrieve an Asset Report before this webhook has fired, you’ll receive a response with the HTTP status code 400 and a Plaid error code of `PRODUCT_NOT_READY`. */
export interface AssetsProductReadyWebhook {
  /** `ASSETS` */
  webhookType: string;
  /** `PRODUCT_READY` */
  webhookCode: string;
  /** The `asset_report_id` that can be provided to `/asset_report/get` to retrieve the Asset Report. */
  assetReportId: string;
}

export const assetsProductReadyWebhookSchema: Schema<AssetsProductReadyWebhook> = object(
  {
    webhookType: ['webhook_type', string()],
    webhookCode: ['webhook_code', string()],
    assetReportId: ['asset_report_id', string()],
  }
);
