/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  AssetReportCreateRequestOptions,
  assetReportCreateRequestOptionsSchema,
} from './assetReportCreateRequestOptions.js';

/** AssetReportCreateRequest defines the request schema for `/asset_report/create` */
export interface AssetReportCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** An array of access tokens corresponding to the Items that will be included in the report. The `assets` product must have been initialized for the Items during link; the Assets product cannot be added after initialization. */
  accessTokens: string[];
  /** The maximum integer number of days of history to include in the Asset Report. If using Fannie Mae Day 1 Certainty, `days_requested` must be at least 61 for new originations or at least 31 for refinancings. */
  daysRequested: number;
  /** An optional object to filter `/asset_report/create` results. If provided, must be non-`null`. The optional `user` object is required for the report to be eligible for Fannie Mae's Day 1 Certainty program. */
  options?: AssetReportCreateRequestOptions;
}

export const assetReportCreateRequestSchema: Schema<AssetReportCreateRequest> = lazy(
  () =>
    object({
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      accessTokens: ['access_tokens', array(string())],
      daysRequested: ['days_requested', number()],
      options: ['options', optional(assetReportCreateRequestOptionsSchema)],
    })
);
