/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

/** AssetReportGetRequest defines the request schema for `/asset_report/get` */
export interface AssetReportGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** A token that can be provided to endpoints such as `/asset_report/get` or `/asset_report/pdf/get` to fetch or update an Asset Report. */
  assetReportToken: string;
  /** `true` if you would like to retrieve the Asset Report with Insights, `false` otherwise. This field defaults to `false` if omitted. */
  includeInsights?: boolean;
}

export const assetReportGetRequestSchema: Schema<AssetReportGetRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    assetReportToken: ['asset_report_token', string()],
    includeInsights: ['include_insights', optional(boolean())],
  }
);
