/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountAssets, accountAssetsSchema } from './accountAssets.js';

/** A representation of an Item within an Asset Report. */
export interface AssetReportItem {
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  /** The full financial institution name associated with the Item. */
  institutionName: string;
  /** The id of the financial institution associated with the Item. */
  institutionId: string;
  /** The date and time when this Item’s data was last retrieved from the financial institution, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. */
  dateLastUpdated: string;
  /** Data about each of the accounts open on the Item. */
  accounts: AccountAssets[];
  additionalProperties?: Record<string, unknown>;
}

export const assetReportItemSchema: Schema<AssetReportItem> = lazy(() =>
  typedExpandoObject(
    {
      itemId: ['item_id', string()],
      institutionName: ['institution_name', string()],
      institutionId: ['institution_id', string()],
      dateLastUpdated: ['date_last_updated', string()],
      accounts: ['accounts', array(accountAssetsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
