/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** AssetReportAuditCopyCreateResponse defines the response schema for `/asset_report/audit_copy/get` */
export interface AssetReportAuditCopyCreateResponse {
  /** A token that can be shared with a third party auditor to allow them to obtain access to the Asset Report. This token should be stored securely. */
  auditCopyToken: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const assetReportAuditCopyCreateResponseSchema: Schema<AssetReportAuditCopyCreateResponse> = object(
  {
    auditCopyToken: ['audit_copy_token', string()],
    requestId: ['request_id', string()],
  }
);
