/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';

/** AssetReportRemoveResponse defines the response schema for `/asset_report/remove` */
export interface AssetReportRemoveResponse {
  /** `true` if the Asset Report was successfully removed. */
  removed: boolean;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const assetReportRemoveResponseSchema: Schema<AssetReportRemoveResponse> = object(
  { removed: ['removed', boolean()], requestId: ['request_id', string()] }
);
