/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AssetReportItem, assetReportItemSchema } from './assetReportItem.js';
import { AssetReportUser, assetReportUserSchema } from './assetReportUser.js';

/** An object representing an Asset Report */
export interface AssetReport {
  /** A unique ID identifying an Asset Report. Like all Plaid identifiers, this ID is case sensitive. */
  assetReportId: string;
  /** An identifier you determine and submit for the Asset Report. */
  clientReportId: string;
  /** The date and time when the Asset Report was created, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (e.g. "2018-04-12T03:32:11Z"). */
  dateGenerated: string;
  /** The duration of transaction history you requested */
  daysRequested: number;
  /** The user object allows you to provide additional information about the user to be appended to the Asset Report. All fields are optional. The `first_name`, `last_name`, and `ssn` fields are required if you would like the Report to be eligible for Fannie Mae’s Day 1 Certainty™ program. */
  user: AssetReportUser;
  /** Data returned by Plaid about each of the Items included in the Asset Report. */
  items: AssetReportItem[];
  additionalProperties?: Record<string, unknown>;
}

export const assetReportSchema: Schema<AssetReport> = lazy(() =>
  typedExpandoObject(
    {
      assetReportId: ['asset_report_id', string()],
      clientReportId: ['client_report_id', string()],
      dateGenerated: ['date_generated', string()],
      daysRequested: ['days_requested', number()],
      user: ['user', assetReportUserSchema],
      items: ['items', array(assetReportItemSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
