/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AssetReportUser, assetReportUserSchema } from './assetReportUser.js';

/** An optional object to filter `/asset_report/create` results. If provided, must be non-`null`. The optional `user` object is required for the report to be eligible for Fannie Mae's Day 1 Certainty program. */
export interface AssetReportCreateRequestOptions {
  /** Client-generated identifier, which can be used by lenders to track loan applications. */
  clientReportId?: string;
  /** URL to which Plaid will send Assets webhooks, for example when the requested Asset Report is ready. */
  webhook?: string;
  /** The user object allows you to provide additional information about the user to be appended to the Asset Report. All fields are optional. The `first_name`, `last_name`, and `ssn` fields are required if you would like the Report to be eligible for Fannie Mae’s Day 1 Certainty™ program. */
  user?: AssetReportUser;
  additionalProperties?: Record<string, unknown>;
}

export const assetReportCreateRequestOptionsSchema: Schema<AssetReportCreateRequestOptions> = lazy(
  () =>
    typedExpandoObject(
      {
        clientReportId: ['client_report_id', optional(string())],
        webhook: ['webhook', optional(string())],
        user: ['user', optional(assetReportUserSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
