/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

/** Metadata specifically related to which auth methods an institution supports. */
export interface AuthSupportedMethods {
  /** Indicates if instant auth is supported. */
  instantAuth: boolean;
  /** Indicates if instant match is supported. */
  instantMatch: boolean;
  /** Indicates if automated microdeposits are supported. */
  automatedMicroDeposits: boolean;
}

export const authSupportedMethodsSchema: Schema<AuthSupportedMethods> = object({
  instantAuth: ['instant_auth', boolean()],
  instantMatch: ['instant_match', boolean()],
  automatedMicroDeposits: ['automated_micro_deposits', boolean()],
});
