/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { NumbersAch, numbersAchSchema } from './numbersAch.js';
import { NumbersBacs, numbersBacsSchema } from './numbersBacs.js';
import { NumbersEft, numbersEftSchema } from './numbersEft.js';
import {
  NumbersInternational,
  numbersInternationalSchema,
} from './numbersInternational.js';

/** An object containing identifying numbers used for making electronic transfers to and from the `accounts`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by any `accounts` for which data has been requested, the array for that type will be empty. */
export interface AuthGetNumbers {
  /** An array of ACH numbers identifying accounts. */
  ach: NumbersAch[];
  /** An array of EFT numbers identifying accounts. */
  eft: NumbersEft[];
  /** An array of IBAN numbers identifying accounts. */
  international: NumbersInternational[];
  /** An array of BACS numbers identifying accounts. */
  bacs: NumbersBacs[];
  additionalProperties?: Record<string, unknown>;
}

export const authGetNumbersSchema: Schema<AuthGetNumbers> = lazy(() =>
  typedExpandoObject(
    {
      ach: ['ach', array(numbersAchSchema)],
      eft: ['eft', array(numbersEftSchema)],
      international: ['international', array(numbersInternationalSchema)],
      bacs: ['bacs', array(numbersBacsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
