/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { AuthGetNumbers, authGetNumbersSchema } from './authGetNumbers.js';
import { Item, itemSchema } from './item.js';

/** AuthGetResponse defines the response schema for `/auth/get` */
export interface AuthGetResponse {
  /** The `accounts` for which numbers are being retrieved. */
  accounts: Account[];
  /** An object containing identifying numbers used for making electronic transfers to and from the `accounts`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by any `accounts` for which data has been requested, the array for that type will be empty. */
  numbers: AuthGetNumbers;
  /** Metadata about the Item. */
  item: Item;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const authGetResponseSchema: Schema<AuthGetResponse> = lazy(() =>
  typedExpandoObject(
    {
      accounts: ['accounts', array(accountSchema)],
      numbers: ['numbers', authGetNumbersSchema],
      item: ['item', itemSchema],
      requestId: ['request_id', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
