/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AvailableBalanceEnum
 */
export enum AvailableBalanceEnum {
  Positive = 'positive',
  Negative = 'negative',
}

/**
 * Schema for AvailableBalanceEnum
 */
export const availableBalanceEnumSchema: Schema<AvailableBalanceEnum> = stringEnum(
  AvailableBalanceEnum
);
