/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AvailableBalance
 */
export enum AvailableBalance {
  Positive = 'positive',
  Negative = 'negative',
}

/**
 * Schema for AvailableBalance
 */
export const availableBalanceSchema: Schema<AvailableBalance> = stringEnum(
  AvailableBalance,
  true
);
