/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Defines the request schema for `/bank_transfer/cancel` */
export interface BankTransferCancelRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Plaid’s unique identifier for a bank transfer. */
  bankTransferId: string;
}

export const bankTransferCancelRequestSchema: Schema<BankTransferCancelRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    bankTransferId: ['bank_transfer_id', string()],
  }
);
