/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BankTransferEventType
 */
export enum BankTransferEventType {
  Pending = 'pending',
  Cancelled = 'cancelled',
  Failed = 'failed',
  Posted = 'posted',
  Reversed = 'reversed',
  ReceiverPending = 'receiver_pending',
  ReceiverPosted = 'receiver_posted',
}

/**
 * Schema for BankTransferEventType
 */
export const bankTransferEventTypeSchema: Schema<BankTransferEventType> = stringEnum(
  BankTransferEventType,
  true
);
