/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Defines the request schema for `/bank_transfer/balance/get` */
export interface BankTransferBalanceGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** If multiple origination accounts are available, `origination_account_id` must be used to specify the account for which balance will be returned. */
  originationAccountId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const bankTransferBalanceGetRequestSchema: Schema<BankTransferBalanceGetRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    originationAccountId: [
      'origination_account_id',
      optional(nullable(string())),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
