/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, nullable, object, Schema, string } from '../schema.js';
import {
  BankTransferSweepAccount,
  bankTransferSweepAccountSchema,
} from './bankTransferSweepAccount.js';

/** BankTransferSweep describes a sweep transfer. */
export interface BankTransferSweep {
  /** Identifier of the sweep. */
  id: bigint;
  /** Identifier of the sweep transfer. */
  transferId: string | null;
  /** The datetime when the sweep occurred, in RFC 3339 format. */
  createdAt: string;
  /** The amount of the sweep. */
  amount: string;
  /** The currency of the sweep, e.g. "USD". */
  isoCurrencyCode: string;
  /** The account where the funds are swept to. */
  sweepAccount: BankTransferSweepAccount;
}

export const bankTransferSweepSchema: Schema<BankTransferSweep> = lazy(() =>
  object({
    id: ['id', bigint()],
    transferId: ['transfer_id', nullable(string())],
    createdAt: ['created_at', string()],
    amount: ['amount', string()],
    isoCurrencyCode: ['iso_currency_code', string()],
    sweepAccount: ['sweep_account', bankTransferSweepAccountSchema],
  })
);
