/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BankTransferType1Enum
 */
export enum BankTransferType1Enum {
  Debit = 'debit',
  Credit = 'credit',
}

/**
 * Schema for BankTransferType1Enum
 */
export const bankTransferType1EnumSchema: Schema<BankTransferType1Enum> = stringEnum(
  BankTransferType1Enum
);
