/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fired when new bank transfer events are available. Receiving this webhook indicates you should fetch the new events from `/bank_transfer/event/sync`. */
export interface BankTransfersEventsUpdateWebhook {
  /** `BANK_TRANSFERS` */
  webhookType: string;
  /** `BANK_TRANSFERS_EVENTS_UPDATE` */
  webhookCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankTransfersEventsUpdateWebhookSchema: Schema<BankTransfersEventsUpdateWebhook> = typedExpandoObject(
  {
    webhookType: ['webhook_type', string()],
    webhookCode: ['webhook_code', string()],
  },
  'additionalProperties',
  optional(unknown())
);
