/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** The account where the funds are swept to. */
export interface BankTransferSweepAccount {
  accountNumber: string;
  routingNumber: string;
}

export const bankTransferSweepAccountSchema: Schema<BankTransferSweepAccount> = object(
  {
    accountNumber: ['account_number', string()],
    routingNumber: ['routing_number', string()],
  }
);
