/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Defines the response schema for `/bank_transfer/migrate_account` */
export interface BankTransferMigrateAccountResponse {
  /** The Plaid `access_token` for the newly created Item. */
  accessToken: string;
  /** The Plaid `account_id` for the newly created Item. */
  accountId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const bankTransferMigrateAccountResponseSchema: Schema<BankTransferMigrateAccountResponse> = object(
  {
    accessToken: ['access_token', string()],
    accountId: ['account_id', string()],
    requestId: ['request_id', string()],
  }
);
