/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

/** BankTransferSweepListRequest defines the request schema for `/bank_transfer/sweep/list` */
export interface BankTransferSweepListRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** If multiple origination accounts are available, `origination_account_id` must be used to specify the account that the sweeps belong to. */
  originationAccountId?: string | null;
  /** Starting ID of sweeps to return. */
  startId?: number | null;
  /** The start datetime of sweeps to return (RFC 3339 format). */
  startTime?: string | null;
  /** The end datetime of sweeps to return (RFC 3339 format). */
  endTime?: string | null;
  /** The maximum number of sweeps to return. */
  count?: number | null;
}

export const bankTransferSweepListRequestSchema: Schema<BankTransferSweepListRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    originationAccountId: [
      'origination_account_id',
      optional(nullable(string())),
    ],
    startId: ['start_id', optional(nullable(number()))],
    startTime: ['start_time', optional(nullable(string()))],
    endTime: ['end_time', optional(nullable(string()))],
    count: ['count', optional(nullable(number()))],
  }
);
