/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BankTransferBalance {
  /** The total available balance - the sum of all successful debit transfer amounts minus all credit transfer amounts. */
  available: string;
  /** The transactable balance shows the amount in your account that you are able to use for transfers, and is essentially your available balance minus your minimum balance. */
  transactable: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankTransferBalanceSchema: Schema<BankTransferBalance> = typedExpandoObject(
  {
    available: ['available', string()],
    transactable: ['transactable', string()],
  },
  'additionalProperties',
  optional(unknown())
);
