/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BankTransferTypeEnum
 */
export enum BankTransferTypeEnum {
  Debit = 'debit',
  Credit = 'credit',
}

/**
 * Schema for BankTransferTypeEnum
 */
export const bankTransferTypeEnumSchema: Schema<BankTransferTypeEnum> = stringEnum(
  BankTransferTypeEnum
);
