/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BankTransferEvent,
  bankTransferEventSchema,
} from './bankTransferEvent.js';

/** Defines the response schema for `/bank_transfer/event/list` */
export interface BankTransferEventListResponse {
  bankTransferEvents: BankTransferEvent[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankTransferEventListResponseSchema: Schema<BankTransferEventListResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        bankTransferEvents: [
          'bank_transfer_events',
          array(bankTransferEventSchema),
        ],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
