/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, Schema, string } from '../schema.js';
import {
  BankTransferBalance,
  bankTransferBalanceSchema,
} from './bankTransferBalance.js';

/** Defines the response schema for `/bank_transfer/balance/get` */
export interface BankTransferBalanceGetResponse {
  balance: BankTransferBalance;
  /** The ID of the origination account that this balance belongs to. */
  originationAccountId: string | null;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const bankTransferBalanceGetResponseSchema: Schema<BankTransferBalanceGetResponse> = lazy(
  () =>
    object({
      balance: ['balance', bankTransferBalanceSchema],
      originationAccountId: ['origination_account_id', nullable(string())],
      requestId: ['request_id', string()],
    })
);
