/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

/** Defines the request schema for `/bank_transfer/event/sync` */
export interface BankTransferEventSyncRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The latest (largest) `event_id` fetched via the sync endpoint, or 0 initially. */
  afterId: number;
  /** The maximum number of bank transfer events to return. */
  count?: number | null;
}

export const bankTransferEventSyncRequestSchema: Schema<BankTransferEventSyncRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    afterId: ['after_id', number()],
    count: ['count', optional(nullable(number()))],
  }
);
