/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

/** BankTransferSweepGetRequest defines the request schema for `/bank_transfer/sweep/get` */
export interface BankTransferSweepGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Identifier of the sweep. */
  sweepId: bigint;
  /** If multiple origination accounts are available, `origination_account_id` must be used to specify the account that the sweep belongs to. */
  originationAccountId?: string | null;
}

export const bankTransferSweepGetRequestSchema: Schema<BankTransferSweepGetRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    sweepId: ['sweep_id', bigint()],
    originationAccountId: [
      'origination_account_id',
      optional(nullable(string())),
    ],
  }
);
