/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The legal name and other information for the account holder. */
export interface BankTransferUser {
  /** The account holder’s full legal name. If the transfer description is `ccd`, this should be the business name of the account holder. */
  legalName: string;
  /** The account holder’s email. */
  emailAddress?: string | null;
  /** The account holder's routing number. This field is only used in response data. Do not provide this field when making requests. */
  routingNumber?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankTransferUserSchema: Schema<BankTransferUser> = typedExpandoObject(
  {
    legalName: ['legal_name', string()],
    emailAddress: ['email_address', optional(nullable(string()))],
    routingNumber: ['routing_number', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
