/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BankTransferStatus
 */
export enum BankTransferStatus {
  Pending = 'pending',
  Posted = 'posted',
  Cancelled = 'cancelled',
  Failed = 'failed',
  Reversed = 'reversed',
}

/**
 * Schema for BankTransferStatus
 */
export const bankTransferStatusSchema: Schema<BankTransferStatus> = stringEnum(
  BankTransferStatus,
  true
);
