/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema.js';
import {
  AvailableBalanceEnum,
  availableBalanceEnumSchema,
} from './availableBalanceEnum.js';

/** The receiver details if the type of this event is `reciever_pending` or `reciever_posted`. Null value otherwise. */
export interface BankTransferReceiverDetails {
  /** The sign of the available balance for the receiver bank account associated with the receiver event at the time the matching transaction was found. Can be `positive`, `negative`, or null if the balance was not available at the time. */
  availableBalance: AvailableBalanceEnum;
}

export const bankTransferReceiverDetailsSchema: Schema<BankTransferReceiverDetails> = object(
  { availableBalance: ['available_balance', availableBalanceEnumSchema] }
);
