/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  BankTransferSweep,
  bankTransferSweepSchema,
} from './bankTransferSweep.js';

/** BankTransferSweepGetResponse defines the response schema for `/bank_transfer/sweep/get` */
export interface BankTransferSweepGetResponse {
  /** BankTransferSweep describes a sweep transfer. */
  sweep: BankTransferSweep;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const bankTransferSweepGetResponseSchema: Schema<BankTransferSweepGetResponse> = lazy(
  () =>
    object({
      sweep: ['sweep', bankTransferSweepSchema],
      requestId: ['request_id', string()],
    })
);
