/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Activity that modifies a cash position */
export interface CashType {
  /** Fees paid for account maintenance */
  accountFee?: string;
  /** Inflow of assets into a tax-advantaged account */
  contribution?: string;
  /** Inflow of cash into an account */
  deposit?: string;
  /** Inflow of cash from a dividend */
  dividend?: string;
  /** Inflow of stock from a distribution */
  stockDistribution?: string;
  /** Inflow of cash from interest */
  interest?: string;
  /** Fees paid for legal charges or services */
  legalFee?: string;
  /** Long-term capital gain received as cash */
  longTermCapitalGain?: string;
  /** Fees paid for investment management of a mutual fund or other pooled investment vehicle */
  managementFee?: string;
  /** Fees paid for maintaining margin debt */
  marginExpense?: string;
  /** Inflow of cash from a non-qualified dividend */
  nonQualifiedDividend?: string;
  /** Taxes paid on behalf of the investor for non-residency in investment jurisdiction */
  nonResidentTax?: string;
  /** Pending inflow of cash */
  pendingCredit?: string;
  /** Pending outflow of cash */
  pendingDebit?: string;
  /** Inflow of cash from a qualified dividend */
  qualifiedDividend?: string;
  /** Short-term capital gain received as cash */
  shortTermCapitalGain?: string;
  /** Taxes paid on behalf of the investor */
  tax?: string;
  /** Taxes withheld on behalf of the customer */
  taxWithheld?: string;
  /** Fees incurred for transfer of a holding or account */
  transferFee?: string;
  /** Fees related to adminstration of a trust account */
  trustFee?: string;
  /** Unqualified capital gain received as cash */
  unqualifiedGain?: string;
  /** Outflow of cash from an account */
  withdrawal?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cashTypeSchema: Schema<CashType> = typedExpandoObject(
  {
    accountFee: ['account fee', optional(string())],
    contribution: ['contribution', optional(string())],
    deposit: ['deposit', optional(string())],
    dividend: ['dividend', optional(string())],
    stockDistribution: ['stock distribution', optional(string())],
    interest: ['interest', optional(string())],
    legalFee: ['legal fee', optional(string())],
    longTermCapitalGain: ['long-term capital gain', optional(string())],
    managementFee: ['management fee', optional(string())],
    marginExpense: ['margin expense', optional(string())],
    nonQualifiedDividend: ['non-qualified dividend', optional(string())],
    nonResidentTax: ['non-resident tax', optional(string())],
    pendingCredit: ['pending credit', optional(string())],
    pendingDebit: ['pending debit', optional(string())],
    qualifiedDividend: ['qualified dividend', optional(string())],
    shortTermCapitalGain: ['short-term capital gain', optional(string())],
    tax: ['tax', optional(string())],
    taxWithheld: ['tax withheld', optional(string())],
    transferFee: ['transfer fee', optional(string())],
    trustFee: ['trust fee', optional(string())],
    unqualifiedGain: ['unqualified gain', optional(string())],
    withdrawal: ['withdrawal', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
