/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema.js';

/** Information describing a transaction category */
export interface Category {
  /** An identifying number for the category. `category_id` is a Plaid-specific identifier and does not necessarily correspond to merchant category codes. */
  categoryId: string;
  /** `place` for physical transactions or `special` for other transactions such as bank charges. */
  group: string;
  /** A hierarchical array of the categories to which this `category_id` belongs. */
  hierarchy: string[];
}

export const categorySchema: Schema<Category> = object({
  categoryId: ['category_id', string()],
  group: ['group', string()],
  hierarchy: ['hierarchy', array(string())],
});
