/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Category, categorySchema } from './category.js';

/** CategoriesGetResponse defines the response schema for `/categories/get` */
export interface CategoriesGetResponse {
  /** An array of all of the transaction categories used by Plaid. */
  categories: Category[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const categoriesGetResponseSchema: Schema<CategoriesGetResponse> = lazy(
  () =>
    object({
      categories: ['categories', array(categorySchema)],
      requestId: ['request_id', string()],
    })
);
