/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Category, categorySchema } from './category.js';

/** CategoriesGetResponse defines the response schema for `/categories/get` */
export interface CategoriesGetResponse {
  /** An array of all of the transaction categories used by Plaid. */
  categories: Category[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const categoriesGetResponseSchema: Schema<CategoriesGetResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        categories: ['categories', array(categorySchema)],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
