/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';

/** An error object and associated `item_id` used to identify a specific Item and error when a batch operation operating on multiple Items has encountered an error in one of the Items. */
export interface Cause {
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error: Error;
  additionalProperties?: Record<string, unknown>;
}

export const causeSchema: Schema<Cause> = lazy(() =>
  typedExpandoObject(
    { itemId: ['item_id', string()], error: ['error', errorSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
