/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Code
 */
export enum Code {
  Nsf = 'NSF',
  Risk = 'RISK',
  ManuallyVerifiedItem = 'MANUALLY_VERIFIED_ITEM',
  LoginRequired = 'LOGIN_REQUIRED',
  Error = 'ERROR',
}

/**
 * Schema for Code
 */
export const codeSchema: Schema<Code> = stringEnum(Code, true);
