/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CodeEnum
 */
export enum CodeEnum {
  NSF = 'NSF',
  RISK = 'RISK',
  MANUALLYVERIFIEDITEM = 'MANUALLY_VERIFIED_ITEM',
  LOGINREQUIRED = 'LOGIN_REQUIRED',
  ERROR = 'ERROR',
}

/**
 * Schema for CodeEnum
 */
export const codeEnumSchema: Schema<CodeEnum> = stringEnum(CodeEnum);
