/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CountryCode
 */
export enum CountryCode {
  Us = 'US',
  Gb = 'GB',
  Es = 'ES',
  Nl = 'NL',
  Fr = 'FR',
  Ie = 'IE',
  Ca = 'CA',
}

/**
 * Schema for CountryCode
 */
export const countryCodeSchema: Schema<CountryCode> = stringEnum(
  CountryCode,
  true
);
