/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A credit card type account. Supported products for `credit` accounts are: Balance, Transactions, Identity, and Liabilities. */
export interface CreditAccount {
  /** Bank-issued credit card */
  creditCard: string;
  /** PayPal-issued credit card */
  paypal: string;
  additionalProperties?: Record<string, unknown>;
}

export const creditAccountSchema: Schema<CreditAccount> = typedExpandoObject(
  { creditCard: ['credit card', string()], paypal: ['paypal', string()] },
  'additionalProperties',
  optional(unknown())
);
