/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** A credit card type account. Supported products for `credit` accounts are: Balance, Transactions, Identity, and Liabilities. */
export interface CreditAccount {
  /** Bank-issued credit card */
  creditCard: string;
  /** PayPal-issued credit card */
  paypal: string;
}

export const creditAccountSchema: Schema<CreditAccount> = object({
  creditCard: ['credit card', string()],
  paypal: ['paypal', string()],
});
