/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CurrencyEnum
 */
export enum CurrencyEnum {
  GBP = 'GBP',
  EUR = 'EUR',
}

/**
 * Schema for CurrencyEnum
 */
export const currencyEnumSchema: Schema<CurrencyEnum> = stringEnum(
  CurrencyEnum
);
