/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Decision
 */
export enum Decision {
  Approved = 'approved',
  Permitted = 'permitted',
  Declined = 'declined',
}

/**
 * Schema for Decision
 */
export const decisionSchema: Schema<Decision> = stringEnum(Decision, true);
