/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Total, totalSchema } from './total.js';

/** An object with the deduction information found on a paystub. */
export interface Deductions {
  subtotals?: Total[];
  totals?: Total[];
}

export const deductionsSchema: Schema<Deductions> = lazy(() =>
  object({
    subtotals: ['subtotals', optional(array(totalSchema))],
    totals: ['totals', optional(array(totalSchema))],
  })
);
