/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { Error, errorSchema } from './error.js';

/** Fired when new transaction data is available for an Item. Plaid will typically check for new transaction data several times a day. */
export interface DefaultUpdateWebhook {
  /** `TRANSACTIONS` */
  webhookType: string;
  /** `DEFAULT_UPDATE` */
  webhookCode: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  /** The number of new transactions detected since the last time this webhook was fired. */
  newTransactions: number;
  /** The `item_id` of the Item the webhook relates to. */
  itemId: string;
}

export const defaultUpdateWebhookSchema: Schema<DefaultUpdateWebhook> = lazy(
  () =>
    object({
      webhookType: ['webhook_type', string()],
      webhookCode: ['webhook_code', string()],
      error: ['error', optional(errorSchema)],
      newTransactions: ['new_transactions', number()],
      itemId: ['item_id', string()],
    })
);
