/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** DepositSwitchTokenCreateResponse defines the response schema for `/deposit_switch/token/create` */
export interface DepositSwitchTokenCreateResponse {
  /** Deposit switch token, used to initialize Link for the Deposit Switch product */
  depositSwitchToken: string;
  /** Expiration time of the token, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format */
  depositSwitchTokenExpirationTime: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const depositSwitchTokenCreateResponseSchema: Schema<DepositSwitchTokenCreateResponse> = object(
  {
    depositSwitchToken: ['deposit_switch_token', string()],
    depositSwitchTokenExpirationTime: [
      'deposit_switch_token_expiration_time',
      string(),
    ],
    requestId: ['request_id', string()],
  }
);
