/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

/** Options to configure the `/deposit_switch/create` request. If provided, cannot be `null`. */
export interface DepositSwitchCreateRequestOptions {
  /** The URL registered to receive webhooks when the status of a deposit switch request has changed. */
  webhook?: string | null;
  /** An array of access tokens corresponding to transaction items to use when attempting to match the user to their Payroll Provider. These tokens must be created by the same client id as the one creating the switch, and have access to the transactions product. */
  transactionItemAccessTokens?: string[];
}

export const depositSwitchCreateRequestOptionsSchema: Schema<DepositSwitchCreateRequestOptions> = object(
  {
    webhook: ['webhook', optional(nullable(string()))],
    transactionItemAccessTokens: [
      'transaction_item_access_tokens',
      optional(array(string())),
    ],
  }
);
