/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CountryCode1, countryCode1Schema } from './countryCode1.js';
import {
  DepositSwitchCreateRequestOptions,
  depositSwitchCreateRequestOptionsSchema,
} from './depositSwitchCreateRequestOptions.js';
import {
  DepositSwitchTargetAccount,
  depositSwitchTargetAccountSchema,
} from './depositSwitchTargetAccount.js';
import {
  DepositSwitchTargetUser,
  depositSwitchTargetUserSchema,
} from './depositSwitchTargetUser.js';

/** DepositSwitchAltCreateRequest defines the request schema for `/deposit_switch/alt/create` */
export interface DepositSwitchAltCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  targetAccount: DepositSwitchTargetAccount;
  targetUser: DepositSwitchTargetUser;
  /** Options to configure the `/deposit_switch/create` request. If provided, cannot be `null`. */
  options?: DepositSwitchCreateRequestOptions;
  /** ISO-3166-1 alpha-2 country code standard. */
  countryCode?: CountryCode1;
  additionalProperties?: Record<string, unknown>;
}

export const depositSwitchAltCreateRequestSchema: Schema<DepositSwitchAltCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        secret: ['secret', optional(string())],
        targetAccount: ['target_account', depositSwitchTargetAccountSchema],
        targetUser: ['target_user', depositSwitchTargetUserSchema],
        options: ['options', optional(depositSwitchCreateRequestOptionsSchema)],
        countryCode: ['country_code', optional(countryCode1Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
