/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { State, stateSchema } from './state.js';
import { SwitchMethod, switchMethodSchema } from './switchMethod.js';

/** DepositSwitchGetResponse defines the response schema for `/deposit_switch/get` */
export interface DepositSwitchGetResponse {
  /** The ID of the deposit switch. */
  depositSwitchId: string;
  /** The ID of the bank account the direct deposit was switched to. */
  targetAccountId: string | null;
  /** The ID of the Item the direct deposit was switched to. */
  targetItemId: string | null;
  /**
   * The state, or status, of the deposit switch.
   * - `initialized` – The deposit switch has been initialized with the user entering the information required to submit the deposit switch request.
   * - `processing` – The deposit switch request has been submitted and is being processed.
   * - `completed` – The user's employer has fulfilled the deposit switch request.
   * - `error` – There was an error processing the deposit switch request.
   */
  state: State;
  /**
   * The method used to make the deposit switch.
   * - `instant` – User instantly switched their direct deposit to a new or existing bank account by connecting their payroll or employer account.
   * - `mail` – User requested that Plaid contact their employer by mail to make the direct deposit switch.
   * - `pdf` – User generated a PDF or email to be sent to their employer with the information necessary to make the deposit switch.'
   */
  switchMethod?: SwitchMethod;
  /** When `true`, user’s direct deposit goes to multiple banks. When false, user’s direct deposit only goes to the target account. Always `null` if the deposit switch has not been completed. */
  accountHasMultipleAllocations: boolean | null;
  /** When `true`, the target account is allocated the remainder of direct deposit after all other allocations have been deducted. When `false`, user’s direct deposit is allocated as a percent or amount. Always `null` if the deposit switch has not been completed. */
  isAllocatedRemainder: boolean | null;
  /** The percentage of direct deposit allocated to the target account. Always `null` if the target account is not allocated a percentage or if the deposit switch has not been completed or if `is_allocated_remainder` is true. */
  percentAllocated: number | null;
  /** The dollar amount of direct deposit allocated to the target account. Always `null` if the target account is not allocated an amount or if the deposit switch has not been completed. */
  amountAllocated: number | null;
  /** The name of the employer selected by the user. If the user did not select an employer, the value returned is `null`. */
  employerName?: string | null;
  /** The ID of the employer selected by the user. If the user did not select an employer, the value returned is `null`. */
  employerId?: string | null;
  /** The name of the institution selected by the user. If the user did not select an institution, the value returned is `null`. */
  institutionName?: string | null;
  /** The ID of the institution selected by the user. If the user did not select an institution, the value returned is `null`. */
  institutionId?: string | null;
  /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) date the deposit switch was created. */
  dateCreated: string;
  /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) date the deposit switch was completed. Always `null` if the deposit switch has not been completed. */
  dateCompleted: string | null;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const depositSwitchGetResponseSchema: Schema<DepositSwitchGetResponse> = typedExpandoObject(
  {
    depositSwitchId: ['deposit_switch_id', string()],
    targetAccountId: ['target_account_id', nullable(string())],
    targetItemId: ['target_item_id', nullable(string())],
    state: ['state', stateSchema],
    switchMethod: ['switch_method', optional(switchMethodSchema)],
    accountHasMultipleAllocations: [
      'account_has_multiple_allocations',
      nullable(boolean()),
    ],
    isAllocatedRemainder: ['is_allocated_remainder', nullable(boolean())],
    percentAllocated: ['percent_allocated', nullable(number())],
    amountAllocated: ['amount_allocated', nullable(number())],
    employerName: ['employer_name', optional(nullable(string()))],
    employerId: ['employer_id', optional(nullable(string()))],
    institutionName: ['institution_name', optional(nullable(string()))],
    institutionId: ['institution_id', optional(nullable(string()))],
    dateCreated: ['date_created', string()],
    dateCompleted: ['date_completed', nullable(string())],
    requestId: ['request_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
