/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** DepositSwitchCreateResponse defines the response schema for `/deposit_switch/create` */
export interface DepositSwitchCreateResponse {
  /** ID of the deposit switch. This ID is persisted throughout the lifetime of the deposit switch. */
  depositSwitchId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const depositSwitchCreateResponseSchema: Schema<DepositSwitchCreateResponse> = object(
  {
    depositSwitchId: ['deposit_switch_id', string()],
    requestId: ['request_id', string()],
  }
);
