/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import {
  AccountSubtype1Enum,
  accountSubtype1EnumSchema,
} from './accountSubtype1Enum.js';

export interface DepositSwitchTargetAccount {
  /** Account number for deposit switch destination */
  accountNumber: string;
  /** Routing number for deposit switch destination */
  routingNumber: string;
  /** The name of the deposit switch destination account, as it will be displayed to the end user in the Deposit Switch interface. It is not required to match the name used in online banking. */
  accountName: string;
  /** The account subtype of the account, either `checking` or `savings`. */
  accountSubtype: AccountSubtype1Enum;
}

export const depositSwitchTargetAccountSchema: Schema<DepositSwitchTargetAccount> = object(
  {
    accountNumber: ['account_number', string()],
    routingNumber: ['routing_number', string()],
    accountName: ['account_name', string()],
    accountSubtype: ['account_subtype', accountSubtype1EnumSchema],
  }
);
