/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** The user's address. */
export interface DepositSwitchAddressData {
  /** The full city name */
  city: string;
  /**
   * The region or state
   * Example: `"NC"`
   */
  region: string;
  /**
   * The full street address
   * Example: `"564 Main Street, APT 15"`
   */
  street: string;
  /** The postal code */
  postalCode: string;
  /** The ISO 3166-1 alpha-2 country code */
  country: string;
}

export const depositSwitchAddressDataSchema: Schema<DepositSwitchAddressData> = object(
  {
    city: ['city', string()],
    region: ['region', string()],
    street: ['street', string()],
    postalCode: ['postal_code', string()],
    country: ['country', string()],
  }
);
