/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Fired when the status of a deposit switch request has changed. */
export interface DepositSwitchStateUpdateWebhook {
  /** `"DEPOSIT_SWITCH"` */
  webhookType?: string;
  /** `"SWITCH_STATE_UPDATE"` */
  webhookCode?: string;
  /**
   * The state, or status, of the deposit switch.
   * `initialized`: The deposit switch has been initialized with the user entering the information required to submit the deposit switch request.
   * `processing`: The deposit switch request has been submitted and is being processed.
   * `completed`: The user's employer has fulfilled and completed the deposit switch request.
   * `error`: There was an error processing the deposit switch request.
   * For more information, see the [Deposit Switch API reference](/docs/api/products#deposit_switchget).
   */
  state?: string;
  /** The ID of the deposit switch. */
  depositSwitchId?: string;
}

export const depositSwitchStateUpdateWebhookSchema: Schema<DepositSwitchStateUpdateWebhook> = object(
  {
    webhookType: ['webhook_type', optional(string())],
    webhookCode: ['webhook_code', optional(string())],
    state: ['state', optional(string())],
    depositSwitchId: ['deposit_switch_id', optional(string())],
  }
);
