/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** DepositSwitchAltCreateResponse defines the response schema for `/deposit_switch/alt/create` */
export interface DepositSwitchAltCreateResponse {
  /** ID of the deposit switch. This ID is persisted throughout the lifetime of the deposit switch. */
  depositSwitchId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const depositSwitchAltCreateResponseSchema: Schema<DepositSwitchAltCreateResponse> = typedExpandoObject(
  {
    depositSwitchId: ['deposit_switch_id', string()],
    requestId: ['request_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
