/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import {
  CanonicalDescriptionEnum,
  canonicalDescriptionEnumSchema,
} from './canonicalDescriptionEnum.js';
import { Pay, paySchema } from './pay.js';

/** An object representing both the current pay period and year to date amount for an earning category. */
export interface EarningsTotal {
  /** Commonly used term to describe the line item. */
  canonicalDescription?: CanonicalDescriptionEnum;
  /** Text of the line item as printed on the paystub. */
  description?: string | null;
  /** An object representing a monetary amount. */
  currentPay?: Pay;
  /** An object representing a monetary amount. */
  ytdPay?: Pay;
  currentHours?: string | null;
  currentRate?: string | null;
}

export const earningsTotalSchema: Schema<EarningsTotal> = lazy(() =>
  object({
    canonicalDescription: [
      'canonical_description',
      optional(canonicalDescriptionEnumSchema),
    ],
    description: ['description', optional(nullable(string()))],
    currentPay: ['current_pay', optional(paySchema)],
    ytdPay: ['ytd_pay', optional(paySchema)],
    currentHours: ['current_hours', optional(nullable(string()))],
    currentRate: ['current_rate', optional(nullable(string()))],
  })
);
