/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The employer on the paystub. */
export interface Employer3 {
  /** The name of the employer. */
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const employer3Schema: Schema<Employer3> = typedExpandoObject(
  { name: ['name', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
