/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import { Pay, paySchema } from './pay.js';

/** An object representing employment details found on a paystub. */
export interface EmploymentDetails {
  /** An object representing a monetary amount. */
  annualSalary?: Pay;
  /** Date on which the employee was hired, in the YYYY-MM-DD format. */
  hireDate?: string | null;
}

export const employmentDetailsSchema: Schema<EmploymentDetails> = lazy(() =>
  object({
    annualSalary: ['annual_salary', optional(paySchema)],
    hireDate: ['hire_date', optional(nullable(string()))],
  })
);
