/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address1, address1Schema } from './address1.js';

/** The employee on the paystub. */
export interface Employee2 {
  /** The name of the employee. */
  name?: string;
  /** The address of the employee. */
  address?: Address1;
  additionalProperties?: Record<string, unknown>;
}

export const employee2Schema: Schema<Employee2> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', optional(string())],
      address: ['address', optional(address1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
