/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Employer, employerSchema } from './employer.js';

/** EmployersSearchResponse defines the response schema for `/employers/search`. */
export interface EmployersSearchResponse {
  /** A list of employers matching the search criteria. */
  employers: Employer[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const employersSearchResponseSchema: Schema<EmployersSearchResponse> = lazy(
  () =>
    object({
      employers: ['employers', array(employerSchema)],
      requestId: ['request_id', string()],
    })
);
