/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema.js';

/** EmployersSearchRequest defines the request schema for `/employers/search`. */
export interface EmployersSearchRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The employer name to be searched for. */
  query: string;
  /** The Plaid products the returned employers should support. Currently, this field must be set to `"deposit_switch"`. */
  products: string[];
}

export const employersSearchRequestSchema: Schema<EmployersSearchRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    query: ['query', string()],
    products: ['products', array(string())],
  }
);
