/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address2, address2Schema } from './address2.js';
import { TaxpayerId, taxpayerIdSchema } from './taxpayerId.js';

/** Data about the employee. */
export interface Employee {
  /** The name of the employee. */
  name: string | null;
  address: Address2;
  /** Marital status of the employee. */
  maritalStatus?: string | null;
  taxpayerId?: TaxpayerId;
  additionalProperties?: Record<string, unknown>;
}

export const employeeSchema: Schema<Employee> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', nullable(string())],
      address: ['address', address2Schema],
      maritalStatus: ['marital_status', optional(nullable(string()))],
      taxpayerId: ['taxpayer_id', optional(taxpayerIdSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
