/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ErrorTypeEnum
 */
export enum ErrorTypeEnum {
  INVALIDREQUEST = 'INVALID_REQUEST',
  INVALIDRESULT = 'INVALID_RESULT',
  INVALIDINPUT = 'INVALID_INPUT',
  INSTITUTIONERROR = 'INSTITUTION_ERROR',
  RATELIMITEXCEEDED = 'RATE_LIMIT_EXCEEDED',
  APIERROR = 'API_ERROR',
  ITEMERROR = 'ITEM_ERROR',
  ASSETREPORTERROR = 'ASSET_REPORT_ERROR',
  RECAPTCHAERROR = 'RECAPTCHA_ERROR',
  OAUTHERROR = 'OAUTH_ERROR',
  PAYMENTERROR = 'PAYMENT_ERROR',
  BANKTRANSFERERROR = 'BANK_TRANSFER_ERROR',
}

/**
 * Schema for ErrorTypeEnum
 */
export const errorTypeEnumSchema: Schema<ErrorTypeEnum> = stringEnum(
  ErrorTypeEnum
);
