/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorType, errorTypeSchema } from './errorType.js';

/** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
export interface Error {
  /** A broad categorization of the error. Safe for programatic use. */
  errorType: ErrorType;
  /** The particular error code. Safe for programmatic use. */
  errorCode: string;
  /** A developer-friendly representation of the error code. This may change over time and is not safe for programmatic use. */
  errorMessage: string;
  /**
   * A user-friendly representation of the error code. `null` if the error is not related to user action.
   * This may change over time and is not safe for programmatic use.
   */
  displayMessage: string | null;
  /** A unique ID identifying the request, to be used for troubleshooting purposes. This field will be omitted in errors provided by webhooks. */
  requestId?: string;
  /**
   * In the Assets product, a request can pertain to more than one Item. If an error is returned for such a request, `causes` will return an array of errors containing a breakdown of these errors on the individual Item level, if any can be identified.
   * `causes` will only be provided for the `error_type` `ASSET_REPORT_ERROR`.
   */
  causes?: unknown[];
  /** The HTTP status code associated with the error. This will only be returned in the response body when the error information is provided via a webhook. */
  status?: number | null;
  /** The URL of a Plaid documentation page with more information about the error */
  documentationUrl?: string;
  /** Suggested steps for resolving the error */
  suggestedAction?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorSchema: Schema<Error> = typedExpandoObject(
  {
    errorType: ['error_type', errorTypeSchema],
    errorCode: ['error_code', string()],
    errorMessage: ['error_message', string()],
    displayMessage: ['display_message', nullable(string())],
    requestId: ['request_id', optional(string())],
    causes: ['causes', optional(array(unknown()))],
    status: ['status', optional(nullable(number()))],
    documentationUrl: ['documentation_url', optional(string())],
    suggestedAction: ['suggested_action', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
