/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  RecipientBacsNullable,
  recipientBacsNullableSchema,
} from './recipientBacsNullable.js';

export interface ExternalPaymentRefundDetails {
  /** The name of the account holder. */
  name: string;
  /** The International Bank Account Number (IBAN) for the account. */
  iban: string | null;
  bacs: RecipientBacsNullable;
  additionalProperties?: Record<string, unknown>;
}

export const externalPaymentRefundDetailsSchema: Schema<ExternalPaymentRefundDetails> = lazy(
  () =>
    typedExpandoObject(
      {
        name: ['name', string()],
        iban: ['iban', nullable(string())],
        bacs: ['bacs', recipientBacsNullableSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
