/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fees on the account, e.g. commission, bookkeeping, options-related. */
export interface FeeType {
  /** Fees paid for account maintenance */
  accountFee?: string;
  /** Increase or decrease in quantity of item */
  adjustment?: string;
  /** Inflow of cash from a dividend */
  dividend?: string;
  /** Inflow of cash from interest */
  interest?: string;
  /** Inflow of cash from interest receivable */
  interestReceivable?: string;
  /** Long-term capital gain received as cash */
  longTermCapitalGain?: string;
  /** Fees paid for legal charges or services */
  legalFee?: string;
  /** Fees paid for investment management of a mutual fund or other pooled investment vehicle */
  managementFee?: string;
  /** Fees paid for maintaining margin debt */
  marginExpense?: string;
  /** Inflow of cash from a non-qualified dividend */
  nonQualifiedDividend?: string;
  /** Taxes paid on behalf of the investor for non-residency in investment jurisdiction */
  nonResidentTax?: string;
  /** Inflow of cash from a qualified dividend */
  qualifiedDividend?: string;
  /** Repayment of loan principal */
  returnOfPrincipal?: string;
  /** Short-term capital gain received as cash */
  shortTermCapitalGain?: string;
  /** Inflow of stock from a distribution */
  stockDistribution?: string;
  /** Taxes paid on behalf of the investor */
  tax?: string;
  /** Taxes withheld on behalf of the customer */
  taxWithheld?: string;
  /** Fees incurred for transfer of a holding or account */
  transferFee?: string;
  /** Fees related to adminstration of a trust account */
  trustFee?: string;
  /** Unqualified capital gain received as cash */
  unqualifiedGain?: string;
  additionalProperties?: Record<string, unknown>;
}

export const feeTypeSchema: Schema<FeeType> = typedExpandoObject(
  {
    accountFee: ['account fee', optional(string())],
    adjustment: ['adjustment', optional(string())],
    dividend: ['dividend', optional(string())],
    interest: ['interest', optional(string())],
    interestReceivable: ['interest receivable', optional(string())],
    longTermCapitalGain: ['long-term capital gain', optional(string())],
    legalFee: ['legal fee', optional(string())],
    managementFee: ['management fee', optional(string())],
    marginExpense: ['margin expense', optional(string())],
    nonQualifiedDividend: ['non-qualified dividend', optional(string())],
    nonResidentTax: ['non-resident tax', optional(string())],
    qualifiedDividend: ['qualified dividend', optional(string())],
    returnOfPrincipal: ['return of principal', optional(string())],
    shortTermCapitalGain: ['short-term capital gain', optional(string())],
    stockDistribution: ['stock distribution', optional(string())],
    tax: ['tax', optional(string())],
    taxWithheld: ['tax withheld', optional(string())],
    transferFee: ['transfer fee', optional(string())],
    trustFee: ['trust fee', optional(string())],
    unqualifiedGain: ['unqualified gain', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
