/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { IncidentUpdate, incidentUpdateSchema } from './incidentUpdate.js';

export interface HealthIncident {
  /** The start date of the incident, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `"2020-10-30T15:26:48Z"`. */
  startDate: string;
  /** The end date of the incident, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `"2020-10-30T15:26:48Z"`. */
  endDate?: string;
  /** The title of the incident */
  title: string;
  /** Updates on the health incident. */
  incidentUpdates: IncidentUpdate[];
  additionalProperties?: Record<string, unknown>;
}

export const healthIncidentSchema: Schema<HealthIncident> = lazy(() =>
  typedExpandoObject(
    {
      startDate: ['start_date', string()],
      endDate: ['end_date', optional(string())],
      title: ['title', string()],
      incidentUpdates: ['incident_updates', array(incidentUpdateSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
