/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { Error, errorSchema } from './error.js';

/** Fired when an Item's historical transaction pull is completed and Plaid has prepared as much historical transaction data as possible for the Item. Once this webhook has been fired, transaction data beyond the most recent 30 days can be fetched for the Item. If [Account Select v2](https://plaid.com/docs/link/customization/#account-select) is enabled, this webhook will also be fired if account selections for the Item are updated, with `num_transactions` set to the number of net new transactions pulled after the account selection update. */
export interface HistoricalUpdateWebhook {
  /** `TRANSACTIONS` */
  webhookType: string;
  /** `HISTORICAL_UPDATE` */
  webhookCode: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  /** The number of new, unfetched transactions available */
  newTransactions: number;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
}

export const historicalUpdateWebhookSchema: Schema<HistoricalUpdateWebhook> = lazy(
  () =>
    object({
      webhookType: ['webhook_type', string()],
      webhookCode: ['webhook_code', string()],
      error: ['error', optional(errorSchema)],
      newTransactions: ['new_transactions', number()],
      itemId: ['item_id', string()],
    })
);
