/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A securities holding at an institution. */
export interface Holding {
  /** The Plaid `account_id` associated with the holding. */
  accountId: string;
  /** The Plaid `security_id` associated with the holding. */
  securityId: string;
  /** The last price given by the institution for this security. */
  institutionPrice: number;
  /** The date at which `institution_price` was current. */
  institutionPriceAsOf: string | null;
  /** The value of the holding, as reported by the institution. */
  institutionValue: number;
  /** The cost basis of the holding. */
  costBasis: number | null;
  /** The total quantity of the asset held, as reported by the financial institution. If the security is an option, `quantity` will reflect the total number of options (typically the number of contracts multiplied by 100), not the number of contracts. */
  quantity: number;
  /** The ISO-4217 currency code of the holding. Always `null` if `unofficial_currency_code` is non-`null`. */
  isoCurrencyCode: string | null;
  /**
   * The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
   * See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
   */
  unofficialCurrencyCode: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const holdingSchema: Schema<Holding> = typedExpandoObject(
  {
    accountId: ['account_id', string()],
    securityId: ['security_id', string()],
    institutionPrice: ['institution_price', number()],
    institutionPriceAsOf: ['institution_price_as_of', nullable(string())],
    institutionValue: ['institution_value', number()],
    costBasis: ['cost_basis', nullable(number())],
    quantity: ['quantity', number()],
    isoCurrencyCode: ['iso_currency_code', nullable(string())],
    unofficialCurrencyCode: ['unofficial_currency_code', nullable(string())],
  },
  'additionalProperties',
  optional(unknown())
);
