/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema.js';

/** An optional object to filter `/identity/get` results. */
export interface IdentityGetRequestOptions {
  /**
   * A list of `account_ids` to retrieve for the Item.
   * Note: An error will be returned if a provided `account_id` is not associated with the Item.
   */
  accountIds?: string[];
}

export const identityGetRequestOptionsSchema: Schema<IdentityGetRequestOptions> = object(
  { accountIds: ['account_ids', optional(array(string()))] }
);
