/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { Status1Enum, status1EnumSchema } from './status1Enum.js';

export interface IncidentUpdate {
  /** The content of the update. */
  description?: string;
  /** The status of the incident. */
  status?: Status1Enum;
  /** The date when the update was published, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `"2020-10-30T15:26:48Z"`. */
  updatedDate?: string;
}

export const incidentUpdateSchema: Schema<IncidentUpdate> = object({
  description: ['description', optional(string())],
  status: ['status', optional(status1EnumSchema)],
  updatedDate: ['updated_date', optional(string())],
});
