/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type5, type5Schema } from './type5.js';

/** An object representing a breakdown of the different income types on the paystub. */
export interface IncomeBreakdown {
  /**
   * The type of income. Possible values include:
   *   `"regular"`: regular income
   *   `"overtime"`: overtime income
   *   `"bonus"`: bonus income
   */
  type: Type5;
  /** The hourly rate at which the income is paid. */
  rate: number | null;
  /** The number of hours logged for this income for this pay period. */
  hours: number | null;
  /** The total pay for this pay period. */
  total: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const incomeBreakdownSchema: Schema<IncomeBreakdown> = typedExpandoObject(
  {
    type: ['type', type5Schema],
    rate: ['rate', nullable(number())],
    hours: ['hours', nullable(number())],
    total: ['total', nullable(number())],
  },
  'additionalProperties',
  optional(unknown())
);
