/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IncomeVerificationPrecheckEmployer {
  /** The employer's name */
  name?: string | null;
  /** The employer's tax id */
  taxId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const incomeVerificationPrecheckEmployerSchema: Schema<IncomeVerificationPrecheckEmployer> = typedExpandoObject(
  {
    name: ['name', optional(nullable(string()))],
    taxId: ['tax_id', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
