/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** IncomeVerificationCreateResponse defines the response schema for `/income/verification/create`. */
export interface IncomeVerificationCreateResponse {
  /** ID of the verification. This ID is persisted throughout the lifetime of the verification. */
  incomeVerificationId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const incomeVerificationCreateResponseSchema: Schema<IncomeVerificationCreateResponse> = object(
  {
    incomeVerificationId: ['income_verification_id', string()],
    requestId: ['request_id', string()],
  }
);
