/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';
import { IncomeSummary, incomeSummarySchema } from './incomeSummary.js';

/** IncomeVerificationSummaryGetResponse defines the response schema for `/income/verification/summary/get`. */
export interface IncomeVerificationSummaryGetResponse {
  /** A list of income summaries. */
  incomeSummaries: IncomeSummary[];
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const incomeVerificationSummaryGetResponseSchema: Schema<IncomeVerificationSummaryGetResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        incomeSummaries: ['income_summaries', array(incomeSummarySchema)],
        error: ['error', optional(errorSchema)],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
