/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaystubOverride, paystubOverrideSchema } from './paystubOverride.js';

/** Specify payroll data on the account. */
export interface IncomeOverride {
  /** A list of paystubs associated with the account. */
  paystubs?: PaystubOverride[];
  additionalProperties?: Record<string, unknown>;
}

export const incomeOverrideSchema: Schema<IncomeOverride> = lazy(() =>
  typedExpandoObject(
    { paystubs: ['paystubs', optional(array(paystubOverrideSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
