/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** IncomeVerificationPaystubsGetRequest defines the request schema for `/income/verification/paystubs/get`. */
export interface IncomeVerificationPaystubsGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The ID of the verification for which to get paystub information. */
  incomeVerificationId?: string | null;
  /** The access token associated with the Item data is being requested for. */
  accessToken?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const incomeVerificationPaystubsGetRequestSchema: Schema<IncomeVerificationPaystubsGetRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    incomeVerificationId: [
      'income_verification_id',
      optional(nullable(string())),
    ],
    accessToken: ['access_token', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
