/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DocumentMetadata,
  documentMetadataSchema,
} from './documentMetadata.js';
import { Error, errorSchema } from './error.js';
import { Paystub, paystubSchema } from './paystub.js';

/** IncomeVerificationPaystubsGetResponse defines the response schema for `/income/verification/paystubs/get`. */
export interface IncomeVerificationPaystubsGetResponse {
  paystubs: Paystub[];
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  documentMetadata?: DocumentMetadata[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const incomeVerificationPaystubsGetResponseSchema: Schema<IncomeVerificationPaystubsGetResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        paystubs: ['paystubs', array(paystubSchema)],
        error: ['error', optional(errorSchema)],
        documentMetadata: [
          'document_metadata',
          optional(array(documentMetadataSchema)),
        ],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
