/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  DocumentMetadata,
  documentMetadataSchema,
} from './documentMetadata.js';
import { Error, errorSchema } from './error.js';
import { Taxform, taxformSchema } from './taxform.js';

/** IncomeVerificationTaxformsGetResponse defines the response schema for `/income/verification/taxforms/get` */
export interface IncomeVerificationTaxformsGetResponse {
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId?: string;
  /** A list of taxforms. */
  taxforms: Taxform[];
  documentMetadata: DocumentMetadata[];
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
}

export const incomeVerificationTaxformsGetResponseSchema: Schema<IncomeVerificationTaxformsGetResponse> = lazy(
  () =>
    object({
      requestId: ['request_id', optional(string())],
      taxforms: ['taxforms', array(taxformSchema)],
      documentMetadata: ['document_metadata', array(documentMetadataSchema)],
      error: ['error', optional(errorSchema)],
    })
);
