/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Confidence, confidenceSchema } from './confidence.js';

/** IncomeVerificationPrecheckResponse defines the response schema for `/income/verification/precheck`. */
export interface IncomeVerificationPrecheckResponse {
  /** ID of the precheck. */
  precheckId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  /**
   * The confidence that Plaid can support the user in the income verification flow. One of the following:
   * `"HIGH"`: This precheck information submitted is definitively tied to a Plaid-supported integration.
   * "`LOW`": This precheck information submitted is known not to be supported by Plaid.
   * `"UNKNOWN"`: It was not possible to determine if the user is supportable with the information passed.
   */
  confidence: Confidence;
  additionalProperties?: Record<string, unknown>;
}

export const incomeVerificationPrecheckResponseSchema: Schema<IncomeVerificationPrecheckResponse> = typedExpandoObject(
  {
    precheckId: ['precheck_id', string()],
    requestId: ['request_id', string()],
    confidence: ['confidence', confidenceSchema],
  },
  'additionalProperties',
  optional(unknown())
);
