/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fired when an Item's initial transaction pull is completed. Once this webhook has been fired, transaction data for the most recent 30 days can be fetched for the Item. If [Account Select v2](https://plaid.com/docs/link/customization/#account-select) is enabled, this webhook will also be fired if account selections for the Item are updated, with `num_transactions` set to the number of net new transactions pulled after the account selection update. */
export interface InitialUpdateWebhook {
  /** `TRANSACTIONS` */
  webhookType: string;
  /** `INITIAL_UPDATE` */
  webhookCode: string;
  /** The error code associated with the webhook. */
  error?: string | null;
  /** The number of new, unfetched transactions available. */
  newTransactions: number;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  additionalProperties?: Record<string, unknown>;
}

export const initialUpdateWebhookSchema: Schema<InitialUpdateWebhook> = typedExpandoObject(
  {
    webhookType: ['webhook_type', string()],
    webhookCode: ['webhook_code', string()],
    error: ['error', optional(nullable(string()))],
    newTransactions: ['new_transactions', number()],
    itemId: ['item_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
