/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Institution, institutionSchema } from './institution.js';

/** InstitutionsSearchResponse defines the response schema for `/institutions/search` */
export interface InstitutionsSearchResponse {
  /** An array of institutions matching the search criteria */
  institutions: Institution[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const institutionsSearchResponseSchema: Schema<InstitutionsSearchResponse> = lazy(
  () =>
    object({
      institutions: ['institutions', array(institutionSchema)],
      requestId: ['request_id', string()],
    })
);
