/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CountryCode, countryCodeSchema } from './countryCode.js';
import {
  InstitutionsSearchRequestOptions,
  institutionsSearchRequestOptionsSchema,
} from './institutionsSearchRequestOptions.js';
import { Products, productsSchema } from './products.js';

/** InstitutionsSearchRequest defines the request schema for `/institutions/search` */
export interface InstitutionsSearchRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The search query. Institutions with names matching the query are returned */
  query: string;
  /** Filter the Institutions based on whether they support all products listed in `products`. Provide `null` to get institutions regardless of supported products. Note that when `auth` is specified as a product, if you are enabled for Instant Match or Automated Micro-deposits, institutions that support those products will be returned even if `auth` is not present in their product array. */
  products: Products[];
  /** Specify an array of Plaid-supported country codes this institution supports, using the ISO-3166-1 alpha-2 country code standard. */
  countryCodes: CountryCode[];
  /** An optional object to filter `/institutions/search` results. */
  options?: InstitutionsSearchRequestOptions;
  additionalProperties?: Record<string, unknown>;
}

export const institutionsSearchRequestSchema: Schema<InstitutionsSearchRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        secret: ['secret', optional(string())],
        query: ['query', string()],
        products: ['products', array(productsSchema)],
        countryCodes: ['country_codes', array(countryCodeSchema)],
        options: ['options', optional(institutionsSearchRequestOptionsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
