/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { CountryCodeEnum, countryCodeEnumSchema } from './countryCodeEnum.js';
import {
  InstitutionsGetByIdRequestOptions,
  institutionsGetByIdRequestOptionsSchema,
} from './institutionsGetByIdRequestOptions.js';

/** InstitutionsGetByIdRequest defines the request schema for `/institutions/get_by_id` */
export interface InstitutionsGetByIdRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The ID of the institution to get details about */
  institutionId: string;
  /** Specify an array of Plaid-supported country codes this institution supports, using the ISO-3166-1 alpha-2 country code standard. */
  countryCodes: CountryCodeEnum[];
  /** Specifies optional parameters for `/institutions/get_by_id`. If provided, must not be `null`. */
  options?: InstitutionsGetByIdRequestOptions;
}

export const institutionsGetByIdRequestSchema: Schema<InstitutionsGetByIdRequest> = lazy(
  () =>
    object({
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      institutionId: ['institution_id', string()],
      countryCodes: ['country_codes', array(countryCodeEnumSchema)],
      options: ['options', optional(institutionsGetByIdRequestOptionsSchema)],
    })
);
