/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Additional options that will be used to filter institutions by various Payment Initiation configurations. */
export interface InstitutionsSearchPaymentInitiationOptions {
  /** A unique ID identifying the payment */
  paymentId?: string;
}

export const institutionsSearchPaymentInitiationOptionsSchema: Schema<InstitutionsSearchPaymentInitiationOptions> = object(
  { paymentId: ['payment_id', optional(string())] }
);
