/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountSubtype, accountSubtypeSchema } from './accountSubtype.js';

export interface InstitutionsSearchAccountFilter {
  loan?: AccountSubtype[];
  depository?: AccountSubtype[];
  credit?: AccountSubtype[];
  investment?: AccountSubtype[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionsSearchAccountFilterSchema: Schema<InstitutionsSearchAccountFilter> = typedExpandoObject(
  {
    loan: ['loan', optional(array(accountSubtypeSchema))],
    depository: ['depository', optional(array(accountSubtypeSchema))],
    credit: ['credit', optional(array(accountSubtypeSchema))],
    investment: ['investment', optional(array(accountSubtypeSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
