/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Institution, institutionSchema } from './institution.js';

/** InstitutionsGetByIdResponse defines the response schema for `/institutions/get_by_id` */
export interface InstitutionsGetByIdResponse {
  /** Details relating to a specific financial institution */
  institution: Institution;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const institutionsGetByIdResponseSchema: Schema<InstitutionsGetByIdResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        institution: ['institution', institutionSchema],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
