/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { SubtypeEnum, subtypeEnumSchema } from './subtypeEnum.js';
import { Type4Enum, type4EnumSchema } from './type4Enum.js';

/** A transaction within an investment account. */
export interface InvestmentTransaction {
  /** The ID of the Investment transaction, unique across all Plaid transactions. Like all Plaid identifiers, the `investment_transaction_id` is case sensitive. */
  investmentTransactionId: string;
  /** A legacy field formerly used internally by Plaid to identify certain canceled transactions. */
  cancelTransactionId?: string | null;
  /** The `account_id` of the account against which this transaction posted. */
  accountId: string;
  /** The `security_id` to which this transaction is related. */
  securityId: string | null;
  /** The [ISO 8601](https://wikipedia.org/wiki/ISO_8601) posting date for the transaction, or transacted date for pending transactions. */
  date: string;
  /** The institution’s description of the transaction. */
  name: string;
  /** The number of units of the security involved in this transaction. */
  quantity: number;
  /** The complete value of the transaction. Positive values when cash is debited, e.g. purchases of stock; negative values when cash is credited, e.g. sales of stock. Treatment remains the same for cash-only movements unassociated with securities. */
  amount: number;
  /** The price of the security at which this transaction occurred. */
  price: number;
  /** The combined value of all fees applied to this transaction */
  fees: number | null;
  /**
   * Value is one of the following:
   * `buy`: Buying an investment
   * `sell`: Selling an investment
   * `cancel`: A cancellation of a pending transaction
   * `cash`: Activity that modifies a cash position
   * `fee`: A fee on the account
   * `transfer`: Activity which modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transfer
   * For descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).
   */
  type: Type4Enum;
  /** For descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema). */
  subtype: SubtypeEnum;
  /** The ISO-4217 currency code of the transaction. Always `null` if `unofficial_currency_code` is non-`null`. */
  isoCurrencyCode: string | null;
  /**
   * The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
   * See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
   */
  unofficialCurrencyCode: string | null;
}

export const investmentTransactionSchema: Schema<InvestmentTransaction> = object(
  {
    investmentTransactionId: ['investment_transaction_id', string()],
    cancelTransactionId: [
      'cancel_transaction_id',
      optional(nullable(string())),
    ],
    accountId: ['account_id', string()],
    securityId: ['security_id', nullable(string())],
    date: ['date', string()],
    name: ['name', string()],
    quantity: ['quantity', number()],
    amount: ['amount', number()],
    price: ['price', number()],
    fees: ['fees', nullable(number())],
    type: ['type', type4EnumSchema],
    subtype: ['subtype', subtypeEnumSchema],
    isoCurrencyCode: ['iso_currency_code', nullable(string())],
    unofficialCurrencyCode: ['unofficial_currency_code', nullable(string())],
  }
);
