/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema } from '../schema.js';
import {
  AccountSubtypeEnum,
  accountSubtypeEnumSchema,
} from './accountSubtypeEnum.js';

/** A filter to apply to `investment`-type accounts */
export interface InvestmentFilter {
  /** An array of account subtypes to display in Link. If not specified, all account subtypes will be shown. For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#accounts-schema). */
  accountSubtypes: AccountSubtypeEnum[];
}

export const investmentFilterSchema: Schema<InvestmentFilter> = object({
  accountSubtypes: ['account_subtypes', array(accountSubtypeEnumSchema)],
});
