/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  InvestmentHoldingsGetRequestOptions,
  investmentHoldingsGetRequestOptionsSchema,
} from './investmentHoldingsGetRequestOptions.js';

/** InvestmentsHoldingsGetRequest defines the request schema for `/investments/holdings/get` */
export interface InvestmentsHoldingsGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** An optional object to filter `/investments/holdings/get` results. If provided, must not be `null`. */
  options?: InvestmentHoldingsGetRequestOptions;
}

export const investmentsHoldingsGetRequestSchema: Schema<InvestmentsHoldingsGetRequest> = lazy(
  () =>
    object({
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      accessToken: ['access_token', string()],
      options: ['options', optional(investmentHoldingsGetRequestOptionsSchema)],
    })
);
