/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

/** Information about the last successful and failed investments update for the Item. */
export interface ItemStatusInvestments {
  /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last successful investments update for the Item. The status will update each time Plaid successfully connects with the institution, regardless of whether any new data is available in the update. */
  lastSuccessfulUpdate?: string | null;
  /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last failed investments update for the Item. The status will update each time Plaid fails an attempt to connect with the institution, regardless of whether any new data is available in the update. */
  lastFailedUpdate?: string | null;
}

export const itemStatusInvestmentsSchema: Schema<ItemStatusInvestments> = object(
  {
    lastSuccessfulUpdate: [
      'last_successful_update',
      optional(nullable(string())),
    ],
    lastFailedUpdate: ['last_failed_update', optional(nullable(string()))],
  }
);
