/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** ItemRemoveResponse defines the response schema for `/item/remove` */
export interface ItemRemoveResponse {
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemRemoveResponseSchema: Schema<ItemRemoveResponse> = typedExpandoObject(
  { requestId: ['request_id', string()] },
  'additionalProperties',
  optional(unknown())
);
