/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Error, errorSchema } from './error.js';
import { ProductsEnum, productsEnumSchema } from './productsEnum.js';
import { UpdateTypeEnum, updateTypeEnumSchema } from './updateTypeEnum.js';

/** Metadata about the Item. */
export interface Item {
  /** The Plaid Item ID. The `item_id` is always unique; linking the same account at the same institution twice will result in two Items with different `item_id` values. Like all Plaid identifiers, the `item_id` is case-sensitive. */
  itemId: string;
  /** The Plaid Institution ID associated with the Item. Field is `null` for Items created via Same Day Micro-deposits. */
  institutionId?: string | null;
  /** The URL registered to receive webhooks for the Item. */
  webhook: string | null;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error: Error;
  /** A list of products available for the Item that have not yet been accessed. */
  availableProducts: ProductsEnum[];
  /** A list of products that have been billed for the Item. Note - `billed_products` is populated in all environments but only requests in Production are billed. */
  billedProducts: ProductsEnum[];
  /**
   * The RFC 3339 timestamp after which the consent provided by the end user will expire. Upon consent expiration, the item will enter the `ITEM_LOGIN_REQUIRED` error state. To circumvent the `ITEM_LOGIN_REQUIRED` error and maintain continuous consent, the end user can reauthenticate via Link’s update mode in advance of the consent expiration time.
   * Note - This is only relevant for certain OAuth-based institutions. For all other institutions, this field will be null.
   */
  consentExpirationTime: string | null;
  /**
   * Indicates whether an Item requires user interaction to be updated, which can be the case for Items with some forms of two-factor authentication.
   * `background` - Item can be updated in the background
   * `user_present_required` - Item requires user interaction to be updated
   */
  updateType: UpdateTypeEnum;
}

export const itemSchema: Schema<Item> = lazy(() =>
  object({
    itemId: ['item_id', string()],
    institutionId: ['institution_id', optional(nullable(string()))],
    webhook: ['webhook', nullable(string())],
    error: ['error', errorSchema],
    availableProducts: ['available_products', array(productsEnumSchema)],
    billedProducts: ['billed_products', array(productsEnumSchema)],
    consentExpirationTime: ['consent_expiration_time', nullable(string())],
    updateType: ['update_type', updateTypeEnumSchema],
  })
);
