/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** ItemPublicTokenExchangeResponse defines the response schema for `/item/public_token/exchange` */
export interface ItemPublicTokenExchangeResponse {
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** The `item_id` value of the Item associated with the returned `access_token` */
  itemId: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const itemPublicTokenExchangeResponseSchema: Schema<ItemPublicTokenExchangeResponse> = object(
  {
    accessToken: ['access_token', string()],
    itemId: ['item_id', string()],
    requestId: ['request_id', string()],
  }
);
