/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** ItemWebhookUpdateRequest defines the request schema for `/item/webhook/update` */
export interface ItemWebhookUpdateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** The new webhook URL to associate with the Item. */
  webhook: string;
}

export const itemWebhookUpdateRequestSchema: Schema<ItemWebhookUpdateRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    accessToken: ['access_token', string()],
    webhook: ['webhook', string()],
  }
);
