/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An optional object to configure `/item/import` request. */
export interface ItemImportRequestOptions {
  /** Specifies a webhook URL to associate with an Item. Plaid fires a webhook if credentials fail. */
  webhook?: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemImportRequestOptionsSchema: Schema<ItemImportRequestOptions> = typedExpandoObject(
  { webhook: ['webhook', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
