/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Object of user ID and auth token pair, permitting Plaid to aggregate a user’s accounts */
export interface ItemImportRequestUserAuth {
  /** Opaque user identifier */
  userId: string;
  /** Authorization token Plaid will use to aggregate this user’s accounts */
  authToken: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemImportRequestUserAuthSchema: Schema<ItemImportRequestUserAuth> = typedExpandoObject(
  { userId: ['user_id', string()], authToken: ['auth_token', string()] },
  'additionalProperties',
  optional(unknown())
);
