/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ItemStatusInvestments,
  itemStatusInvestmentsSchema,
} from './itemStatusInvestments.js';
import {
  ItemStatusLastWebhook,
  itemStatusLastWebhookSchema,
} from './itemStatusLastWebhook.js';
import {
  ItemStatusTransactions,
  itemStatusTransactionsSchema,
} from './itemStatusTransactions.js';

export interface ItemStatusNullable {
  /** Information about the last successful and failed investments update for the Item. */
  investments?: ItemStatusInvestments;
  /** Information about the last successful and failed transactions update for the Item. */
  transactions?: ItemStatusTransactions;
  /** Information about the last webhook fired for the Item. */
  lastWebhook?: ItemStatusLastWebhook;
  additionalProperties?: Record<string, unknown>;
}

export const itemStatusNullableSchema: Schema<ItemStatusNullable> = lazy(() =>
  typedExpandoObject(
    {
      investments: ['investments', optional(itemStatusInvestmentsSchema)],
      transactions: ['transactions', optional(itemStatusTransactionsSchema)],
      lastWebhook: ['last_webhook', optional(itemStatusLastWebhookSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
