/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** User authentication parameters, for clients making a request without an `access_token`. This is only allowed for select clients and will not be supported in the future. Most clients should call /item/import to obtain an access token before making a request. */
export interface ItemApplicationListUserAuth {
  /** Account username. */
  userId?: string | null;
  /** Account username hashed by FI. */
  fiUsernameHash?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const itemApplicationListUserAuthSchema: Schema<ItemApplicationListUserAuth> = typedExpandoObject(
  {
    userId: ['user_id', optional(nullable(string()))],
    fiUsernameHash: ['fi_username_hash', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
