/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An optional object to configure `/item/import` request. */
export interface ItemImportRequestOptions {
  /** Specifies a webhook URL to associate with an Item. Plaid fires a webhook if credentials fail. */
  webhook?: string;
}

export const itemImportRequestOptionsSchema: Schema<ItemImportRequestOptions> = object(
  { webhook: ['webhook', optional(string())] }
);
