/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** ItemPublicTokenExchangeRequest defines the request schema for `/item/public_token/exchange` */
export interface ItemPublicTokenExchangeRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Your `public_token`, obtained from the Link `onSuccess` callback or `/sandbox/item/public_token/create`. */
  publicToken: string;
}

export const itemPublicTokenExchangeRequestSchema: Schema<ItemPublicTokenExchangeRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    publicToken: ['public_token', string()],
  }
);
