/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Information about the last webhook fired for the Item. */
export interface ItemStatusLastWebhook {
  /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp of when the webhook was fired. */
  sentAt?: string | null;
  /** The last webhook code sent. */
  codeSent?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const itemStatusLastWebhookSchema: Schema<ItemStatusLastWebhook> = typedExpandoObject(
  {
    sentAt: ['sent_at', optional(nullable(string()))],
    codeSent: ['code_sent', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
