/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ItemImportRequestOptions,
  itemImportRequestOptionsSchema,
} from './itemImportRequestOptions.js';
import {
  ItemImportRequestUserAuth,
  itemImportRequestUserAuthSchema,
} from './itemImportRequestUserAuth.js';
import { Products, productsSchema } from './products.js';

/** ItemImportRequest defines the request schema for `/item/import` */
export interface ItemImportRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Array of product strings */
  products: Products[];
  /** Object of user ID and auth token pair, permitting Plaid to aggregate a user’s accounts */
  userAuth: ItemImportRequestUserAuth;
  /** An optional object to configure `/item/import` request. */
  options?: ItemImportRequestOptions;
  additionalProperties?: Record<string, unknown>;
}

export const itemImportRequestSchema: Schema<ItemImportRequest> = lazy(() =>
  typedExpandoObject(
    {
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      products: ['products', array(productsSchema)],
      userAuth: ['user_auth', itemImportRequestUserAuthSchema],
      options: ['options', optional(itemImportRequestOptionsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
