/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CreditCardLiability,
  creditCardLiabilitySchema,
} from './creditCardLiability.js';
import {
  MortgageLiability,
  mortgageLiabilitySchema,
} from './mortgageLiability.js';
import { StudentLoan, studentLoanSchema } from './studentLoan.js';

/** An object containing liability accounts */
export interface LiabilitiesObject {
  /** The credit accounts returned. */
  credit: CreditCardLiability[] | null;
  /** The mortgage accounts returned. */
  mortgage: MortgageLiability[] | null;
  /** The student loan accounts returned. */
  student: StudentLoan[] | null;
  additionalProperties?: Record<string, unknown>;
}

export const liabilitiesObjectSchema: Schema<LiabilitiesObject> = lazy(() =>
  typedExpandoObject(
    {
      credit: ['credit', nullable(array(creditCardLiabilitySchema))],
      mortgage: ['mortgage', nullable(array(mortgageLiabilitySchema))],
      student: ['student', nullable(array(studentLoanSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
