/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An optional object to filter `/liabilities/get` results. If provided, `options` cannot be null. */
export interface LiabilitiesGetRequestOptions {
  /**
   * A list of accounts to retrieve for the Item.
   * An error will be returned if a provided `account_id` is not associated with the Item
   */
  accountIds?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const liabilitiesGetRequestOptionsSchema: Schema<LiabilitiesGetRequestOptions> = typedExpandoObject(
  { accountIds: ['account_ids', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
