/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';
import { PslfStatus, pslfStatusSchema } from './pslfStatus.js';
import {
  StudentLoanRepaymentModel,
  studentLoanRepaymentModelSchema,
} from './studentLoanRepaymentModel.js';
import {
  StudentLoanStatus,
  studentLoanStatusSchema,
} from './studentLoanStatus.js';

/** Used to configure Sandbox test data for the Liabilities product */
export interface LiabilityOverride {
  /** The type of the liability object, either `credit` or `student`. Mortgages are not currently supported in the custom Sandbox. */
  type: string;
  /** The purchase APR percentage value. For simplicity, this is the only interest rate used to calculate interest charges. Can only be set if `type` is `credit`. */
  purchaseApr: number;
  /** The cash APR percentage value. Can only be set if `type` is `credit`. */
  cashApr: number;
  /** The balance transfer APR percentage value. Can only be set if `type` is `credit`. Can only be set if `type` is `credit`. */
  balanceTransferApr: number;
  /** The special APR percentage value. Can only be set if `type` is `credit`. */
  specialApr: number;
  /** Override the `last_payment_amount` field. Can only be set if `type` is `credit`. */
  lastPaymentAmount: number;
  /** Override the `minimum_payment_amount` field. Can only be set if `type` is `credit` or `student`. */
  minimumPaymentAmount: number;
  /** Override the `is_overdue` field */
  isOverdue: boolean;
  /** The date on which the loan was initially lent, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format. Can only be set if `type` is `student`. */
  originationDate: string;
  /** The original loan principal. Can only be set if `type` is `student`. */
  principal: number;
  /** The interest rate on the loan as a percentage. Can only be set if `type` is `student`. */
  nominalApr: number;
  /** If set, interest capitalization begins at the given number of months after loan origination. By default interest is never capitalized. Can only be set if `type` is `student`. */
  interestCapitalizationGracePeriodMonths: number;
  /** Student loan repayment information used to configure Sandbox test data for the Liabilities product */
  repaymentModel: StudentLoanRepaymentModel;
  /** Override the `expected_payoff_date` field. Can only be set if `type` is `student`. */
  expectedPayoffDate: string;
  /** Override the `guarantor` field. Can only be set if `type` is `student`. */
  guarantor: string;
  /** Override the `is_federal` field. Can only be set if `type` is `student`. */
  isFederal: boolean;
  /** Override the `loan_name` field. Can only be set if `type` is `student`. */
  loanName: string;
  /** An object representing the status of the student loan */
  loanStatus: StudentLoanStatus;
  /** Override the `payment_reference_number` field. Can only be set if `type` is `student`. */
  paymentReferenceNumber: string;
  /** Information about the student's eligibility in the Public Service Loan Forgiveness program. This is only returned if the institution is Fedloan (`ins_116527`). */
  pslfStatus: PslfStatus;
  /** Override the `repayment_plan.description` field. Can only be set if `type` is `student`. */
  repaymentPlanDescription: string;
  /** Override the `repayment_plan.type` field. Can only be set if `type` is `student`. Possible values are: `"extended graduated"`, `"extended standard"`, `"graduated"`, `"income-contingent repayment"`, `"income-based repayment"`, `"interest only"`, `"other"`, `"pay as you earn"`, `"revised pay as you earn"`, or `"standard"`. */
  repaymentPlanType: string;
  /** Override the `sequence_number` field. Can only be set if `type` is `student`. */
  sequenceNumber: string;
  /** A physical mailing address. */
  servicerAddress: Address;
  additionalProperties?: Record<string, unknown>;
}

export const liabilityOverrideSchema: Schema<LiabilityOverride> = lazy(() =>
  typedExpandoObject(
    {
      type: ['type', string()],
      purchaseApr: ['purchase_apr', number()],
      cashApr: ['cash_apr', number()],
      balanceTransferApr: ['balance_transfer_apr', number()],
      specialApr: ['special_apr', number()],
      lastPaymentAmount: ['last_payment_amount', number()],
      minimumPaymentAmount: ['minimum_payment_amount', number()],
      isOverdue: ['is_overdue', boolean()],
      originationDate: ['origination_date', string()],
      principal: ['principal', number()],
      nominalApr: ['nominal_apr', number()],
      interestCapitalizationGracePeriodMonths: [
        'interest_capitalization_grace_period_months',
        number(),
      ],
      repaymentModel: ['repayment_model', studentLoanRepaymentModelSchema],
      expectedPayoffDate: ['expected_payoff_date', string()],
      guarantor: ['guarantor', string()],
      isFederal: ['is_federal', boolean()],
      loanName: ['loan_name', string()],
      loanStatus: ['loan_status', studentLoanStatusSchema],
      paymentReferenceNumber: ['payment_reference_number', string()],
      pslfStatus: ['pslf_status', pslfStatusSchema],
      repaymentPlanDescription: ['repayment_plan_description', string()],
      repaymentPlanType: ['repayment_plan_type', string()],
      sequenceNumber: ['sequence_number', string()],
      servicerAddress: ['servicer_address', addressSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
