/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CountryCode, countryCodeSchema } from './countryCode.js';
import {
  LinkTokenAccountFilters,
  linkTokenAccountFiltersSchema,
} from './linkTokenAccountFilters.js';
import {
  LinkTokenCreateRequestAuth,
  linkTokenCreateRequestAuthSchema,
} from './linkTokenCreateRequestAuth.js';
import {
  LinkTokenCreateRequestDepositSwitch,
  linkTokenCreateRequestDepositSwitchSchema,
} from './linkTokenCreateRequestDepositSwitch.js';
import {
  LinkTokenCreateRequestIncomeVerification,
  linkTokenCreateRequestIncomeVerificationSchema,
} from './linkTokenCreateRequestIncomeVerification.js';
import {
  LinkTokenCreateRequestPaymentInitiation,
  linkTokenCreateRequestPaymentInitiationSchema,
} from './linkTokenCreateRequestPaymentInitiation.js';
import {
  LinkTokenCreateRequestUpdate,
  linkTokenCreateRequestUpdateSchema,
} from './linkTokenCreateRequestUpdate.js';
import {
  LinkTokenCreateRequestUser,
  linkTokenCreateRequestUserSchema,
} from './linkTokenCreateRequestUser.js';
import {
  LinkTokenEuConfig,
  linkTokenEuConfigSchema,
} from './linkTokenEuConfig.js';
import { Products, productsSchema } from './products.js';

/** LinkTokenCreateRequest defines the request schema for `/link/token/create` */
export interface LinkTokenCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The name of your application, as it should be displayed in Link. Maximum length of 30 characters. */
  clientName: string;
  /**
   * The language that Link should be displayed in.
   * Supported languages are:
   * - English (`'en'`)
   * - French (`'fr'`)
   * - Spanish (`'es'`)
   * - Dutch (`'nl'`)
   * When using a Link customization, the language configured here must match the setting in the customization, or the customization will not be applied.
   */
  language: string;
  /**
   * Specify an array of Plaid-supported country codes using the ISO-3166-1 alpha-2 country code standard. Institutions from all listed countries will be shown.  Supported country codes are: `US`, `CA`, `ES`, `FR`, `GB`, `IE`, `NL`.
   * If Link is launched with multiple country codes, only products that you are enabled for in all countries will be used by Link. Note that while all countries are enabled by default in Sandbox and Development, in Production only US and Canada are enabled by default. To gain access to European institutions in the Production environment, [file a product access Support ticket](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/request-product-access) via the Plaid dashboard. If you initialize with a European country code, your users will see the European consent panel during the Link flow.
   * If using a Link customization, make sure the country codes in the customization match those specified in `country_codes`. If both `country_codes` and a Link customization are used, the value in `country_codes` may override the value in the customization.
   * If using the Auth features Instant Match, Same-day Micro-deposits, or Automated Micro-deposits, `country_codes` must be set to `['US']`.
   */
  countryCodes: CountryCode[];
  /** An object specifying information about the end user who will be linking their account. */
  user: LinkTokenCreateRequestUser;
  /**
   * List of Plaid product(s) you wish to use. If launching Link in update mode, should be omitted; required otherwise. Valid products are:
   * `transactions`, `auth`, `identity`, `assets`, `investments`, `liabilities`, `payment_initiation`, `deposit_switch`, `income_verification`, `transfer`
   * `balance` is *not* a valid value, the Balance product does not require explicit initalization and will automatically be initialized when any other product is initialized.
   * Only institutions that support *all* requested products will be shown in Link; to maximize the number of institutions listed, it is recommended to initialize Link with the minimal product set required for your use case. Additional products can be added after Link initialization by calling the relevant endpoints. For details and exceptions, see [Choosing when to initialize products](https://plaid.com/docs/link/best-practices/#choosing-when-to-initialize-products).
   * Note that, unless you have opted to disable Instant Match support, institutions that support Instant Match will also be shown in Link if `auth` is specified as a product, even though these institutions do not contain `auth` in their product array.
   * In Production, you will be billed for each product that you specify when initializing Link. Note that a product cannot be removed from an Item once the Item has been initialized with that product. To stop billing on an Item for subscription-based products, such as Liabilities, Investments, and Transactions, remove the Item via `/item/remove`.
   */
  products?: Products[];
  /** The destination URL to which any webhooks should be sent. */
  webhook?: string;
  /** The `access_token` associated with the Item to update, used when updating or modifying an existing `access_token`. Used when launching Link in update mode, when completing the Same-day (manual) Micro-deposit flow, or (optionally) when initializing Link as part of the Payment Initiation (UK and Europe) flow. */
  accessToken?: string;
  /** The name of the Link customization from the Plaid Dashboard to be applied to Link. If not specified, the `default` customization will be used. When using a Link customization, the language in the customization must match the language selected via the `language` parameter, and the countries in the customization should match the country codes selected via `country_codes`. */
  linkCustomizationName?: string;
  /** A URI indicating the destination where a user should be forwarded after completing the Link flow; used to support OAuth authentication flows when launching Link in the browser or via a webview. The `redirect_uri` should not contain any query parameters. When used in Production or Development, must be an https URI. To specify any subdomain, use `*` as a wildcard character, e.g. `https://*.example.com/oauth.html`. If `android_package_name` is specified, this field should be left blank.  Note that any redirect URI must also be added to the Allowed redirect URIs list in the [developer dashboard](https://dashboard.plaid.com/team/api). */
  redirectUri?: string;
  /** The name of your app's Android package. Required if using the `link_token` to initialize Link on Android. When creating a `link_token` for initializing Link on other platforms, this field must be left blank. Any package name specified here must also be added to the Allowed Android package names setting on the [developer dashboard](https://dashboard.plaid.com/team/api). */
  androidPackageName?: string;
  /**
   * By default, Link will provide limited account filtering: it will only display Institutions that are compatible with all products supplied in the `products` parameter of `/link/token/create`, and, if `auth` is specified in the `products` array, will also filter out accounts other than `checking` and `savings` accounts on the Account Select pane. You can further limit the accounts shown in Link by using `account_filters` to specify the account subtypes to be shown in Link. Only the specified subtypes will be shown. This filtering applies to both the Account Select view (if enabled) and the Institution Select view. Institutions that do not support the selected subtypes will be omitted from Link. To indicate that all subtypes should be shown, use the value `"all"`. If the `account_filters` filter is used, any account type for which a filter is not specified will be entirely omitted from Link. For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#accounts-schema).
   * For institutions using OAuth, the filter will not affect the list of accounts shown by the bank in the OAuth window.
   */
  accountFilters?: LinkTokenAccountFilters;
  /** Configuration parameters for EU flows */
  euConfig?: LinkTokenEuConfig;
  /** Used for certain Europe-only configurations, as well as certain legacy use cases in other regions. */
  institutionId?: string;
  /** Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if `payment_initiation` is included in the `products` array. */
  paymentInitiation?: LinkTokenCreateRequestPaymentInitiation;
  /** Specifies options for initializing Link for use with the Deposit Switch (beta) product. This field is required if `deposit_switch` is included in the `products` array. */
  depositSwitch?: LinkTokenCreateRequestDepositSwitch;
  /** Specifies options for initializing Link for use with the Income (beta) product. This field is required if `income_verification` is included in the `products` array. */
  incomeVerification?: LinkTokenCreateRequestIncomeVerification;
  /** Specifies options for initializing Link for use with the Auth product. This field is currently only required if using the Flexible Auth product (currently in closed beta). */
  auth?: LinkTokenCreateRequestAuth;
  /** Specifies options for initializing Link for [update mode](https://plaid.com/docs/link/update-mode). */
  update?: LinkTokenCreateRequestUpdate;
  additionalProperties?: Record<string, unknown>;
}

export const linkTokenCreateRequestSchema: Schema<LinkTokenCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        secret: ['secret', optional(string())],
        clientName: ['client_name', string()],
        language: ['language', string()],
        countryCodes: ['country_codes', array(countryCodeSchema)],
        user: ['user', linkTokenCreateRequestUserSchema],
        products: ['products', optional(array(productsSchema))],
        webhook: ['webhook', optional(string())],
        accessToken: ['access_token', optional(string())],
        linkCustomizationName: ['link_customization_name', optional(string())],
        redirectUri: ['redirect_uri', optional(string())],
        androidPackageName: ['android_package_name', optional(string())],
        accountFilters: [
          'account_filters',
          optional(linkTokenAccountFiltersSchema),
        ],
        euConfig: ['eu_config', optional(linkTokenEuConfigSchema)],
        institutionId: ['institution_id', optional(string())],
        paymentInitiation: [
          'payment_initiation',
          optional(linkTokenCreateRequestPaymentInitiationSchema),
        ],
        depositSwitch: [
          'deposit_switch',
          optional(linkTokenCreateRequestDepositSwitchSchema),
        ],
        incomeVerification: [
          'income_verification',
          optional(linkTokenCreateRequestIncomeVerificationSchema),
        ],
        auth: ['auth', optional(linkTokenCreateRequestAuthSchema)],
        update: ['update', optional(linkTokenCreateRequestUpdateSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
