/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** LinkTokenGetRequest defines the request schema for `/link/token/get` */
export interface LinkTokenGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** A `link_token` from a previous invocation of `/link/token/create` */
  linkToken: string;
}

export const linkTokenGetRequestSchema: Schema<LinkTokenGetRequest> = object({
  clientId: ['client_id', optional(string())],
  secret: ['secret', optional(string())],
  linkToken: ['link_token', string()],
});
