/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Configuration parameters for EU flows */
export interface LinkTokenEuConfig {
  /** If `true`, open Link without an initial UI. Defaults to `false`. */
  headless?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const linkTokenEuConfigSchema: Schema<LinkTokenEuConfig> = typedExpandoObject(
  { headless: ['headless', optional(boolean())] },
  'additionalProperties',
  optional(unknown())
);
