/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if `payment_initiation` is included in the `products` array. */
export interface LinkTokenCreateRequestPaymentInitiation {
  /** The `payment_id` provided by the `/payment_initiation/payment/create` endpoint. */
  paymentId: string;
}

export const linkTokenCreateRequestPaymentInitiationSchema: Schema<LinkTokenCreateRequestPaymentInitiation> = object(
  { paymentId: ['payment_id', string()] }
);
