/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountFiltersResponse,
  accountFiltersResponseSchema,
} from './accountFiltersResponse.js';
import { CountryCode, countryCodeSchema } from './countryCode.js';
import { Products, productsSchema } from './products.js';

/** An object specifying the arguments originally provided to the `/link/token/create` call. */
export interface LinkTokenGetMetadataResponse {
  /** The `products` specified in the `/link/token/create` call. */
  initialProducts: Products[];
  /** The `webhook` specified in the `/link/token/create` call. */
  webhook: string | null;
  /** The `country_codes` specified in the `/link/token/create` call. */
  countryCodes: CountryCode[];
  /** The `language` specified in the `/link/token/create` call. */
  language: string | null;
  /** The `account_filters` specified in the original call to `/link/token/create`. */
  accountFilters?: AccountFiltersResponse;
  /** The `redirect_uri` specified in the `/link/token/create` call. */
  redirectUri: string | null;
  /** The `client_name` specified in the `/link/token/create` call. */
  clientName: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const linkTokenGetMetadataResponseSchema: Schema<LinkTokenGetMetadataResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        initialProducts: ['initial_products', array(productsSchema)],
        webhook: ['webhook', nullable(string())],
        countryCodes: ['country_codes', array(countryCodeSchema)],
        language: ['language', nullable(string())],
        accountFilters: [
          'account_filters',
          optional(accountFiltersResponseSchema),
        ],
        redirectUri: ['redirect_uri', nullable(string())],
        clientName: ['client_name', nullable(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
