/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** LinkTokenCreateResponse defines the response schema for `/link/token/create` */
export interface LinkTokenCreateResponse {
  /** A `link_token`, which can be supplied to Link in order to initialize it and receive a `public_token`, which can be exchanged for an `access_token`. */
  linkToken: string;
  /** The expiration date for the `link_token`, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. A `link_token` created to generate a `public_token` that will be exchanged for a new `access_token` expires after 4 hours. A `link_token` created for an existing Item (such as when updating an existing `access_token` by launching Link in update mode) expires after 30 minutes. */
  expiration: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const linkTokenCreateResponseSchema: Schema<LinkTokenCreateResponse> = typedExpandoObject(
  {
    linkToken: ['link_token', string()],
    expiration: ['expiration', string()],
    requestId: ['request_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
