/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if `payment_initiation` is included in the `products` array. */
export interface LinkTokenCreateRequestPaymentInitiation {
  /** The `payment_id` provided by the `/payment_initiation/payment/create` endpoint. */
  paymentId: string;
  additionalProperties?: Record<string, unknown>;
}

export const linkTokenCreateRequestPaymentInitiationSchema: Schema<LinkTokenCreateRequestPaymentInitiation> = typedExpandoObject(
  { paymentId: ['payment_id', string()] },
  'additionalProperties',
  optional(unknown())
);
