/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

/** Specifies options for initializing Link for [update mode](https://plaid.com/docs/link/update-mode). */
export interface LinkTokenCreateRequestUpdate {
  /** If `true`, enables [update mode with Account Select](https://plaid.com/docs/link/update-mode/#using-update-mode-to-request-new-accounts). */
  accountSelectionEnabled?: boolean;
}

export const linkTokenCreateRequestUpdateSchema: Schema<LinkTokenCreateRequestUpdate> = object(
  {
    accountSelectionEnabled: ['account_selection_enabled', optional(boolean())],
  }
);
