/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, Schema, string } from '../schema.js';
import {
  LinkTokenGetMetadataResponse,
  linkTokenGetMetadataResponseSchema,
} from './linkTokenGetMetadataResponse.js';

/** LinkTokenGetResponse defines the response schema for `/link/token/get` */
export interface LinkTokenGetResponse {
  /** A `link_token`, which can be supplied to Link in order to initialize it and receive a `public_token`, which can be exchanged for an `access_token`. */
  linkToken: string;
  /** The creation timestamp for the `link_token`, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. */
  createdAt: string | null;
  /** The expiration timestamp for the `link_token`, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. */
  expiration: string | null;
  /** An object specifying the arguments originally provided to the `/link/token/create` call. */
  metadata: LinkTokenGetMetadataResponse;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const linkTokenGetResponseSchema: Schema<LinkTokenGetResponse> = lazy(
  () =>
    object({
      linkToken: ['link_token', string()],
      createdAt: ['created_at', nullable(string())],
      expiration: ['expiration', nullable(string())],
      metadata: ['metadata', linkTokenGetMetadataResponseSchema],
      requestId: ['request_id', string()],
    })
);
