/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Allows specifying the metadata of the test account */
export interface Meta {
  /** The account's name */
  name: string;
  /** The account's official name */
  officialName: string;
  /** The account's limit */
  limit: number;
  additionalProperties?: Record<string, unknown>;
}

export const metaSchema: Schema<Meta> = typedExpandoObject(
  {
    name: ['name', string()],
    officialName: ['official_name', string()],
    limit: ['limit', number()],
  },
  'additionalProperties',
  optional(unknown())
);
