/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MortgageInterestRate,
  mortgageInterestRateSchema,
} from './mortgageInterestRate.js';
import {
  MortgagePropertyAddress,
  mortgagePropertyAddressSchema,
} from './mortgagePropertyAddress.js';

/** Contains details about a mortgage account. */
export interface MortgageLiability {
  /** The ID of the account that this liability belongs to. */
  accountId: string;
  /** The account number of the loan. */
  accountNumber: string;
  /** The current outstanding amount charged for late payment. */
  currentLateFee: number | null;
  /** Total amount held in escrow to pay taxes and insurance on behalf of the borrower. */
  escrowBalance: number | null;
  /** Indicates whether the borrower has private mortgage insurance in effect. */
  hasPmi: boolean | null;
  /** Indicates whether the borrower will pay a penalty for early payoff of mortgage. */
  hasPrepaymentPenalty: boolean | null;
  /** Object containing metadata about the interest rate for the mortgage. */
  interestRate: MortgageInterestRate;
  /** The amount of the last payment. */
  lastPaymentAmount: number | null;
  /** The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
  lastPaymentDate: string | null;
  /** Description of the type of loan, for example `conventional`, `fixed`, or `variable`. This field is provided directly from the loan servicer and does not have an enumerated set of possible values. */
  loanTypeDescription: string | null;
  /** Full duration of mortgage as at origination (e.g. `10 year`). */
  loanTerm: string | null;
  /** Original date on which mortgage is due in full. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
  maturityDate: string | null;
  /** The amount of the next payment. */
  nextMonthlyPayment: number | null;
  /** The due date for the next payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
  nextPaymentDueDate: string | null;
  /** The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
  originationDate: string | null;
  /** The original principal balance of the mortgage. */
  originationPrincipalAmount: number | null;
  /** Amount of loan (principal + interest) past due for payment. */
  pastDueAmount: number | null;
  /** Object containing fields describing property address. */
  propertyAddress: MortgagePropertyAddress;
  /** The year to date (YTD) interest paid. */
  ytdInterestPaid: number | null;
  /** The YTD principal paid. */
  ytdPrincipalPaid: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const mortgageLiabilitySchema: Schema<MortgageLiability> = lazy(() =>
  typedExpandoObject(
    {
      accountId: ['account_id', string()],
      accountNumber: ['account_number', string()],
      currentLateFee: ['current_late_fee', nullable(number())],
      escrowBalance: ['escrow_balance', nullable(number())],
      hasPmi: ['has_pmi', nullable(boolean())],
      hasPrepaymentPenalty: ['has_prepayment_penalty', nullable(boolean())],
      interestRate: ['interest_rate', mortgageInterestRateSchema],
      lastPaymentAmount: ['last_payment_amount', nullable(number())],
      lastPaymentDate: ['last_payment_date', nullable(string())],
      loanTypeDescription: ['loan_type_description', nullable(string())],
      loanTerm: ['loan_term', nullable(string())],
      maturityDate: ['maturity_date', nullable(string())],
      nextMonthlyPayment: ['next_monthly_payment', nullable(number())],
      nextPaymentDueDate: ['next_payment_due_date', nullable(string())],
      originationDate: ['origination_date', nullable(string())],
      originationPrincipalAmount: [
        'origination_principal_amount',
        nullable(number()),
      ],
      pastDueAmount: ['past_due_amount', nullable(number())],
      propertyAddress: ['property_address', mortgagePropertyAddressSchema],
      ytdInterestPaid: ['ytd_interest_paid', nullable(number())],
      ytdPrincipalPaid: ['ytd_principal_paid', nullable(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
