/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

/** Object containing metadata about the interest rate for the mortgage. */
export interface MortgageInterestRate {
  /** Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan. */
  percentage: number | null;
  /** The type of interest charged (fixed or variable). */
  type: string | null;
}

export const mortgageInterestRateSchema: Schema<MortgageInterestRate> = object({
  percentage: ['percentage', nullable(number())],
  type: ['type', nullable(string())],
});
