/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema.js';

/** Object containing fields describing property address. */
export interface MortgagePropertyAddress {
  /** The city name. */
  city: string | null;
  /** The ISO 3166-1 alpha-2 country code. */
  country: string | null;
  /** The five or nine digit postal code. */
  postalCode: string | null;
  /** The region or state (example "NC"). */
  region: string | null;
  /** The full street address (example "564 Main Street, Apt 15"). */
  street: string | null;
}

export const mortgagePropertyAddressSchema: Schema<MortgagePropertyAddress> = object(
  {
    city: ['city', nullable(string())],
    country: ['country', nullable(string())],
    postalCode: ['postal_code', nullable(string())],
    region: ['region', nullable(string())],
    street: ['street', nullable(string())],
  }
);
