/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';

/** Fired when Plaid detects a new account for Items created or updated with [Account Select v2](https://plaid.com/docs/link/customization/#account-select). Upon receiving this webhook, you can prompt your users to share new accounts with you through [Account Select v2 update mode](https://plaid.com/docs/link/update-mode/#using-update-mode-to-request-new-accounts). */
export interface NewAccountsAvailableWebhook {
  /** `ITEM` */
  webhookType?: string;
  /** `NEW_ACCOUNTS_AVAILABLE` */
  webhookCode?: string;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId?: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  additionalProperties?: Record<string, unknown>;
}

export const newAccountsAvailableWebhookSchema: Schema<NewAccountsAvailableWebhook> = lazy(
  () =>
    typedExpandoObject(
      {
        webhookType: ['webhook_type', optional(string())],
        webhookCode: ['webhook_code', optional(string())],
        itemId: ['item_id', optional(string())],
        error: ['error', optional(errorSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
