/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NewPaymentStatusEnum
 */
export enum NewPaymentStatusEnum {
  PAYMENTSTATUSINPUTNEEDED = 'PAYMENT_STATUS_INPUT_NEEDED',
  PAYMENTSTATUSPROCESSING = 'PAYMENT_STATUS_PROCESSING',
  PAYMENTSTATUSINITIATED = 'PAYMENT_STATUS_INITIATED',
  PAYMENTSTATUSCOMPLETED = 'PAYMENT_STATUS_COMPLETED',
  PAYMENTSTATUSINSUFFICIENTFUNDS = 'PAYMENT_STATUS_INSUFFICIENT_FUNDS',
  PAYMENTSTATUSFAILED = 'PAYMENT_STATUS_FAILED',
  PAYMENTSTATUSBLOCKED = 'PAYMENT_STATUS_BLOCKED',
  PAYMENTSTATUSUNKNOWN = 'PAYMENT_STATUS_UNKNOWN',
}

/**
 * Schema for NewPaymentStatusEnum
 */
export const newPaymentStatusEnumSchema: Schema<NewPaymentStatusEnum> = stringEnum(
  NewPaymentStatusEnum
);
