/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NumbersInternationalNullable {
  /** The Plaid account ID associated with the account numbers */
  accountId: string;
  /** The International Bank Account Number (IBAN) for the account */
  iban: string;
  /** The Bank Identifier Code (BIC) for the account */
  bic: string;
  additionalProperties?: Record<string, unknown>;
}

export const numbersInternationalNullableSchema: Schema<NumbersInternationalNullable> = typedExpandoObject(
  {
    accountId: ['account_id', string()],
    iban: ['iban', string()],
    bic: ['bic', string()],
  },
  'additionalProperties',
  optional(unknown())
);
