/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Identifying information for transferring money to or from a Canadian bank account via EFT. */
export interface NumbersEft {
  /** The Plaid account ID associated with the account numbers */
  accountId: string;
  /** The EFT account number for the account */
  account: string;
  /** The EFT institution number for the account */
  institution: string;
  /** The EFT branch number for the account */
  branch: string;
  additionalProperties?: Record<string, unknown>;
}

export const numbersEftSchema: Schema<NumbersEft> = typedExpandoObject(
  {
    accountId: ['account_id', string()],
    account: ['account', string()],
    institution: ['institution', string()],
    branch: ['branch', string()],
  },
  'additionalProperties',
  optional(unknown())
);
