/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OldPaymentStatus
 */
export enum OldPaymentStatus {
  PaymentStatusInputNeeded = 'PAYMENT_STATUS_INPUT_NEEDED',
  PaymentStatusProcessing = 'PAYMENT_STATUS_PROCESSING',
  PaymentStatusInitiated = 'PAYMENT_STATUS_INITIATED',
  PaymentStatusCompleted = 'PAYMENT_STATUS_COMPLETED',
  PaymentStatusInsufficientFunds = 'PAYMENT_STATUS_INSUFFICIENT_FUNDS',
  PaymentStatusFailed = 'PAYMENT_STATUS_FAILED',
  PaymentStatusBlocked = 'PAYMENT_STATUS_BLOCKED',
  PaymentStatusUnknown = 'PAYMENT_STATUS_UNKNOWN',
}

/**
 * Schema for OldPaymentStatus
 */
export const oldPaymentStatusSchema: Schema<OldPaymentStatus> = stringEnum(
  OldPaymentStatus,
  true
);
