/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OverrideAccountTypeEnum
 */
export enum OverrideAccountTypeEnum {
  Investment = 'investment',
  Credit = 'credit',
  Depository = 'depository',
  Loan = 'loan',
  Payroll = 'payroll',
  Other = 'other',
}

/**
 * Schema for OverrideAccountTypeEnum
 */
export const overrideAccountTypeEnumSchema: Schema<OverrideAccountTypeEnum> = stringEnum(
  OverrideAccountTypeEnum
);
