/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  AccountSubtypeEnum,
  accountSubtypeEnumSchema,
} from './accountSubtypeEnum.js';
import {
  HoldingsOverride,
  holdingsOverrideSchema,
} from './holdingsOverride.js';
import { IncomeOverride, incomeOverrideSchema } from './incomeOverride.js';
import { InflowModel, inflowModelSchema } from './inflowModel.js';
import {
  InvestmentsTransactionsOverride,
  investmentsTransactionsOverrideSchema,
} from './investmentsTransactionsOverride.js';
import {
  LiabilityOverride,
  liabilityOverrideSchema,
} from './liabilityOverride.js';
import { Meta, metaSchema } from './meta.js';
import { Numbers, numbersSchema } from './numbers.js';
import {
  OverrideAccountTypeEnum,
  overrideAccountTypeEnumSchema,
} from './overrideAccountTypeEnum.js';
import { OwnerOverride, ownerOverrideSchema } from './ownerOverride.js';
import {
  TransactionOverride,
  transactionOverrideSchema,
} from './transactionOverride.js';

/** Data to use to set values of test accounts. Some values cannot be specified in the schema and will instead will be calculated from other test data in order to achieve more consistent, realistic test data. */
export interface OverrideAccounts {
  /**
   * `investment:` Investment account
   * `credit:` Credit card
   * `depository:` Depository account
   * `loan:` Loan account
   * `payroll:` Payroll acccount
   * `other:` Non-specified account type
   * See the [Account type schema](https://plaid.com/docs/api/accounts#account-type-schema) for a full listing of account types and corresponding subtypes.
   */
  type: OverrideAccountTypeEnum;
  /** See the [Account type schema](https://plaid.com/docs/api/accounts/#account-type-schema) for a full listing of account types and corresponding subtypes. */
  subtype: AccountSubtypeEnum;
  /** If provided, the account will start with this amount as the current balance. */
  startingBalance: number;
  /** If provided, the account will always have this amount as its  available balance, regardless of current balance or changes in transactions over time. */
  forceAvailableBalance: number;
  /** ISO-4217 currency code. If provided, the account will be denominated in the given currency. Transactions will also be in this currency by default. */
  currency: string;
  /** Allows specifying the metadata of the test account */
  meta: Meta;
  /** Account and bank identifier number data used to configure the test account. All values are optional. */
  numbers: Numbers;
  /** Specify the list of transactions on the account. */
  transactions: TransactionOverride[];
  /** Specify the holdings on the account. */
  holdings?: HoldingsOverride;
  /** Specify the list of investments transactions on the account. */
  investmentTransactions?: InvestmentsTransactionsOverride;
  /** Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox information. */
  identity: OwnerOverride;
  /** Used to configure Sandbox test data for the Liabilities product */
  liability: LiabilityOverride;
  /** The `inflow_model` allows you to model a test account that receives regular income or make regular payments on a loan. Any transactions generated by the `inflow_model` will appear in addition to randomly generated test data or transactions specified by `override_accounts`. */
  inflowModel: InflowModel;
  /** Specify payroll data on the account. */
  income?: IncomeOverride;
}

export const overrideAccountsSchema: Schema<OverrideAccounts> = lazy(() =>
  object({
    type: ['type', overrideAccountTypeEnumSchema],
    subtype: ['subtype', accountSubtypeEnumSchema],
    startingBalance: ['starting_balance', number()],
    forceAvailableBalance: ['force_available_balance', number()],
    currency: ['currency', string()],
    meta: ['meta', metaSchema],
    numbers: ['numbers', numbersSchema],
    transactions: ['transactions', array(transactionOverrideSchema)],
    holdings: ['holdings', optional(holdingsOverrideSchema)],
    investmentTransactions: [
      'investment_transactions',
      optional(investmentsTransactionsOverrideSchema),
    ],
    identity: ['identity', ownerOverrideSchema],
    liability: ['liability', liabilityOverrideSchema],
    inflowModel: ['inflow_model', inflowModelSchema],
    income: ['income', optional(incomeOverrideSchema)],
  })
);
