/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';
import { Email, emailSchema } from './email.js';
import { PhoneNumber, phoneNumberSchema } from './phoneNumber.js';

/** Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox information. */
export interface OwnerOverride {
  /** A list of names associated with the account by the financial institution. These should always be the names of individuals, even for business accounts. Note that the same name data will be used for all accounts associated with an Item. */
  names: string[];
  /** A list of phone numbers associated with the account. */
  phoneNumbers: PhoneNumber[];
  /** A list of email addresses associated with the account. */
  emails: Email[];
  /** Data about the various addresses associated with the account. */
  addresses: Address[];
  additionalProperties?: Record<string, unknown>;
}

export const ownerOverrideSchema: Schema<OwnerOverride> = lazy(() =>
  typedExpandoObject(
    {
      names: ['names', array(string())],
      phoneNumbers: ['phone_numbers', array(phoneNumberSchema)],
      emails: ['emails', array(emailSchema)],
      addresses: ['addresses', array(addressSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
