/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object representing a monetary amount. */
export interface Pay {
  /** A numerical amount of a specific currency. */
  amount?: number | null;
  /** Currency code, e.g. USD */
  currency?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const paySchema: Schema<Pay> = typedExpandoObject(
  {
    amount: ['amount', optional(nullable(number()))],
    currency: ['currency', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
