/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PayFrequency1
 */
export enum PayFrequency1 {
  Monthly = 'MONTHLY',
  Biweekly = 'BI-WEEKLY',
  Weekly = 'WEEKLY',
  Semimonthly = 'SEMI-MONTHLY',
}

/**
 * Schema for PayFrequency1
 */
export const payFrequency1Schema: Schema<PayFrequency1> = stringEnum(
  PayFrequency1,
  true
);
