/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentInitiationStandingOrderMetadata,
  paymentInitiationStandingOrderMetadataSchema,
} from './paymentInitiationStandingOrderMetadata.js';

/** Metadata that captures what specific payment configurations an institution supports when making Payment Initiation requests. */
export interface PaymentInitiationMetadata {
  /** Indicates whether the institution supports payments from a different country. */
  supportsInternationalPayments: boolean;
  /**
   * A mapping of currency to maximum payment amount (denominated in the smallest unit of currency) supported by the insitution.
   * Example: `{"GBP": "10000"}`
   */
  maximumPaymentAmount: Record<string, string>;
  /** Indicates whether the institution supports returning refund details when initiating a payment. */
  supportsRefundDetails: boolean;
  /** Metadata specifically related to valid Payment Initiation standing order configurations for the institution. */
  standingOrderMetadata: PaymentInitiationStandingOrderMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInitiationMetadataSchema: Schema<PaymentInitiationMetadata> = lazy(
  () =>
    typedExpandoObject(
      {
        supportsInternationalPayments: [
          'supports_international_payments',
          boolean(),
        ],
        maximumPaymentAmount: ['maximum_payment_amount', dict(string())],
        supportsRefundDetails: ['supports_refund_details', boolean()],
        standingOrderMetadata: [
          'standing_order_metadata',
          paymentInitiationStandingOrderMetadataSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
