/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** PaymentInitiationRecipientGetRequest defines the request schema for `/payment_initiation/recipient/get` */
export interface PaymentInitiationRecipientGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The ID of the recipient */
  recipientId: string;
}

export const paymentInitiationRecipientGetRequestSchema: Schema<PaymentInitiationRecipientGetRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    recipientId: ['recipient_id', string()],
  }
);
