/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentInitiationOptionalRestrictionBacs,
  paymentInitiationOptionalRestrictionBacsSchema,
} from './paymentInitiationOptionalRestrictionBacs.js';

/** Additional payment options */
export interface PaymentOptions {
  /** When `true`, Plaid will attempt to request refund details from the payee's financial institution.  Support varies between financial institutions and will not always be available.  If refund details could be retrieved, they will be available in the `/payment_initiation/payment/get` response. */
  requestRefundDetails?: boolean | null;
  /** The International Bank Account Number (IBAN) for the payer's account. If provided, the end user will be able to send payments only from the specified bank account. */
  iban?: string | null;
  bacs?: PaymentInitiationOptionalRestrictionBacs;
  /** The EMI (E-Money Institution) account that this payment is associated with, if any. This EMI account is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests. */
  emiAccountId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const paymentOptionsSchema: Schema<PaymentOptions> = lazy(() =>
  typedExpandoObject(
    {
      requestRefundDetails: [
        'request_refund_details',
        optional(nullable(boolean())),
      ],
      iban: ['iban', optional(nullable(string()))],
      bacs: ['bacs', optional(paymentInitiationOptionalRestrictionBacsSchema)],
      emiAccountId: ['emi_account_id', optional(nullable(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
