/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** PaymentInitiationPaymentCreateResponse defines the response schema for `/payment_initiation/payment/create` */
export interface PaymentInitiationPaymentCreateResponse {
  /** A unique ID identifying the payment */
  paymentId: string;
  /**
   * For a payment returned by this endpoint, there is only one possible value:
   * `PAYMENT_STATUS_INPUT_NEEDED`: The initial phase of the payment
   */
  status: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const paymentInitiationPaymentCreateResponseSchema: Schema<PaymentInitiationPaymentCreateResponse> = object(
  {
    paymentId: ['payment_id', string()],
    status: ['status', string()],
    requestId: ['request_id', string()],
  }
);
