/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** PaymentInitiationPaymentTokenCreateResponse defines the response schema for `/payment_initiation/payment/token/create` */
export interface PaymentInitiationPaymentTokenCreateResponse {
  /** A `payment_token` that can be provided to Link initialization to enter the payment initiation flow */
  paymentToken: string;
  /** The date and time at which the token will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. A `payment_token` expires after 15 minutes. */
  paymentTokenExpirationTime: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const paymentInitiationPaymentTokenCreateResponseSchema: Schema<PaymentInitiationPaymentTokenCreateResponse> = object(
  {
    paymentToken: ['payment_token', string()],
    paymentTokenExpirationTime: ['payment_token_expiration_time', string()],
    requestId: ['request_id', string()],
  }
);
