/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, Schema, string } from '../schema.js';
import {
  PaymentInitiationPayment,
  paymentInitiationPaymentSchema,
} from './paymentInitiationPayment.js';

/** PaymentInitiationPaymentListResponse defines the response schema for `/payment_initiation/payment/list` */
export interface PaymentInitiationPaymentListResponse {
  /** An array of payments that have been created, associated with the given `client_id`. */
  payments: PaymentInitiationPayment[];
  /** The value that, when used as the optional `cursor` parameter to `/payment_initiation/payment/list`, will return the next unreturned payment as its first payment. */
  nextCursor: string | null;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const paymentInitiationPaymentListResponseSchema: Schema<PaymentInitiationPaymentListResponse> = lazy(
  () =>
    object({
      payments: ['payments', array(paymentInitiationPaymentSchema)],
      nextCursor: ['next_cursor', nullable(string())],
      requestId: ['request_id', string()],
    })
);
