/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import {
  PaymentInitiationAddress,
  paymentInitiationAddressSchema,
} from './paymentInitiationAddress.js';
import {
  RecipientBACSNullable,
  recipientBACSNullableSchema,
} from './recipientBACSNullable.js';

/** PaymentInitiationRecipientGetResponse defines the response schema for `/payment_initiation/recipient/get` */
export interface PaymentInitiationRecipientGetResponse {
  /** The ID of the recipient. */
  recipientId: string;
  /** The name of the recipient. */
  name: string;
  /** The optional address of the payment recipient. This object is not currently required to make payments from UK institutions and should not be populated, though may be necessary for future European expansion. */
  address?: PaymentInitiationAddress;
  /** The International Bank Account Number (IBAN) for the recipient. */
  iban?: string | null;
  bacs?: RecipientBACSNullable;
  /** The EMI (E-Money Institution) recipient that this recipient is associated with, if any. This EMI recipient is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests. */
  emiRecipientId?: string | null;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const paymentInitiationRecipientGetResponseSchema: Schema<PaymentInitiationRecipientGetResponse> = lazy(
  () =>
    object({
      recipientId: ['recipient_id', string()],
      name: ['name', string()],
      address: ['address', optional(paymentInitiationAddressSchema)],
      iban: ['iban', optional(nullable(string()))],
      bacs: ['bacs', optional(recipientBACSNullableSchema)],
      emiRecipientId: ['emi_recipient_id', optional(nullable(string()))],
      requestId: ['request_id', string()],
    })
);
