/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** PaymentInitiationPaymentGetRequest defines the request schema for `/payment_initiation/payment/get` */
export interface PaymentInitiationPaymentGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The `payment_id` returned from `/payment_initiation/payment/create`. */
  paymentId: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInitiationPaymentGetRequestSchema: Schema<PaymentInitiationPaymentGetRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    paymentId: ['payment_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
