/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Currency, currencySchema } from './currency.js';

/** The amount and currency of a payment */
export interface PaymentAmount {
  /** The ISO-4217 currency code of the payment. For standing orders, `"GBP"` must be used. */
  currency: Currency;
  /** The amount of the payment. Must contain at most two digits of precision e.g. `1.23`. Minimum accepted value is `1`. */
  value: number;
  additionalProperties?: Record<string, unknown>;
}

export const paymentAmountSchema: Schema<PaymentAmount> = typedExpandoObject(
  { currency: ['currency', currencySchema], value: ['value', number()] },
  'additionalProperties',
  optional(unknown())
);
