/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';

/** The amount and currency of a payment */
export interface PaymentAmount {
  /** The ISO-4217 currency code of the payment. For standing orders, `"GBP"` must be used. */
  currency: CurrencyEnum;
  /** The amount of the payment. Must contain at most two digits of precision e.g. `1.23`. Minimum accepted value is `1`. */
  value: number;
}

export const paymentAmountSchema: Schema<PaymentAmount> = object({
  currency: ['currency', currencyEnumSchema],
  value: ['value', number()],
});
