/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentInitiationAddress,
  paymentInitiationAddressSchema,
} from './paymentInitiationAddress.js';
import {
  RecipientBacsNullable,
  recipientBacsNullableSchema,
} from './recipientBacsNullable.js';

/** PaymentInitiationRecipient defines a payment initiation recipient */
export interface PaymentInitiationRecipient {
  /** The ID of the recipient. */
  recipientId: string;
  /** The name of the recipient. */
  name: string;
  /** The optional address of the payment recipient. This object is not currently required to make payments from UK institutions and should not be populated, though may be necessary for future European expansion. */
  address?: PaymentInitiationAddress;
  /** The International Bank Account Number (IBAN) for the recipient. */
  iban?: string | null;
  bacs?: RecipientBacsNullable;
  /** The EMI (E-Money Institution) recipient that this recipient is associated with, if any. This EMI recipient is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests. */
  emiRecipientId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInitiationRecipientSchema: Schema<PaymentInitiationRecipient> = lazy(
  () =>
    typedExpandoObject(
      {
        recipientId: ['recipient_id', string()],
        name: ['name', string()],
        address: ['address', optional(paymentInitiationAddressSchema)],
        iban: ['iban', optional(nullable(string()))],
        bacs: ['bacs', optional(recipientBacsNullableSchema)],
        emiRecipientId: ['emi_recipient_id', optional(nullable(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
