/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** PaymentInitiationPaymentGetRequest defines the request schema for `/payment_initiation/payment/get` */
export interface PaymentInitiationPaymentGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The `payment_id` returned from `/payment_initiation/payment/create`. */
  paymentId: string;
}

export const paymentInitiationPaymentGetRequestSchema: Schema<PaymentInitiationPaymentGetRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    paymentId: ['payment_id', string()],
  }
);
