/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentAmount, paymentAmountSchema } from './paymentAmount.js';
import { Status2, status2Schema } from './status2.js';

/** PaymentInitiationRefund defines a payment initiation refund */
export interface PaymentInitiationRefund {
  /** The ID of the refund. Like all Plaid identifiers, the `refund_id` is case sensitive. */
  refundId: string;
  /** The amount and currency of a payment */
  amount: PaymentAmount;
  /**
   * The status of the refund.
   * `PROCESSING`: The refund is currently being processed. The refund will automatically exit this state when processing is complete.
   * `INITIATED`: The refund has been successfully initiated.
   * `EXECUTED`: Indicates that the refund has been successfully executed.
   * `FAILED`: The refund has failed to be executed. This error is retryable once the root cause is resolved.
   */
  status: Status2;
  /** The date and time of the last time the `status` was updated, in IS0 8601 format */
  lastStatusUpdate: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInitiationRefundSchema: Schema<PaymentInitiationRefund> = lazy(
  () =>
    typedExpandoObject(
      {
        refundId: ['refund_id', string()],
        amount: ['amount', paymentAmountSchema],
        status: ['status', status2Schema],
        lastStatusUpdate: ['last_status_update', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
