/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** PaymentInitiationPaymentListRequest defines the request schema for `/payment_initiation/payment/list` */
export interface PaymentInitiationPaymentListRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The maximum number of payments to return. If `count` is not specified, a maximum of 10 payments will be returned, beginning with the most recent payment before the cursor (if specified). */
  count?: number | null;
  /** A string in RFC 3339 format (i.e. "2019-12-06T22:35:49Z"). Only payments created before the cursor will be returned. */
  cursor?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInitiationPaymentListRequestSchema: Schema<PaymentInitiationPaymentListRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    count: ['count', optional(nullable(number()))],
    cursor: ['cursor', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
