/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Employee2, employee2Schema } from './employee2.js';
import { Employer3, employer3Schema } from './employer3.js';
import { IncomeBreakdown, incomeBreakdownSchema } from './incomeBreakdown.js';
import {
  PayPeriodDetails,
  payPeriodDetailsSchema,
} from './payPeriodDetails.js';

/** An object representing data from a paystub. */
export interface PaystubOverride {
  /** The employer on the paystub. */
  employer?: Employer3;
  /** The employee on the paystub. */
  employee?: Employee2;
  incomeBreakdown?: IncomeBreakdown[];
  /** Details about the pay period. */
  payPeriodDetails?: PayPeriodDetails;
  additionalProperties?: Record<string, unknown>;
}

export const paystubOverrideSchema: Schema<PaystubOverride> = lazy(() =>
  typedExpandoObject(
    {
      employer: ['employer', optional(employer3Schema)],
      employee: ['employee', optional(employee2Schema)],
      incomeBreakdown: [
        'income_breakdown',
        optional(array(incomeBreakdownSchema)),
      ],
      payPeriodDetails: [
        'pay_period_details',
        optional(payPeriodDetailsSchema),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
