/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface PaystubDeduction {
  /** The description of the deduction, as provided on the paystub. For example: `"401(k)"`, `"FICA MED TAX"`. */
  type: string | null;
  /** `true` if the deduction is pre-tax; `false` otherwise. */
  isPretax: boolean | null;
  /** The amount of the deduction. */
  total: number | null;
}

export const paystubDeductionSchema: Schema<PaystubDeduction> = object({
  type: ['type', nullable(string())],
  isPretax: ['is_pretax', nullable(boolean())],
  total: ['total', nullable(number())],
});
