/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fired when an Item’s access consent is expiring in 7 days. Some Items have explicit expiration times and we try to relay this when possible to reduce service disruption. This can be resolved by having the user go through Link’s update mode. */
export interface PendingExpirationWebhook {
  /** `ITEM` */
  webhookType: string;
  /** `PENDING_EXPIRATION` */
  webhookCode: string;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  /** The date and time at which the Item's access consent will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format */
  consentExpirationTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const pendingExpirationWebhookSchema: Schema<PendingExpirationWebhook> = typedExpandoObject(
  {
    webhookType: ['webhook_type', string()],
    webhookCode: ['webhook_code', string()],
    itemId: ['item_id', string()],
    consentExpirationTime: ['consent_expiration_time', string()],
  },
  'additionalProperties',
  optional(unknown())
);
