/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface PersonalFinanceCategory2 {
  /** A high level category that communicates the broad category of the transaction. */
  primary: string;
  /** Provides additional granularity to the primary categorization. */
  detailed: string;
}

export const personalFinanceCategory2Schema: Schema<PersonalFinanceCategory2> = object(
  { primary: ['primary', string()], detailed: ['detailed', string()] }
);
