/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PersonalFinanceCategory2 {
  /** A high level category that communicates the broad category of the transaction. */
  primary: string;
  /** Provides additional granularity to the primary categorization. */
  detailed: string;
  additionalProperties?: Record<string, unknown>;
}

export const personalFinanceCategory2Schema: Schema<PersonalFinanceCategory2> = typedExpandoObject(
  { primary: ['primary', string()], detailed: ['detailed', string()] },
  'additionalProperties',
  optional(unknown())
);
