/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** ProcessorTokenCreateResponse defines the response schema for `/processor/token/create` and `/processor/apex/processor_token/create` */
export interface ProcessorTokenCreateResponse {
  /** The `processor_token` that can then be used by the Plaid partner to make API requests */
  processorToken: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const processorTokenCreateResponseSchema: Schema<ProcessorTokenCreateResponse> = object(
  {
    processorToken: ['processor_token', string()],
    requestId: ['request_id', string()],
  }
);
