/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Processor
 */
export enum Processor {
  Achq = 'achq',
  Alpaca = 'alpaca',
  Astra = 'astra',
  Check = 'check',
  Checkbook = 'checkbook',
  Circle = 'circle',
  Drivewealth = 'drivewealth',
  Dwolla = 'dwolla',
  Galileo = 'galileo',
  Lithic = 'lithic',
  ModernTreasury = 'modern_treasury',
  Moov = 'moov',
  Ocrolus = 'ocrolus',
  PrimeTrust = 'prime_trust',
  Rize = 'rize',
  SilaMoney = 'sila_money',
  SvbApi = 'svb_api',
  TreasuryPrime = 'treasury_prime',
  Unit = 'unit',
  Vesta = 'vesta',
  Vopay = 'vopay',
  Wyre = 'wyre',
}

/**
 * Schema for Processor
 */
export const processorSchema: Schema<Processor> = stringEnum(Processor, true);
