/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { ProcessorEnum, processorEnumSchema } from './processorEnum.js';

/** ProcessorTokenCreateRequest defines the request schema for `/processor/token/create` */
export interface ProcessorTokenCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** The `account_id` value obtained from the `onSuccess` callback in Link */
  accountId: string;
  /** The processor you are integrating with. */
  processor: ProcessorEnum;
}

export const processorTokenCreateRequestSchema: Schema<ProcessorTokenCreateRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    accessToken: ['access_token', string()],
    accountId: ['account_id', string()],
    processor: ['processor', processorEnumSchema],
  }
);
