/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Account, accountSchema } from './account.js';

/** ProcessorBalanceGetResponse defines the response schema for `/processor/balance/get` */
export interface ProcessorBalanceGetResponse {
  /** A single account at a financial institution. */
  account: Account;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const processorBalanceGetResponseSchema: Schema<ProcessorBalanceGetResponse> = lazy(
  () =>
    object({
      account: ['account', accountSchema],
      requestId: ['request_id', string()],
    })
);
