/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  NumbersACHNullable,
  numbersACHNullableSchema,
} from './numbersACHNullable.js';
import {
  NumbersBACSNullable,
  numbersBACSNullableSchema,
} from './numbersBACSNullable.js';
import {
  NumbersEFTNullable,
  numbersEFTNullableSchema,
} from './numbersEFTNullable.js';
import {
  NumbersInternationalNullable,
  numbersInternationalNullableSchema,
} from './numbersInternationalNullable.js';

/** An object containing identifying numbers used for making electronic transfers to and from the `account`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by the `account` for which auth data has been requested, a null value will be returned. */
export interface ProcessorNumber {
  ach?: NumbersACHNullable;
  eft?: NumbersEFTNullable;
  international?: NumbersInternationalNullable;
  bacs?: NumbersBACSNullable;
}

export const processorNumberSchema: Schema<ProcessorNumber> = lazy(() =>
  object({
    ach: ['ach', optional(numbersACHNullableSchema)],
    eft: ['eft', optional(numbersEFTNullableSchema)],
    international: [
      'international',
      optional(numbersInternationalNullableSchema),
    ],
    bacs: ['bacs', optional(numbersBACSNullableSchema)],
  })
);
