/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BankTransfer, bankTransferSchema } from './bankTransfer.js';

/** Defines the response schema for `/processor/bank_transfer/create` */
export interface ProcessorBankTransferCreateResponse {
  /** Represents a bank transfer within the Bank Transfers API. */
  bankTransfer: BankTransfer;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const processorBankTransferCreateResponseSchema: Schema<ProcessorBankTransferCreateResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        bankTransfer: ['bank_transfer', bankTransferSchema],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
