/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AchClass, achClassSchema } from './achClass.js';
import {
  BankTransferNetwork,
  bankTransferNetworkSchema,
} from './bankTransferNetwork.js';
import {
  BankTransferType,
  bankTransferTypeSchema,
} from './bankTransferType.js';
import {
  BankTransferUser,
  bankTransferUserSchema,
} from './bankTransferUser.js';

/** Defines the request schema for `/processor/bank_transfer/create` */
export interface ProcessorBankTransferCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /**
   * A random key provided by the client, per unique bank transfer. Maximum of 50 characters.
   * The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. For example, if a request to create a bank transfer fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single bank transfer is created.
   */
  idempotencyKey: string;
  /** The processor token obtained from the Plaid integration partner. Processor tokens are in the format: `processor-<environment>-<identifier>` */
  processorToken: string;
  /** The type of bank transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account. */
  type: BankTransferType;
  /** The network or rails used for the transfer. Valid options are `ach`, `same-day-ach`, or `wire`. */
  network: BankTransferNetwork;
  /** The amount of the bank transfer (decimal string with two digits of precision e.g. “10.00”). */
  amount: string;
  /** The currency of the transfer amount – should be set to "USD". */
  isoCurrencyCode: string;
  /** The transfer description. Maximum of 10 characters. */
  description: string;
  /**
   * Specifies the use case of the transfer.  Required for transfers on an ACH network.
   * `"arc"` - Accounts Receivable Entry
   * `"cbr`" - Cross Border Entry
   * `"ccd"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts
   * `"cie"` - Customer Initiated Entry
   * `"cor"` - Automated Notification of Change
   * `"ctx"` - Corporate Trade Exchange
   * `"iat"` - International
   * `"mte"` - Machine Transfer Entry
   * `"pbr"` - Cross Border Entry
   * `"pop"` - Point-of-Purchase Entry
   * `"pos"` - Point-of-Sale Entry
   * `"ppd"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment
   * `"rck"` - Re-presented Check Entry
   * `"tel"` - Telephone-Initiated Entry
   * `"web"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
   */
  achClass?: AchClass;
  /** The legal name and other information for the account holder. */
  user: BankTransferUser;
  /** An arbitrary string provided by the client for storage with the bank transfer. May be up to 100 characters. */
  customTag?: string | null;
  /**
   * The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply:
   * - The JSON values must be Strings (no nested JSON objects allowed)
   * - Only ASCII characters may be used
   * - Maximum of 50 key/value pairs
   * - Maximum key length of 40 characters
   * - Maximum value length of 500 characters
   */
  metadata?: Record<string, string>;
  /** Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination account, this value must be specified. */
  originationAccountId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const processorBankTransferCreateRequestSchema: Schema<ProcessorBankTransferCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        secret: ['secret', optional(string())],
        idempotencyKey: ['idempotency_key', string()],
        processorToken: ['processor_token', string()],
        type: ['type', bankTransferTypeSchema],
        network: ['network', bankTransferNetworkSchema],
        amount: ['amount', string()],
        isoCurrencyCode: ['iso_currency_code', string()],
        description: ['description', string()],
        achClass: ['ach_class', optional(achClassSchema)],
        user: ['user', bankTransferUserSchema],
        customTag: ['custom_tag', optional(nullable(string()))],
        metadata: ['metadata', optional(dict(string()))],
        originationAccountId: [
          'origination_account_id',
          optional(nullable(string())),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
