/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Account, accountSchema } from './account.js';
import { ProcessorNumber, processorNumberSchema } from './processorNumber.js';

/** ProcessorAuthGetResponse defines the response schema for `/processor/auth/get` */
export interface ProcessorAuthGetResponse {
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  /** An object containing identifying numbers used for making electronic transfers to and from the `account`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by the `account` for which auth data has been requested, a null value will be returned. */
  numbers: ProcessorNumber;
  /** A single account at a financial institution. */
  account: Account;
}

export const processorAuthGetResponseSchema: Schema<ProcessorAuthGetResponse> = lazy(
  () =>
    object({
      requestId: ['request_id', string()],
      numbers: ['numbers', processorNumberSchema],
      account: ['account', accountSchema],
    })
);
