/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountIdentity, accountIdentitySchema } from './accountIdentity.js';

/** ProcessorIdentityGetResponse defines the response schema for `/processor/identity/get` */
export interface ProcessorIdentityGetResponse {
  account: AccountIdentity;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const processorIdentityGetResponseSchema: Schema<ProcessorIdentityGetResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        account: ['account', accountIdentitySchema],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
