/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProductsEnum
 */
export enum ProductsEnum {
  Assets = 'assets',
  Auth = 'auth',
  Balance = 'balance',
  Identity = 'identity',
  Investments = 'investments',
  Liabilities = 'liabilities',
  PaymentInitiation = 'payment_initiation',
  Transactions = 'transactions',
  CreditDetails = 'credit_details',
  Income = 'income',
  IncomeVerification = 'income_verification',
  DepositSwitch = 'deposit_switch',
  StandingOrders = 'standing_orders',
  Transfer = 'transfer',
}

/**
 * Schema for ProductsEnum
 */
export const productsEnumSchema: Schema<ProductsEnum> = stringEnum(
  ProductsEnum
);
