/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An object containing a BACS account number and sort code. If an IBAN is not provided or if this recipient needs to accept domestic GBP-denominated payments, BACS data is required. */
export interface RecipientBACS {
  /** The account number of the account. Maximum of 10 characters. */
  account?: string;
  /** The 6-character sort code of the account. */
  sortCode?: string;
}

export const recipientBACSSchema: Schema<RecipientBACS> = object({
  account: ['account', optional(string())],
  sortCode: ['sort_code', optional(string())],
});
