/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RefreshInterval
 */
export enum RefreshInterval {
  Normal = 'NORMAL',
  Delayed = 'DELAYED',
  Stopped = 'STOPPED',
}

/**
 * Schema for RefreshInterval
 */
export const refreshIntervalSchema: Schema<RefreshInterval> = stringEnum(
  RefreshInterval,
  true
);
