/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountFilter, accountFilterSchema } from './accountFilter.js';
import {
  AccountSelectionCardinality,
  accountSelectionCardinalitySchema,
} from './accountSelectionCardinality.js';
import { ProductAccess, productAccessSchema } from './productAccess.js';

/** Scope of required and optional account features or content from a ConnectedApplication. */
export interface RequestedScopes {
  /** The product access being requested. Used to or disallow product access across all accounts. If unset, defaults to all products allowed. */
  requiredProductAccess: ProductAccess;
  /** The product access being requested. Used to or disallow product access across all accounts. If unset, defaults to all products allowed. */
  optionalProductAccess: ProductAccess;
  /** Enumerates the account subtypes that the application wishes for the user to be able to select from. For more details refer to Plaid documentation on account filters. */
  accountFilters?: AccountFilter;
  /**
   * The application requires that accounts be limited to a specific cardinality.
   * `MULTI_SELECT`: indicates that the user should be allowed to pick multiple accounts.
   * `SINGLE_SELECT`: indicates that the user should be allowed to pick only a single account.
   * `ALL`: indicates that the user must share all of their accounts and should not be given the opportunity to de-select
   */
  accountSelectionCardinality: AccountSelectionCardinality;
  additionalProperties?: Record<string, unknown>;
}

export const requestedScopesSchema: Schema<RequestedScopes> = lazy(() =>
  typedExpandoObject(
    {
      requiredProductAccess: ['required_product_access', productAccessSchema],
      optionalProductAccess: ['optional_product_access', productAccessSchema],
      accountFilters: ['account_filters', optional(accountFilterSchema)],
      accountSelectionCardinality: [
        'account_selection_cardinality',
        accountSelectionCardinalitySchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
