/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ProductsEnum, productsEnumSchema } from './productsEnum.js';
import {
  SandboxPublicTokenCreateRequestOptions,
  sandboxPublicTokenCreateRequestOptionsSchema,
} from './sandboxPublicTokenCreateRequestOptions.js';

/** SandboxPublicTokenCreateRequest defines the request schema for `/sandbox/public_token/create` */
export interface SandboxPublicTokenCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The ID of the institution the Item will be associated with */
  institutionId: string;
  /** The products to initially pull for the Item. May be any products that the specified `institution_id`  supports. This array may not be empty. */
  initialProducts: ProductsEnum[];
  /** An optional set of options to be used when configuring the Item. If specified, must not be `null`. */
  options?: SandboxPublicTokenCreateRequestOptions;
}

export const sandboxPublicTokenCreateRequestSchema: Schema<SandboxPublicTokenCreateRequest> = lazy(
  () =>
    object({
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      institutionId: ['institution_id', string()],
      initialProducts: ['initial_products', array(productsEnumSchema)],
      options: [
        'options',
        optional(sandboxPublicTokenCreateRequestOptionsSchema),
      ],
    })
);
