/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import {
  SandboxPublicTokenCreateRequestOptionsTransactions,
  sandboxPublicTokenCreateRequestOptionsTransactionsSchema,
} from './sandboxPublicTokenCreateRequestOptionsTransactions.js';

/** An optional set of options to be used when configuring the Item. If specified, must not be `null`. */
export interface SandboxPublicTokenCreateRequestOptions {
  /** Specify a webhook to associate with the new Item. */
  webhook?: string;
  /** Test username to use for the creation of the Sandbox Item. Default value is `user_good`. */
  overrideUsername?: string | null;
  /** Test password to use for the creation of the Sandbox Item. Default value is `pass_good`. */
  overridePassword?: string | null;
  /** SandboxPublicTokenCreateRequestOptionsTransactions is an optional set of parameters corresponding to transactions options. */
  transactions?: SandboxPublicTokenCreateRequestOptionsTransactions;
}

export const sandboxPublicTokenCreateRequestOptionsSchema: Schema<SandboxPublicTokenCreateRequestOptions> = lazy(
  () =>
    object({
      webhook: ['webhook', optional(string())],
      overrideUsername: ['override_username', optional(nullable(string()))],
      overridePassword: ['override_password', optional(nullable(string()))],
      transactions: [
        'transactions',
        optional(sandboxPublicTokenCreateRequestOptionsTransactionsSchema),
      ],
    })
);
