/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** SandboxPublicTokenCreateResponse defines the response schema for `/sandbox/public_token/create` */
export interface SandboxPublicTokenCreateResponse {
  /** A public token that can be exchanged for an access token using `/item/public_token/exchange` */
  publicToken: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const sandboxPublicTokenCreateResponseSchema: Schema<SandboxPublicTokenCreateResponse> = typedExpandoObject(
  {
    publicToken: ['public_token', string()],
    requestId: ['request_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
