/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Defines the response schema for `/sandbox/transfer/simulate` */
export interface SandboxTransferSimulateResponse {
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const sandboxTransferSimulateResponseSchema: Schema<SandboxTransferSimulateResponse> = object(
  { requestId: ['request_id', string()] }
);
