/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TransferFailure, transferFailureSchema } from './transferFailure.js';

/** Defines the request schema for `/sandbox/transfer/simulate` */
export interface SandboxTransferSimulateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Plaid’s unique identifier for a transfer. */
  transferId: string;
  /**
   * The asynchronous event to be simulated. May be: `posted`, `failed`, or `reversed`.
   * An error will be returned if the event type is incompatible with the current transfer status. Compatible status --> event type transitions include:
   * `pending` --> `failed`
   * `pending` --> `posted`
   * `posted` --> `reversed`
   */
  eventType: string;
  /** The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise. */
  failureReason?: TransferFailure;
  additionalProperties?: Record<string, unknown>;
}

export const sandboxTransferSimulateRequestSchema: Schema<SandboxTransferSimulateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        secret: ['secret', optional(string())],
        transferId: ['transfer_id', string()],
        eventType: ['event_type', string()],
        failureReason: ['failure_reason', optional(transferFailureSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
