/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** SandboxPublicTokenCreateRequestOptionsTransactions is an optional set of parameters corresponding to transactions options. */
export interface SandboxPublicTokenCreateRequestOptionsTransactions {
  /** The earliest date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD. */
  startDate?: string;
  /** The most recent date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD. */
  endDate?: string;
}

export const sandboxPublicTokenCreateRequestOptionsTransactionsSchema: Schema<SandboxPublicTokenCreateRequestOptionsTransactions> = object(
  {
    startDate: ['start_date', optional(string())],
    endDate: ['end_date', optional(string())],
  }
);
