/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface SandboxProcessorTokenCreateResponse {
  /** A processor token that can be used to call the `/processor/` endpoints. */
  processorToken: string;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const sandboxProcessorTokenCreateResponseSchema: Schema<SandboxProcessorTokenCreateResponse> = object(
  {
    processorToken: ['processor_token', string()],
    requestId: ['request_id', string()],
  }
);
