/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Defines the request schema for `sandbox/oauth/select_accounts` */
export interface SandboxOauthSelectAccountsRequest {
  oauthStateId: string;
  accounts: string[];
  additionalProperties?: Record<string, unknown>;
}

export const sandboxOauthSelectAccountsRequestSchema: Schema<SandboxOauthSelectAccountsRequest> = typedExpandoObject(
  {
    oauthStateId: ['oauth_state_id', string()],
    accounts: ['accounts', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
