/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** SandboxItemFireWebhookResponse defines the response schema for `/sandbox/item/fire_webhook` */
export interface SandboxItemFireWebhookResponse {
  /** Value is `true`  if the test` webhook_code`  was successfully fired. */
  webhookFired: boolean;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const sandboxItemFireWebhookResponseSchema: Schema<SandboxItemFireWebhookResponse> = typedExpandoObject(
  {
    webhookFired: ['webhook_fired', boolean()],
    requestId: ['request_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
