/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ScopesContextEnum
 */
export enum ScopesContextEnum {
  ENROLLMENT = 'ENROLLMENT',
  PORTAL = 'PORTAL',
}

/**
 * Schema for ScopesContextEnum
 */
export const scopesContextEnumSchema: Schema<ScopesContextEnum> = stringEnum(
  ScopesContextEnum
);
