/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Selling an investment */
export interface SellType {
  /** Outflow of assets from a tax-advantaged account */
  distribution?: string;
  /** Exercise of an option or warrant contract */
  exercise?: string;
  /** Sell to close or decrease an existing holding */
  sell?: string;
  /** Sell to open a short position */
  sellShort?: string;
}

export const sellTypeSchema: Schema<SellType> = object({
  distribution: ['distribution', optional(string())],
  exercise: ['exercise', optional(string())],
  sell: ['sell', optional(string())],
  sellShort: ['sell short', optional(string())],
});
