/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** SignalReturnReportRequest defines the request schema for `/signal/return/report` */
export interface SignalReturnReportRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate` */
  clientTransactionId: string;
  /** Must be a valid ACH return code (e.g. "R01") */
  returnCode: string;
}

export const signalReturnReportRequestSchema: Schema<SignalReturnReportRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    clientTransactionId: ['client_transaction_id', string()],
    returnCode: ['return_code', string()],
  }
);
