/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

/** SignalDecisionReportRequest defines the request schema for `/signal/decision/report` */
export interface SignalDecisionReportRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate` */
  clientTransactionId: string;
  /** `true` if the ACH transaction was initiated, `false` otherwise. */
  initiated: boolean;
}

export const signalDecisionReportRequestSchema: Schema<SignalDecisionReportRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    clientTransactionId: ['client_transaction_id', string()],
    initiated: ['initiated', boolean()],
  }
);
