/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CreditAccount, creditAccountSchema } from './creditAccount.js';
import {
  DepositoryAccount,
  depositoryAccountSchema,
} from './depositoryAccount.js';
import {
  InvestmentAccountSubtype,
  investmentAccountSubtypeSchema,
} from './investmentAccountSubtype.js';
import { LoanAccount, loanAccountSchema } from './loanAccount.js';

/** The schema below describes the various `types` and corresponding `subtypes` that Plaid recognizes and reports for financial institution accounts. */
export interface StandaloneAccountType {
  /** An account type holding cash, in which funds are deposited. Supported products for `depository` accounts are: Auth, Balance, Transactions, Identity, Payment Initiation, and Assets. */
  depository: DepositoryAccount;
  /** A credit card type account. Supported products for `credit` accounts are: Balance, Transactions, Identity, and Liabilities. */
  credit: CreditAccount;
  /** A loan type account. Supported products for `loan` accounts are: Balance, Liabilities, and Transactions. */
  loan: LoanAccount;
  /** An investment account. Supported products for `investment` accounts are: Balance and Investments. */
  investment: InvestmentAccountSubtype;
  /** Other or unknown account type. Supported products for `other` accounts are: Balance, Transactions, Identity, and Assets. */
  other: string;
  additionalProperties?: Record<string, unknown>;
}

export const standaloneAccountTypeSchema: Schema<StandaloneAccountType> = lazy(
  () =>
    typedExpandoObject(
      {
        depository: ['depository', depositoryAccountSchema],
        credit: ['credit', creditAccountSchema],
        loan: ['loan', loanAccountSchema],
        investment: ['investment', investmentAccountSubtypeSchema],
        other: ['other', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
