/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  UnofficialCurrencyCodeList,
  unofficialCurrencyCodeListSchema,
} from './unofficialCurrencyCodeList.js';

/** The following currency codes are supported by Plaid. */
export interface StandaloneCurrencyCodeList {
  /** Plaid supports all ISO 4217 currency codes. */
  isoCurrencyCode: string;
  /** List of unofficial currency codes */
  unofficialCurrencyCode: UnofficialCurrencyCodeList;
}

export const standaloneCurrencyCodeListSchema: Schema<StandaloneCurrencyCodeList> = lazy(
  () =>
    object({
      isoCurrencyCode: ['iso_currency_code', string()],
      unofficialCurrencyCode: [
        'unofficial_currency_code',
        unofficialCurrencyCodeListSchema,
      ],
    })
);
