/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status2Enum
 */
export enum Status2Enum {
  PROCESSING = 'PROCESSING',
  EXECUTED = 'EXECUTED',
  INITIATED = 'INITIATED',
  FAILED = 'FAILED',
}

/**
 * Schema for Status2Enum
 */
export const status2EnumSchema: Schema<Status2Enum> = stringEnum(Status2Enum);
