/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RefreshInterval, refreshIntervalSchema } from './refreshInterval.js';

/** A detailed breakdown of the institution's performance for a request type. The values for `success`, `error_plaid`, and `error_institution` sum to 1. */
export interface StatusBreakdown {
  /** The percentage of login attempts that are successful, expressed as a decimal. */
  success: number;
  /** The percentage of logins that are failing due to an internal Plaid issue, expressed as a decimal. */
  errorPlaid: number;
  /** The percentage of logins that are failing due to an issue in the institution's system, expressed as a decimal. */
  errorInstitution: number;
  /** The `refresh_interval` may be `DELAYED` or `STOPPED` even when the success rate is high. This value is only returned for Transactions status breakdowns. */
  refreshInterval?: RefreshInterval;
  additionalProperties?: Record<string, unknown>;
}

export const statusBreakdownSchema: Schema<StatusBreakdown> = typedExpandoObject(
  {
    success: ['success', number()],
    errorPlaid: ['error_plaid', number()],
    errorInstitution: ['error_institution', number()],
    refreshInterval: ['refresh_interval', optional(refreshIntervalSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
