/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StateEnum
 */
export enum StateEnum {
  Initialized = 'initialized',
  Processing = 'processing',
  Completed = 'completed',
  Error = 'error',
}

/**
 * Schema for StateEnum
 */
export const stateEnumSchema: Schema<StateEnum> = stringEnum(StateEnum);
