/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status
 */
export enum Status {
  Healthy = 'HEALTHY',
  Degraded = 'DEGRADED',
  Down = 'DOWN',
}

/**
 * Schema for Status
 */
export const statusSchema: Schema<Status> = stringEnum(Status, true);
