/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema.js';
import { Type2Enum, type2EnumSchema } from './type2Enum.js';

/** An object representing the status of the student loan */
export interface StudentLoanStatus {
  /** The date until which the loan will be in its current status. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). */
  endDate: string | null;
  /** The status type of the student loan */
  type: Type2Enum;
}

export const studentLoanStatusSchema: Schema<StudentLoanStatus> = object({
  endDate: ['end_date', nullable(string())],
  type: ['type', type2EnumSchema],
});
