/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

/** Student loan repayment information used to configure Sandbox test data for the Liabilities product */
export interface StudentLoanRepaymentModel {
  /** The only currently supported value for this field is `standard`. */
  type: string;
  /** Configures the number of months before repayment starts. */
  nonRepaymentMonths: number;
  /** Configures the number of months of repayments before the loan is paid off. */
  repaymentMonths: number;
}

export const studentLoanRepaymentModelSchema: Schema<StudentLoanRepaymentModel> = object(
  {
    type: ['type', string()],
    nonRepaymentMonths: ['non_repayment_months', number()],
    repaymentMonths: ['repayment_months', number()],
  }
);
