/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SubtypeEnum
 */
export enum SubtypeEnum {
  EnumAccountFee = 'account fee',
  Assignment = 'assignment',
  Buy = 'buy',
  EnumBuyToCover = 'buy to cover',
  Contribution = 'contribution',
  Deposit = 'deposit',
  Distribution = 'distribution',
  Dividend = 'dividend',
  EnumDividendReinvestment = 'dividend reinvestment',
  Exercise = 'exercise',
  Expire = 'expire',
  EnumFundFee = 'fund fee',
  Interest = 'interest',
  EnumInterestReceivable = 'interest receivable',
  EnumInterestReinvestment = 'interest reinvestment',
  EnumLegalFee = 'legal fee',
  EnumLoanPayment = 'loan payment',
  EnumLongtermCapitalGain = 'long-term capital gain',
  EnumLongtermCapitalGainReinvestment = 'long-term capital gain reinvestment',
  EnumManagementFee = 'management fee',
  EnumMarginExpense = 'margin expense',
  Merger = 'merger',
  EnumMiscellaneousFee = 'miscellaneous fee',
  EnumNonqualifiedDividend = 'non-qualified dividend',
  EnumNonresidentTax = 'non-resident tax',
  EnumPendingCredit = 'pending credit',
  EnumPendingDebit = 'pending debit',
  EnumQualifiedDividend = 'qualified dividend',
  Rebalance = 'rebalance',
  EnumReturnOfPrincipal = 'return of principal',
  Sell = 'sell',
  EnumSellShort = 'sell short',
  EnumShorttermCapitalGain = 'short-term capital gain',
  EnumShorttermCapitalGainReinvestment = 'short-term capital gain reinvestment',
  EnumSpinOff = 'spin off',
  Split = 'split',
  EnumStockDistribution = 'stock distribution',
  Tax = 'tax',
  EnumTaxWithheld = 'tax withheld',
  Transfer = 'transfer',
  EnumTransferFee = 'transfer fee',
  EnumTrustFee = 'trust fee',
  EnumUnqualifiedGain = 'unqualified gain',
  Withdrawal = 'withdrawal',
}

/**
 * Schema for SubtypeEnum
 */
export const subtypeEnumSchema: Schema<SubtypeEnum> = stringEnum(SubtypeEnum);
