/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TaxpayerId {
  /** Type of ID, e.g. 'SSN' */
  idType?: string | null;
  /** Last 4 digits of unique number of ID. */
  last4Digits?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const taxpayerIdSchema: Schema<TaxpayerId> = typedExpandoObject(
  {
    idType: ['id_type', optional(nullable(string()))],
    last4Digits: ['last_4_digits', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
