/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

export interface TaxpayerID {
  /** Type of ID, e.g. 'SSN' */
  idType?: string | null;
  /** Last 4 digits of unique number of ID. */
  last4Digits?: string | null;
}

export const taxpayerIDSchema: Schema<TaxpayerID> = object({
  idType: ['id_type', optional(nullable(string()))],
  last4Digits: ['last_4_digits', optional(nullable(string()))],
});
