/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import { CodeEnum, codeEnumSchema } from './codeEnum.js';

/** The rationale for Plaid's decision regarding a proposed transfer. Will be null for `approved` decisions. */
export interface TransferAuthorizationDecisionRationale {
  /**
   * A code representing the rationale for permitting or declining the proposed transfer. Possible values are:
   * `NSF` – Transaction likely to result in a return due to insufficient funds.
   * `RISK` - Transaction is high-risk.
   * `MANUALLY_VERIFIED_ITEM` – Item created via same-day micro deposits, limited information available. Plaid can only offer `permitted` as a transaction decision.
   * `LOGIN_REQUIRED` – Unable to collect the account information required for an authorization decision due to Item staleness. Can be rectified using Link update mode.
   * `ERROR` – Unable to collect the account information required for an authorization decision due to an error.
   */
  code: CodeEnum;
  /** A human-readable description of the code associated with a permitted transfer or transfer decline. */
  description: string;
}

export const transferAuthorizationDecisionRationaleSchema: Schema<TransferAuthorizationDecisionRationale> = object(
  { code: ['code', codeEnumSchema], description: ['description', string()] }
);
