/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

/** The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise. */
export interface TransferFailure {
  /** The ACH return code, e.g. `R01`.  A return code will be provided if and only if the transfer status is `reversed`. For a full listing of ACH return codes, see [Bank Transfers errors](https://plaid.com/docs/errors/bank-transfers/#ach-return-codes). */
  achReturnCode?: string | null;
  /** A human-readable description of the reason for the failure or reversal. */
  description?: string;
}

export const transferFailureSchema: Schema<TransferFailure> = object({
  achReturnCode: ['ach_return_code', optional(nullable(string()))],
  description: ['description', optional(string())],
});
