/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Defines the request schema for `/transfer/cancel` */
export interface TransferCancelRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** Plaid’s unique identifier for a transfer. */
  transferId: string;
  additionalProperties?: Record<string, unknown>;
}

export const transferCancelRequestSchema: Schema<TransferCancelRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    transferId: ['transfer_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
