/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Activity that modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transfer */
export interface TransferType {
  /** Assignment of short option holding */
  assignment?: string;
  /** Increase or decrease in quantity of item */
  adjustment?: string;
  /** Exercise of an option or warrant contract */
  exercise?: string;
  /** Expiration of an option or warrant contract */
  expire?: string;
  /** Stock exchanged at a pre-defined ratio as part of a merger between companies */
  merger?: string;
  /** Inflow of stock from spin-off transaction of an existing holding */
  spinOff?: string;
  /** Inflow of stock from a forward split of an existing holding */
  split?: string;
  /** Movement of assets into or out of an account */
  transfer?: string;
}

export const transferTypeSchema: Schema<TransferType> = object({
  assignment: ['assignment', optional(string())],
  adjustment: ['adjustment', optional(string())],
  exercise: ['exercise', optional(string())],
  expire: ['expire', optional(string())],
  merger: ['merger', optional(string())],
  spinOff: ['spin off', optional(string())],
  split: ['split', optional(string())],
  transfer: ['transfer', optional(string())],
});
