/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransferNetwork
 */
export enum TransferNetwork {
  Ach = 'ach',
  Samedayach = 'same-day-ach',
}

/**
 * Schema for TransferNetwork
 */
export const transferNetworkSchema: Schema<TransferNetwork> = stringEnum(
  TransferNetwork,
  true
);
