/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Transfer, transferSchema } from './transfer.js';

/** Defines the response schema for `/transfer/list` */
export interface TransferListResponse {
  transfers: Transfer[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const transferListResponseSchema: Schema<TransferListResponse> = lazy(
  () =>
    object({
      transfers: ['transfers', array(transferSchema)],
      requestId: ['request_id', string()],
    })
);
