/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, number, object, Schema, string } from '../schema.js';
import {
  TransferEventTypeEnum,
  transferEventTypeEnumSchema,
} from './transferEventTypeEnum.js';
import { TransferFailure, transferFailureSchema } from './transferFailure.js';
import {
  TransferType1Enum,
  transferType1EnumSchema,
} from './transferType1Enum.js';

/** Represents an event in the Transfers API. */
export interface TransferEvent {
  /** Plaid’s unique identifier for this event. IDs are sequential unsigned 64-bit integers. */
  eventId: number;
  /** The datetime when this event occurred. This will be of the form `2006-01-02T15:04:05Z`. */
  timestamp: string;
  /**
   * The type of event that this transfer represents.
   * `pending`: A new transfer was created; it is in the pending state.
   * `cancelled`: The transfer was cancelled by the client.
   * `failed`: The transfer failed, no funds were moved.
   * `posted`: The transfer has been successfully submitted to the payment network.
   * `reversed`: A posted transfer was reversed.
   */
  eventType: TransferEventTypeEnum;
  /** The account ID associated with the transfer. */
  accountId: string;
  /** Plaid’s unique identifier for a transfer. */
  transferId: string;
  /** The ID of the origination account that this balance belongs to. */
  originationAccountId: string | null;
  /** The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account. */
  transferType: TransferType1Enum;
  /** The amount of the transfer (decimal string with two digits of precision e.g. “10.00”). */
  transferAmount: string;
  /** The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise. */
  failureReason: TransferFailure;
}

export const transferEventSchema: Schema<TransferEvent> = lazy(() =>
  object({
    eventId: ['event_id', number()],
    timestamp: ['timestamp', string()],
    eventType: ['event_type', transferEventTypeEnumSchema],
    accountId: ['account_id', string()],
    transferId: ['transfer_id', string()],
    originationAccountId: ['origination_account_id', nullable(string())],
    transferType: ['transfer_type', transferType1EnumSchema],
    transferAmount: ['transfer_amount', string()],
    failureReason: ['failure_reason', transferFailureSchema],
  })
);
