/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema.js';

/** The address associated with the account holder. */
export interface TransferUserAddressInResponse {
  /** The street number and name (i.e., "100 Market St."). */
  street: string | null;
  /** Ex. "San Francisco" */
  city: string | null;
  /** The state or province (e.g., "California"). */
  region: string | null;
  /** The postal code (e.g., "94103"). */
  postalCode: string | null;
  /** A two-letter country code (e.g., "US"). */
  country: string | null;
}

export const transferUserAddressInResponseSchema: Schema<TransferUserAddressInResponse> = object(
  {
    street: ['street', nullable(string())],
    city: ['city', nullable(string())],
    region: ['region', nullable(string())],
    postalCode: ['postal_code', nullable(string())],
    country: ['country', nullable(string())],
  }
);
