/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  TransferAuthorization,
  transferAuthorizationSchema,
} from './transferAuthorization.js';

/** Defines the response schema for `/transfer/authorization/create` */
export interface TransferAuthorizationCreateResponse {
  /** TransferAuthorization contains the authorization decision for a proposed transfer */
  authorization: TransferAuthorization;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const transferAuthorizationCreateResponseSchema: Schema<TransferAuthorizationCreateResponse> = lazy(
  () =>
    object({
      authorization: ['authorization', transferAuthorizationSchema],
      requestId: ['request_id', string()],
    })
);
