/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransferEventType,
  transferEventTypeSchema,
} from './transferEventType.js';
import { TransferType2, transferType2Schema } from './transferType2.js';

/** Defines the request schema for `/transfer/event/list` */
export interface TransferEventListRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The start datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
  startDate?: string | null;
  /** The end datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
  endDate?: string | null;
  /** Plaid’s unique identifier for a transfer. */
  transferId?: string | null;
  /** The account ID to get events for all transactions to/from an account. */
  accountId?: string | null;
  /** The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into your origination account; a `credit` indicates a transfer of money out of your origination account. */
  transferType?: TransferType2;
  /** Filter events by event type. */
  eventTypes?: TransferEventType[];
  /** The maximum number of transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned. */
  count?: number | null;
  /** The offset into the list of transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 bank transfer events will be returned. */
  offset?: number | null;
  /** The origination account ID to get events for transfers from a specific origination account. */
  originationAccountId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const transferEventListRequestSchema: Schema<TransferEventListRequest> = typedExpandoObject(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    startDate: ['start_date', optional(nullable(string()))],
    endDate: ['end_date', optional(nullable(string()))],
    transferId: ['transfer_id', optional(nullable(string()))],
    accountId: ['account_id', optional(nullable(string()))],
    transferType: ['transfer_type', optional(transferType2Schema)],
    eventTypes: ['event_types', optional(array(transferEventTypeSchema))],
    count: ['count', optional(nullable(number()))],
    offset: ['offset', optional(nullable(number()))],
    originationAccountId: [
      'origination_account_id',
      optional(nullable(string())),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
