/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The address associated with the account holder. */
export interface TransferUserAddressInRequest {
  /** The street number and name (i.e., "100 Market St."). */
  street?: string;
  /** Ex. "San Francisco" */
  city?: string;
  /** The state or province (e.g., "California"). */
  region?: string;
  /** The postal code (e.g., "94103"). */
  postalCode?: string;
  /** A two-letter country code (e.g., "US"). */
  country?: string;
  additionalProperties?: Record<string, unknown>;
}

export const transferUserAddressInRequestSchema: Schema<TransferUserAddressInRequest> = typedExpandoObject(
  {
    street: ['street', optional(string())],
    city: ['city', optional(string())],
    region: ['region', optional(string())],
    postalCode: ['postal_code', optional(string())],
    country: ['country', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
