/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ACHClassEnum, aCHClassEnumSchema } from './aCHClassEnum.js';
import {
  TransferAuthorizationDevice,
  transferAuthorizationDeviceSchema,
} from './transferAuthorizationDevice.js';
import {
  TransferNetworkEnum,
  transferNetworkEnumSchema,
} from './transferNetworkEnum.js';
import {
  TransferType1Enum,
  transferType1EnumSchema,
} from './transferType1Enum.js';
import {
  TransferUserInRequest,
  transferUserInRequestSchema,
} from './transferUserInRequest.js';

/** Defines the request schema for `/transfer/authorization/create` */
export interface TransferAuthorizationCreateRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The Plaid `access_token` for the account that will be debited or credited. */
  accessToken: string;
  /** The Plaid `account_id` for the account that will be debited or credited. */
  accountId: string;
  /** The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account. */
  type: TransferType1Enum;
  /** The network or rails used for the transfer. Valid options are `ach` or `same-day-ach`. */
  network: TransferNetworkEnum;
  /** The amount of the transfer (decimal string with two digits of precision e.g. “10.00”). */
  amount: string;
  /**
   * Specifies the use case of the transfer.  Required for transfers on an ACH network.
   * `"arc"` - Accounts Receivable Entry
   * `"cbr`" - Cross Border Entry
   * `"ccd"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts
   * `"cie"` - Customer Initiated Entry
   * `"cor"` - Automated Notification of Change
   * `"ctx"` - Corporate Trade Exchange
   * `"iat"` - International
   * `"mte"` - Machine Transfer Entry
   * `"pbr"` - Cross Border Entry
   * `"pop"` - Point-of-Purchase Entry
   * `"pos"` - Point-of-Sale Entry
   * `"ppd"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment
   * `"rck"` - Re-presented Check Entry
   * `"tel"` - Telephone-Initiated Entry
   * `"web"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
   */
  achClass: ACHClassEnum;
  /** The legal name and other information for the account holder. */
  user: TransferUserInRequest;
  /** Information about the device being used to initiate the authorization. */
  device?: TransferAuthorizationDevice;
  /** Plaid's unique identifier for the origination account for this authorization. If not specified, the default account will be used. */
  originationAccountId?: string;
}

export const transferAuthorizationCreateRequestSchema: Schema<TransferAuthorizationCreateRequest> = lazy(
  () =>
    object({
      clientId: ['client_id', optional(string())],
      secret: ['secret', optional(string())],
      accessToken: ['access_token', string()],
      accountId: ['account_id', string()],
      type: ['type', transferType1EnumSchema],
      network: ['network', transferNetworkEnumSchema],
      amount: ['amount', string()],
      achClass: ['ach_class', aCHClassEnumSchema],
      user: ['user', transferUserInRequestSchema],
      device: ['device', optional(transferAuthorizationDeviceSchema)],
      originationAccountId: ['origination_account_id', optional(string())],
    })
);
