/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransferEventType
 */
export enum TransferEventType {
  Pending = 'pending',
  Cancelled = 'cancelled',
  Failed = 'failed',
  Posted = 'posted',
  Reversed = 'reversed',
}

/**
 * Schema for TransferEventType
 */
export const transferEventTypeSchema: Schema<TransferEventType> = stringEnum(
  TransferEventType,
  true
);
