/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Transfer, transferSchema } from './transfer.js';

/** Defines the response schema for `/transfer/create` */
export interface TransferCreateResponse {
  /** Represents a transfer within the Transfers API. */
  transfer: Transfer;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const transferCreateResponseSchema: Schema<TransferCreateResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        transfer: ['transfer', transferSchema],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
