/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TransferEvent, transferEventSchema } from './transferEvent.js';

/** Defines the response schema for `/transfer/event/list` */
export interface TransferEventListResponse {
  transferEvents: TransferEvent[];
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const transferEventListResponseSchema: Schema<TransferEventListResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        transferEvents: ['transfer_events', array(transferEventSchema)],
        requestId: ['request_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
