/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, dict, lazy, object, Schema, string } from '../schema.js';
import { ACHClassEnum, aCHClassEnumSchema } from './aCHClassEnum.js';
import { TransferFailure, transferFailureSchema } from './transferFailure.js';
import {
  TransferNetworkEnum,
  transferNetworkEnumSchema,
} from './transferNetworkEnum.js';
import {
  TransferStatusEnum,
  transferStatusEnumSchema,
} from './transferStatusEnum.js';
import {
  TransferType1Enum,
  transferType1EnumSchema,
} from './transferType1Enum.js';
import {
  TransferUserInResponse,
  transferUserInResponseSchema,
} from './transferUserInResponse.js';

/** Represents a transfer within the Transfers API. */
export interface Transfer {
  /** Plaid’s unique identifier for a transfer. */
  id: string;
  /**
   * Specifies the use case of the transfer.  Required for transfers on an ACH network.
   * `"arc"` - Accounts Receivable Entry
   * `"cbr`" - Cross Border Entry
   * `"ccd"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts
   * `"cie"` - Customer Initiated Entry
   * `"cor"` - Automated Notification of Change
   * `"ctx"` - Corporate Trade Exchange
   * `"iat"` - International
   * `"mte"` - Machine Transfer Entry
   * `"pbr"` - Cross Border Entry
   * `"pop"` - Point-of-Purchase Entry
   * `"pos"` - Point-of-Sale Entry
   * `"ppd"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment
   * `"rck"` - Re-presented Check Entry
   * `"tel"` - Telephone-Initiated Entry
   * `"web"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
   */
  achClass: ACHClassEnum;
  /** The account ID that should be credited/debited for this transfer. */
  accountId: string;
  /** The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account. */
  type: TransferType1Enum;
  /** The legal name and other information for the account holder. */
  user: TransferUserInResponse;
  /** The amount of the transfer (decimal string with two digits of precision e.g. “10.00”). */
  amount: string;
  /** The description of the transfer. */
  description: string;
  /** The datetime when this transfer was created. This will be of the form `2006-01-02T15:04:05Z` */
  created: string;
  /** The status of the transfer. */
  status: TransferStatusEnum;
  /** The network or rails used for the transfer. Valid options are `ach` or `same-day-ach`. */
  network: TransferNetworkEnum;
  /** When `true`, you can still cancel this transfer. */
  cancellable: boolean;
  /** The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise. */
  failureReason: TransferFailure;
  /**
   * The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply:
   * - The JSON values must be Strings (no nested JSON objects allowed)
   * - Only ASCII characters may be used
   * - Maximum of 50 key/value pairs
   * - Maximum key length of 40 characters
   * - Maximum value length of 500 characters
   */
  metadata: Record<string, string>;
  /** Plaid’s unique identifier for the origination account that was used for this transfer. */
  originationAccountId: string;
}

export const transferSchema: Schema<Transfer> = lazy(() =>
  object({
    id: ['id', string()],
    achClass: ['ach_class', aCHClassEnumSchema],
    accountId: ['account_id', string()],
    type: ['type', transferType1EnumSchema],
    user: ['user', transferUserInResponseSchema],
    amount: ['amount', string()],
    description: ['description', string()],
    created: ['created', string()],
    status: ['status', transferStatusEnumSchema],
    network: ['network', transferNetworkEnumSchema],
    cancellable: ['cancellable', boolean()],
    failureReason: ['failure_reason', transferFailureSchema],
    metadata: ['metadata', dict(string())],
    originationAccountId: ['origination_account_id', string()],
  })
);
