/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Information about the matched direct deposit transaction used to verify a user's payroll information. */
export interface TransactionData {
  /** The description of the transaction. */
  description: string;
  /** The amount of the transaction. */
  amount: number;
  /** The date of the transaction, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ("yyyy-mm-dd"). */
  date: string;
  /** A unique identifier for the end user's account. */
  accountId: string;
  /** A unique identifier for the transaction. */
  transactionId: string;
  additionalProperties?: Record<string, unknown>;
}

export const transactionDataSchema: Schema<TransactionData> = typedExpandoObject(
  {
    description: ['description', string()],
    amount: ['amount', number()],
    date: ['date', string()],
    accountId: ['account_id', string()],
    transactionId: ['transaction_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
