/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransferEventType,
  transferEventTypeSchema,
} from './transferEventType.js';
import { TransferFailure, transferFailureSchema } from './transferFailure.js';
import { TransferType1, transferType1Schema } from './transferType1.js';

/** Represents an event in the Transfers API. */
export interface TransferEvent {
  /** Plaid’s unique identifier for this event. IDs are sequential unsigned 64-bit integers. */
  eventId: number;
  /** The datetime when this event occurred. This will be of the form `2006-01-02T15:04:05Z`. */
  timestamp: string;
  /**
   * The type of event that this transfer represents.
   * `pending`: A new transfer was created; it is in the pending state.
   * `cancelled`: The transfer was cancelled by the client.
   * `failed`: The transfer failed, no funds were moved.
   * `posted`: The transfer has been successfully submitted to the payment network.
   * `reversed`: A posted transfer was reversed.
   */
  eventType: TransferEventType;
  /** The account ID associated with the transfer. */
  accountId: string;
  /** Plaid’s unique identifier for a transfer. */
  transferId: string;
  /** The ID of the origination account that this balance belongs to. */
  originationAccountId: string | null;
  /** The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account. */
  transferType: TransferType1;
  /** The amount of the transfer (decimal string with two digits of precision e.g. “10.00”). */
  transferAmount: string;
  /** The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise. */
  failureReason: TransferFailure;
  additionalProperties?: Record<string, unknown>;
}

export const transferEventSchema: Schema<TransferEvent> = lazy(() =>
  typedExpandoObject(
    {
      eventId: ['event_id', number()],
      timestamp: ['timestamp', string()],
      eventType: ['event_type', transferEventTypeSchema],
      accountId: ['account_id', string()],
      transferId: ['transfer_id', string()],
      originationAccountId: ['origination_account_id', nullable(string())],
      transferType: ['transfer_type', transferType1Schema],
      transferAmount: ['transfer_amount', string()],
      failureReason: ['failure_reason', transferFailureSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
