/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  TransferUserAddressInRequest,
  transferUserAddressInRequestSchema,
} from './transferUserAddressInRequest.js';

/** The legal name and other information for the account holder. */
export interface TransferUserInRequest {
  /** The user's legal name. */
  legalName: string;
  /** The user's phone number. */
  phoneNumber?: string;
  /** The user's email address. */
  emailAddress?: string;
  /** The address associated with the account holder. */
  address?: TransferUserAddressInRequest;
}

export const transferUserInRequestSchema: Schema<TransferUserInRequest> = lazy(
  () =>
    object({
      legalName: ['legal_name', string()],
      phoneNumber: ['phone_number', optional(string())],
      emailAddress: ['email_address', optional(string())],
      address: ['address', optional(transferUserAddressInRequestSchema)],
    })
);
