/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { DecisionEnum, decisionEnumSchema } from './decisionEnum.js';
import {
  TransferAuthorizationDecisionRationale,
  transferAuthorizationDecisionRationaleSchema,
} from './transferAuthorizationDecisionRationale.js';
import {
  TransferAuthorizationProposedTransfer,
  transferAuthorizationProposedTransferSchema,
} from './transferAuthorizationProposedTransfer.js';

/** TransferAuthorization contains the authorization decision for a proposed transfer */
export interface TransferAuthorization {
  /** Plaid’s unique identifier for a transfer authorization. */
  id: string;
  /** The datetime representing when the authorization was created, in the format "2006-01-02T15:04:05Z". */
  created: string;
  /**
   * A decision regarding the proposed transfer.
   * `approved` – The proposed transfer has received the end user's consent and has been approved for processing. Plaid has also reviewed the proposed transfer and has approved it for processing.
   * `permitted` – Plaid was unable to fetch the information required to approve or decline the proposed transfer. You may proceed with the transfer, but further review is recommended. Plaid is awaiting further instructions from the client.
   * `declined` – Plaid reviewed the proposed transfer and declined processing. Refer to the `code` field in the `decision_rationale` object for details.
   */
  decision: DecisionEnum;
  /** The rationale for Plaid's decision regarding a proposed transfer. Will be null for `approved` decisions. */
  decisionRationale: TransferAuthorizationDecisionRationale;
  /** Details regarding the proposed transfer. */
  proposedTransfer: TransferAuthorizationProposedTransfer;
}

export const transferAuthorizationSchema: Schema<TransferAuthorization> = lazy(
  () =>
    object({
      id: ['id', string()],
      created: ['created', string()],
      decision: ['decision', decisionEnumSchema],
      decisionRationale: [
        'decision_rationale',
        transferAuthorizationDecisionRationaleSchema,
      ],
      proposedTransfer: [
        'proposed_transfer',
        transferAuthorizationProposedTransferSchema,
      ],
    })
);
