/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionCode
 */
export enum TransactionCode {
  Adjustment = 'adjustment',
  Atm = 'atm',
  EnumBankCharge = 'bank charge',
  EnumBillPayment = 'bill payment',
  Cash = 'cash',
  Cashback = 'cashback',
  Cheque = 'cheque',
  EnumDirectDebit = 'direct debit',
  Interest = 'interest',
  Purchase = 'purchase',
  EnumStandingOrder = 'standing order',
  Transfer = 'transfer',
}

/**
 * Schema for TransactionCode
 */
export const transactionCodeSchema: Schema<TransactionCode> = stringEnum(
  TransactionCode,
  true
);
