/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** TransactionsRefreshRequest defines the request schema for `/transactions/refresh` */
export interface TransactionsRefreshRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
}

export const transactionsRefreshRequestSchema: Schema<TransactionsRefreshRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    accessToken: ['access_token', string()],
    secret: ['secret', optional(string())],
  }
);
