/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransferType2Enum
 */
export enum TransferType2Enum {
  Debit = 'debit',
  Credit = 'credit',
}

/**
 * Schema for TransferType2Enum
 */
export const transferType2EnumSchema: Schema<TransferType2Enum> = stringEnum(
  TransferType2Enum
);
