/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  Digital = 'digital',
  Place = 'place',
  Special = 'special',
  Unresolved = 'unresolved',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(
  TransactionTypeEnum
);
