/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransactionsGetRequestOptions,
  transactionsGetRequestOptionsSchema,
} from './transactionsGetRequestOptions.js';

/** TransactionsGetRequest defines the request schema for `/transactions/get` */
export interface TransactionsGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** An optional object to be used with the request. If specified, `options` must not be `null`. */
  options?: TransactionsGetRequestOptions;
  /** The access token associated with the Item data is being requested for. */
  accessToken: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The earliest date for which data should be returned. Dates should be formatted as YYYY-MM-DD. */
  startDate: string;
  /** The latest date for which data should be returned. Dates should be formatted as YYYY-MM-DD. */
  endDate: string;
  additionalProperties?: Record<string, unknown>;
}

export const transactionsGetRequestSchema: Schema<TransactionsGetRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        clientId: ['client_id', optional(string())],
        options: ['options', optional(transactionsGetRequestOptionsSchema)],
        accessToken: ['access_token', string()],
        secret: ['secret', optional(string())],
        startDate: ['start_date', string()],
        endDate: ['end_date', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
