/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransferType1
 */
export enum TransferType1 {
  Debit = 'debit',
  Credit = 'credit',
}

/**
 * Schema for TransferType1
 */
export const transferType1Schema: Schema<TransferType1> = stringEnum(
  TransferType1,
  true
);
