/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Information about the device being used to initiate the authorization. */
export interface TransferAuthorizationDevice {
  /** The IP address of the device being used to initiate the authorization. */
  ipAddress?: string;
  /** The user agent of the device being used to initiate the authorization. */
  userAgent?: string;
}

export const transferAuthorizationDeviceSchema: Schema<TransferAuthorizationDevice> = object(
  {
    ipAddress: ['ip_address', optional(string())],
    userAgent: ['user_agent', optional(string())],
  }
);
