/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Error, errorSchema } from './error.js';

/** Fired when transaction(s) for an Item are deleted. The deleted transaction IDs are included in the webhook payload. Plaid will typically check for deleted transaction data several times a day. */
export interface TransactionsRemovedWebhook {
  /** `TRANSACTIONS` */
  webhookType: string;
  /** `TRANSACTIONS_REMOVED` */
  webhookCode: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
  /** An array of `transaction_ids` corresponding to the removed transactions */
  removedTransactions: string[];
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
}

export const transactionsRemovedWebhookSchema: Schema<TransactionsRemovedWebhook> = lazy(
  () =>
    object({
      webhookType: ['webhook_type', string()],
      webhookCode: ['webhook_code', string()],
      error: ['error', optional(errorSchema)],
      removedTransactions: ['removed_transactions', array(string())],
      itemId: ['item_id', string()],
    })
);
