/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransferType2
 */
export enum TransferType2 {
  Debit = 'debit',
  Credit = 'credit',
}

/**
 * Schema for TransferType2
 */
export const transferType2Schema: Schema<TransferType2> = stringEnum(
  TransferType2,
  true
);
