/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type3
 */
export enum Type3 {
  EnumExtendedGraduated = 'extended graduated',
  EnumExtendedStandard = 'extended standard',
  Graduated = 'graduated',
  EnumIncomecontingentRepayment = 'income-contingent repayment',
  EnumIncomebasedRepayment = 'income-based repayment',
  Interestonly = 'interest-only',
  Other = 'other',
  EnumPayAsYouEarn = 'pay as you earn',
  EnumRevisedPayAsYouEarn = 'revised pay as you earn',
  Standard = 'standard',
}

/**
 * Schema for Type3
 */
export const type3Schema: Schema<Type3> = stringEnum(Type3, true);
