/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type2
 */
export enum Type2 {
  Cancelled = 'cancelled',
  EnumChargedOff = 'charged off',
  Claim = 'claim',
  Consolidated = 'consolidated',
  Deferment = 'deferment',
  Delinquent = 'delinquent',
  Discharged = 'discharged',
  Extension = 'extension',
  Forbearance = 'forbearance',
  EnumInGrace = 'in grace',
  EnumInMilitary = 'in military',
  EnumInSchool = 'in school',
  EnumNotFullyDisbursed = 'not fully disbursed',
  Other = 'other',
  EnumPaidInFull = 'paid in full',
  Refunded = 'refunded',
  Repayment = 'repayment',
  Transferred = 'transferred',
}

/**
 * Schema for Type2
 */
export const type2Schema: Schema<Type2> = stringEnum(Type2, true);
