/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type4Enum
 */
export enum Type4Enum {
  Buy = 'buy',
  Sell = 'sell',
  Cancel = 'cancel',
  Cash = 'cash',
  Fee = 'fee',
  Transfer = 'transfer',
}

/**
 * Schema for Type4Enum
 */
export const type4EnumSchema: Schema<Type4Enum> = stringEnum(Type4Enum);
