/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type4
 */
export enum Type4 {
  Buy = 'buy',
  Sell = 'sell',
  Cancel = 'cancel',
  Cash = 'cash',
  Fee = 'fee',
  Transfer = 'transfer',
}

/**
 * Schema for Type4
 */
export const type4Schema: Schema<Type4> = stringEnum(Type4, true);
