/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type5
 */
export enum Type5 {
  Bonus = 'bonus',
  Overtime = 'overtime',
  Regular = 'regular',
}

/**
 * Schema for Type5
 */
export const type5Schema: Schema<Type5> = stringEnum(Type5, true);
