/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** List of unofficial currency codes */
export interface UnofficialCurrencyCodeList {
  /** Cardano */
  aDA: string;
  /** Basic Attention Token */
  bAT: string;
  /** Bitcoin Cash */
  bCH: string;
  /** Binance Coin */
  bNB: string;
  /** Bitcoin */
  bTC: string;
  /** Bitcoin Gold */
  bTG: string;
  /** Chinese Yuan (offshore) */
  cNH: string;
  /** Dash */
  dASH: string;
  /** Dogecoin */
  dOGE: string;
  /** Ethereum Classic */
  eTC: string;
  /** Ethereum */
  eTH: string;
  /** Pence sterling, i.e. British penny */
  gBX: string;
  /** Lisk */
  lSK: string;
  /** Neo */
  nEO: string;
  /** OmiseGO */
  oMG: string;
  /** Qtum */
  qTUM: string;
  /** TehterUS */
  uSDT: string;
  /** Stellar Lumen */
  xLM: string;
  /** Monero */
  xMR: string;
  /** Ripple */
  xRP: string;
  /** Zcash */
  zEC: string;
  /** 0x */
  zRX: string;
}

export const unofficialCurrencyCodeListSchema: Schema<UnofficialCurrencyCodeList> = object(
  {
    aDA: ['ADA', string()],
    bAT: ['BAT', string()],
    bCH: ['BCH', string()],
    bNB: ['BNB', string()],
    bTC: ['BTC', string()],
    bTG: ['BTG', string()],
    cNH: ['CNH', string()],
    dASH: ['DASH', string()],
    dOGE: ['DOGE', string()],
    eTC: ['ETC', string()],
    eTH: ['ETH', string()],
    gBX: ['GBX', string()],
    lSK: ['LSK', string()],
    nEO: ['NEO', string()],
    oMG: ['OMG', string()],
    qTUM: ['QTUM', string()],
    uSDT: ['USDT', string()],
    xLM: ['XLM', string()],
    xMR: ['XMR', string()],
    xRP: ['XRP', string()],
    zEC: ['ZEC', string()],
    zRX: ['ZRX', string()],
  }
);
