/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UpdateType
 */
export enum UpdateType {
  Background = 'background',
  UserPresentRequired = 'user_present_required',
}

/**
 * Schema for UpdateType
 */
export const updateTypeSchema: Schema<UpdateType> = stringEnum(
  UpdateType,
  true
);
