/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ValueEnum
 */
export enum ValueEnum {
  Monthly = 'monthly',
  Semimonthly = 'semimonthly',
  Weekly = 'weekly',
  Biweekly = 'biweekly',
  Unknown = 'unknown',
  Null = 'null',
}

/**
 * Schema for ValueEnum
 */
export const valueEnumSchema: Schema<ValueEnum> = stringEnum(ValueEnum);
