/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Value
 */
export enum Value {
  Monthly = 'monthly',
  Semimonthly = 'semimonthly',
  Weekly = 'weekly',
  Biweekly = 'biweekly',
  Unknown = 'unknown',
  Null = 'null',
}

/**
 * Schema for Value
 */
export const valueSchema: Schema<Value> = stringEnum(Value, true);
