/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VerificationRefreshStatusEnum
 */
export enum VerificationRefreshStatusEnum {
  VERIFICATIONREFRESHSTATUSUSERPRESENCEREQUIRED = 'VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED',
}

/**
 * Schema for VerificationRefreshStatusEnum
 */
export const verificationRefreshStatusEnumSchema: Schema<VerificationRefreshStatusEnum> = stringEnum(
  VerificationRefreshStatusEnum
);
