/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VerificationStatus3Enum
 */
export enum VerificationStatus3Enum {
  VERIFICATIONSTATUSPROCESSINGCOMPLETE = 'VERIFICATION_STATUS_PROCESSING_COMPLETE',
  VERIFICATIONSTATUSDOCUMENTREJECTED = 'VERIFICATION_STATUS_DOCUMENT_REJECTED',
  VERIFICATIONSTATUSPROCESSINGFAILED = 'VERIFICATION_STATUS_PROCESSING_FAILED',
}

/**
 * Schema for VerificationStatus3Enum
 */
export const verificationStatus3EnumSchema: Schema<VerificationStatus3Enum> = stringEnum(
  VerificationStatus3Enum
);
