/**
 * Plaid
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VerificationStatus
 */
export enum VerificationStatus {
  Verified = 'VERIFIED',
  Unverified = 'UNVERIFIED',
  NeedsInfo = 'NEEDS_INFO',
  UnableToVerify = 'UNABLE_TO_VERIFY',
  Unknown = 'UNKNOWN',
}

/**
 * Schema for VerificationStatus
 */
export const verificationStatusSchema: Schema<VerificationStatus> = stringEnum(
  VerificationStatus,
  true
);
