/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Fired when an Item was not verified via automated micro-deposits after ten days since the automated micro-deposit was made. */
export interface VerificationExpiredWebhook {
  /** `AUTH` */
  webhookType: string;
  /** `VERIFICATION_EXPIRED` */
  webhookCode: string;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  /** The `account_id` of the account associated with the webhook */
  accountId: string;
}

export const verificationExpiredWebhookSchema: Schema<VerificationExpiredWebhook> = object(
  {
    webhookType: ['webhook_type', string()],
    webhookCode: ['webhook_code', string()],
    itemId: ['item_id', string()],
    accountId: ['account_id', string()],
  }
);
