/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** WebhookVerificationKeyGetRequest defines the request schema for `/webhook_verification_key/get` */
export interface WebhookVerificationKeyGetRequest {
  /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
  clientId?: string;
  /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
  secret?: string;
  /** The key ID ( `kid` ) from the JWT header. */
  keyId: string;
}

export const webhookVerificationKeyGetRequestSchema: Schema<WebhookVerificationKeyGetRequest> = object(
  {
    clientId: ['client_id', optional(string())],
    secret: ['secret', optional(string())],
    keyId: ['key_id', string()],
  }
);
