/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { JWKPublicKey, jWKPublicKeySchema } from './jWKPublicKey.js';

/** WebhookVerificationKeyGetResponse defines the response schema for `/webhook_verification_key/get` */
export interface WebhookVerificationKeyGetResponse {
  /** A JSON Web Key (JWK) that can be used in conjunction with [JWT libraries](https://jwt.io/#libraries-io) to verify Plaid webhooks */
  key: JWKPublicKey;
  /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
  requestId: string;
}

export const webhookVerificationKeyGetResponseSchema: Schema<WebhookVerificationKeyGetResponse> = lazy(
  () =>
    object({
      key: ['key', jWKPublicKeySchema],
      requestId: ['request_id', string()],
    })
);
