/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Error, errorSchema } from './error.js';

/** Fired when an Item's webhook is updated. This will be sent to the newly specified webhook. */
export interface WebhookUpdateAcknowledgedWebhook {
  /** `ITEM` */
  webhookType: string;
  /** `WEBHOOK_UPDATE_ACKNOWLEDGED` */
  webhookCode: string;
  /** The `item_id` of the Item associated with this webhook, warning, or error */
  itemId: string;
  /** The new webhook URL */
  newWebhookUrl: string;
  /** We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred. */
  error?: Error;
}

export const webhookUpdateAcknowledgedWebhookSchema: Schema<WebhookUpdateAcknowledgedWebhook> = lazy(
  () =>
    object({
      webhookType: ['webhook_type', string()],
      webhookCode: ['webhook_code', string()],
      itemId: ['item_id', string()],
      newWebhookUrl: ['new_webhook_url', string()],
      error: ['error', optional(errorSchema)],
    })
);
