/**
 * The Plaid APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  compositeAuthenticationProvider,
  customHeaderAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';

export function createAuthProviderFromConfig(config: Partial<Configuration>) {
  const authConfig = {
    pLAIDCLIENTID:
      config.pLAIDCLIENTIDCredentials &&
      customHeaderAuthenticationProvider(config.pLAIDCLIENTIDCredentials),
    pLAIDSECRET:
      config.pLAIDSECRETCredentials &&
      customHeaderAuthenticationProvider(config.pLAIDSECRETCredentials),
    plaidVersion:
      config.plaidVersionCredentials &&
      customHeaderAuthenticationProvider(config.plaidVersionCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}
