/**
 * Plaid
 *
 * Stainless-parity customization (hand-written, not generated by APIMatic).
 *
 * Provides a single `PlaidApi` facade that mirrors the shape of the official
 * `plaid-node` (Stainless / OpenAPI-Generator) SDK: one class, constructed with
 * `new PlaidApi(config)`, exposing every endpoint as a flat, fully-typed method
 * (e.g. `plaid.authGet(...)`, `plaid.accountsGet(...)`).
 *
 * Under the hood it still uses APIMatic's modular controllers and the
 * `@apimatic/core` runtime — a single shared `Client` backs all controllers,
 * and their methods are mixed onto the facade instance. No controller files are
 * modified, so this stays compatible across regenerations.
 */

import { Client } from './client.js';
import { Configuration } from './configuration.js';
import { AccountsApi } from './controllers/accountsApi.js';
import { ApplicationApi } from './controllers/applicationApi.js';
import { AssetReportApi } from './controllers/assetReportApi.js';
import { AuthApi } from './controllers/authApi.js';
import { BankTransferApi } from './controllers/bankTransferApi.js';
import { CategoriesApi } from './controllers/categoriesApi.js';
import { DepositSwitchApi } from './controllers/depositSwitchApi.js';
import { EmployersApi } from './controllers/employersApi.js';
import { IdentityApi } from './controllers/identityApi.js';
import { IncomeApi } from './controllers/incomeApi.js';
import { InstitutionsApi } from './controllers/institutionsApi.js';
import { InvestmentsApi } from './controllers/investmentsApi.js';
import { ItemApi } from './controllers/itemApi.js';
import { LiabilitiesApi } from './controllers/liabilitiesApi.js';
import { LinkApi } from './controllers/linkApi.js';
import { PaymentInitiationApi } from './controllers/paymentInitiationApi.js';
import { ProcessorApi } from './controllers/processorApi.js';
import { SandboxApi } from './controllers/sandboxApi.js';
import { SignalApi } from './controllers/signalApi.js';
import { TransactionsApi } from './controllers/transactionsApi.js';
import { TransferApi } from './controllers/transferApi.js';
import { WebhookVerificationKeyApi } from './controllers/webhookVerificationKeyApi.js';

/** Default Plaid API version header, matching the official plaid-node SDK. */
export const DEFAULT_PLAID_VERSION = '2020-09-14';

/**
 * The flat surface of `PlaidApi`: the union of every controller's endpoint
 * methods, so `new PlaidApi(config)` exposes all endpoints directly.
 */
export type PlaidApi = AccountsApi &
  ApplicationApi &
  AssetReportApi &
  AuthApi &
  BankTransferApi &
  CategoriesApi &
  DepositSwitchApi &
  EmployersApi &
  IdentityApi &
  IncomeApi &
  InstitutionsApi &
  InvestmentsApi &
  ItemApi &
  LiabilitiesApi &
  LinkApi &
  PaymentInitiationApi &
  ProcessorApi &
  SandboxApi &
  SignalApi &
  TransactionsApi &
  TransferApi &
  WebhookVerificationKeyApi;

class PlaidApiClient {
  constructor(config?: Partial<Configuration>) {
    const merged: Partial<Configuration> = { ...config };
    // Mirror plaid-node, which sends `Plaid-Version: 2020-09-14` by default.
    if (!merged.plaidVersionCredentials) {
      merged.plaidVersionCredentials = { 'Plaid-Version': DEFAULT_PLAID_VERSION };
    }

    const client = new Client(merged);
    const controllers = [
      new AccountsApi(client),
      new ApplicationApi(client),
      new AssetReportApi(client),
      new AuthApi(client),
      new BankTransferApi(client),
      new CategoriesApi(client),
      new DepositSwitchApi(client),
      new EmployersApi(client),
      new IdentityApi(client),
      new IncomeApi(client),
      new InstitutionsApi(client),
      new InvestmentsApi(client),
      new ItemApi(client),
      new LiabilitiesApi(client),
      new LinkApi(client),
      new PaymentInitiationApi(client),
      new ProcessorApi(client),
      new SandboxApi(client),
      new SignalApi(client),
      new TransactionsApi(client),
      new TransferApi(client),
      new WebhookVerificationKeyApi(client),
    ];

    // Flatten every controller's endpoint methods onto this instance. Method
    // names are unique across controllers, so there are no collisions. Each
    // method is bound to its controller so `this.createRequest` stays intact.
    for (const controller of controllers) {
      const proto = Object.getPrototypeOf(controller);
      for (const name of Object.getOwnPropertyNames(proto)) {
        if (name === 'constructor') {
          continue;
        }
        const value = (controller as unknown as Record<string, unknown>)[name];
        if (typeof value === 'function') {
          (this as unknown as Record<string, unknown>)[name] = value.bind(
            controller
          );
        }
      }
    }
  }
}

/**
 * A single client for the entire Plaid API.
 *
 * @example
 * const plaid = new PlaidApi({
 *   environment: Environment.Sandbox,
 *   plaidClientIdCredentials: { 'PLAID-CLIENT-ID': clientId },
 *   plaidSecretCredentials: { 'PLAID-SECRET': secret },
 * });
 * const { result } = await plaid.authGet({ accessToken });
 */
export const PlaidApi = PlaidApiClient as unknown as {
  new (config?: Partial<Configuration>): PlaidApi;
};
